-- Migration 010: Seed 450+ additional perfumes for FragBase
-- Uses INSERT OR IGNORE to avoid duplicates with existing data
-- All real fragrances with accurate note pyramids

-- BATCH 1: Chanel, Dior (s001-s020)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s001', 'No. 5', 'Chanel', 1921, 'Parfum', 'Aldehydes, Neroli, Ylang-Ylang, Bergamot', 'Jasmine, Rose, Lily of the Valley, Iris', 'Sandalwood, Vetiver, Vanilla, Musk', 'The most iconic perfume ever. A timeless floral aldehyde masterpiece.'),
('s002', 'Chance', 'Chanel', 2002, 'Eau de Parfum', 'Pink Pepper, Pineapple, Hyacinth', 'Jasmine, Iris, Citrus', 'Amber, Patchouli, Musk, Vanilla', 'A round fragrance of unexpected encounters.'),
('s003', 'Allure Homme Sport', 'Chanel', 2004, 'Eau de Toilette', 'Orange, Aldehydes, Sea Notes', 'Neroli, Cedar, Pepper', 'Tonka Bean, Musk, Amber, Vanilla', 'Dynamic fresh woody for the active man.'),
('s004', 'Coco Noir', 'Chanel', 2012, 'Eau de Parfum', 'Grapefruit, Bergamot', 'Rose, Jasmine, Narcissus, Geranium', 'Sandalwood, Patchouli, Tonka Bean, Vanilla', 'Dark and mysterious oriental inspired by Venice at night.'),
('s005', 'Gabrielle', 'Chanel', 2017, 'Eau de Parfum', 'Mandarin, Grapefruit, Blackcurrant', 'Ylang-Ylang, Jasmine, Orange Blossom, Tuberose', 'Sandalwood, Cashmeran, Musk', 'A radiant solar floral. Luminous and bold.'),
('s006', 'Platinum Egoiste', 'Chanel', 1993, 'Eau de Toilette', 'Lavender, Rosemary, Petit Grain', 'Clary Sage, Geranium, Jasmine', 'Oakmoss, Vetiver, Cedar, Sandalwood', 'Sophisticated fougere. Fresh and herbal.'),
('s007', 'Chance Eau Fraiche', 'Chanel', 2007, 'Eau de Toilette', 'Lemon, Grapefruit, Quince', 'Jasmine, Hyacinth, Water Lily', 'Teak Wood, Amber, Musk, Vetiver', 'A sparkling fresh take on Chance.'),
('s008', 'Allure Sensuelle', 'Chanel', 2005, 'Eau de Parfum', 'Mandarin, Bergamot, Pink Pepper', 'Rose, Jasmine, May Rose', 'Sandalwood, Vanilla, Musk, Amber', 'A warm and sensual oriental floral.'),
('s009', 'No. 19', 'Chanel', 1970, 'Eau de Parfum', 'Neroli, Bergamot, Galbanum', 'Iris, Jasmine, Lily of the Valley, Rose', 'Vetiver, Oakmoss, Leather, Musk', 'A bold green floral. Crisp and sophisticated.'),
('s010', 'Pour Monsieur', 'Chanel', 1955, 'Eau de Toilette', 'Lemon, Bergamot, Neroli, Mandarin', 'Tarragon, Carnation, Orris', 'Oakmoss, Vetiver, Sandalwood, Labdanum', 'Classic gentlemanly citrus chypre.'),
('s011', 'Sauvage Eau de Parfum', 'Dior', 2018, 'Eau de Parfum', 'Bergamot, Pepper, Nutmeg', 'Lavender, Star Anise, Sichuan Pepper', 'Ambroxan, Vanilla, Cedar', 'A more intense Sauvage with spicy vanilla warmth.'),
('s012', 'Fahrenheit', 'Dior', 1988, 'Eau de Toilette', 'Lavender, Mandarin, Hawthorn, Cedar', 'Nutmeg, Violet Leaf', 'Leather, Amber, Vetiver, Tonka Bean', 'Groundbreaking masculine with a unique petrol note.'),
('s013', 'Eau Sauvage', 'Dior', 1966, 'Eau de Toilette', 'Lemon, Bergamot, Basil, Rosemary', 'Jasmine, Coriander, Patchouli, Carnation', 'Vetiver, Oakmoss, Musk, Amber', 'The original gentleman citrus cologne.'),
('s014', 'Poison', 'Dior', 1985, 'Eau de Toilette', 'Plum, Coriander, Wildberries', 'Tuberose, Carnation, Cinnamon, Opoponax', 'Amber, Sandalwood, Musk, Cedar', 'Bold and provocative 80s oriental powerhouse.'),
('s015', 'Hypnotic Poison', 'Dior', 1998, 'Eau de Toilette', 'Apricot, Plum, Coconut', 'Tuberose, Jasmine, Lily of the Valley, Rose', 'Vanilla, Almond, Musk, Sandalwood', 'Intoxicating almond vanilla oriental.'),
('s016', 'Joy', 'Dior', 2018, 'Eau de Parfum', 'Bergamot, Mandarin', 'Grasse Rose, Jasmine, Peach', 'Sandalwood, Cashmere Wood, Musk', 'A luminous floral celebrating the essence of joy.'),
('s017', 'Dior Homme', 'Dior', 2005, 'Eau de Toilette', 'Lavender, Sage, Bergamot', 'Iris, Amber, Pear', 'Vetiver, Leather, Cacao', 'Elegant iris-based masculine. Refined and powdery.'),
('s018', 'Dior Homme Intense', 'Dior', 2011, 'Eau de Parfum', 'Lavender, Iris, Pear', 'Virginia Cedar, Ambroxan', 'Vetiver, Leather', 'Sophisticated iris-forward masculine. Powdery and woody.'),
('s019', 'Miss Dior Blooming Bouquet', 'Dior', 2014, 'Eau de Toilette', 'Mandarin, Pink Pepper', 'Peony, Rose', 'White Musk, Apricot', 'A delicate floral bouquet. Light and romantic.'),
('s020', 'Dior Addict', 'Dior', 2002, 'Eau de Parfum', 'Mandarin Leaf, Silk Tree Flower', 'Night Queen Flower, Rose, Orange Blossom', 'Vanilla, Sandalwood, Tonka Bean', 'A sensual oriental floral. Addictive and glamorous.');

-- BATCH 2: Tom Ford (s021-s040)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s021', 'Black Orchid', 'Tom Ford', 2006, 'Eau de Parfum', 'Truffle, Blackcurrant, Ylang-Ylang, Bergamot', 'Orchid, Lotus, Fruity Notes', 'Patchouli, Incense, Vanilla, Vetiver', 'A luxurious dark floral. Opulent and mysterious.'),
('s022', 'Fucking Fabulous', 'Tom Ford', 2017, 'Eau de Parfum', 'Lavender, Clary Sage, Almond', 'Leather, Cashmeran, Orris', 'Tonka Bean, Amber, Vanilla', 'Bold and provocative. Leather and almond.'),
('s023', 'Bitter Peach', 'Tom Ford', 2020, 'Eau de Parfum', 'Blood Orange, Cardamom, Davana', 'Peach, Rum, Heliotrope', 'Sandalwood, Patchouli, Cashmeran, Benzoin', 'A ripe boozy peach gourmand. Lush and indulgent.'),
('s024', 'Rose Prick', 'Tom Ford', 2020, 'Eau de Parfum', 'May Rose, Turkish Rose, Sichuan Pepper', 'Turmeric, Bulgarian Rose', 'Patchouli, Tonka Bean, Oud', 'A thorny rose with spice. Beautiful and daring.'),
('s025', 'Ombre Leather', 'Tom Ford', 2018, 'Eau de Parfum', 'Cardamom, Violet Leaf', 'Jasmine Sambac, Leather', 'Patchouli, Amber, Moss', 'Rugged leather. Raw and sensual.'),
('s026', 'Soleil Blanc', 'Tom Ford', 2016, 'Eau de Parfum', 'Bergamot, Cardamom, Pink Pepper, Pistachio', 'Ylang-Ylang, Tuberose, Jasmine', 'Coconut, Amber, Musk, Tonka Bean', 'Sun-drenched luxury. Creamy coconut and amber.'),
('s027', 'Cafe Rose', 'Tom Ford', 2012, 'Eau de Parfum', 'Saffron, Rose, Coffee', 'Turkish Rose, Incense', 'Sandalwood, Oud, Patchouli', 'Rich rose with coffee and saffron. Exotic.'),
('s028', 'Grey Vetiver', 'Tom Ford', 2009, 'Eau de Parfum', 'Grapefruit, Orange Blossom, Sage', 'Orris, Nutmeg', 'Vetiver, Oakmoss, Amber', 'Refined vetiver. Clean and sophisticated.'),
('s029', 'Tobacco Oud', 'Tom Ford', 2013, 'Eau de Parfum', 'Whiskey, Cinnamon', 'Tobacco, Pimento, Oud', 'Sandalwood, Patchouli, Benzoin', 'Dark and smoky. Tobacco and oud entwined.'),
('s030', 'Costa Azzurra', 'Tom Ford', 2014, 'Eau de Parfum', 'Seaweed, Lemon, Citrus', 'Juniper, Myrtle', 'Amber, Driftwood, Vetiver, Musk', 'Mediterranean coastal. Woody and aromatic.'),
('s031', 'Noir de Noir', 'Tom Ford', 2007, 'Eau de Parfum', 'Saffron, Black Rose, Black Truffle', 'Rose, Vanilla Orchid', 'Oud, Patchouli, Musk, Vanilla', 'Dark romantic masterpiece. Rose and truffle.'),
('s032', 'White Patchouli', 'Tom Ford', 2008, 'Eau de Parfum', 'Peony, Bergamot, Coriander', 'Rose Absolute, Jasmine', 'Patchouli, Amber, Vanilla, Incense', 'Bright and luminous patchouli.'),
('s033', 'Mandarino di Amalfi', 'Tom Ford', 2014, 'Eau de Parfum', 'Mandarin, Tarragon, Lemon, Grapefruit', 'Basil, Mint, Shiso Leaf, Orange Blossom', 'Amber, Labdanum, Musk', 'Vibrant Italian citrus like the Amalfi Coast.'),
('s034', 'Noir Extreme', 'Tom Ford', 2015, 'Eau de Parfum', 'Mandarin, Nutmeg, Cardamom, Saffron', 'Rose, Jasmine, Orange Blossom', 'Amber, Vanilla, Sandalwood, Woody Notes', 'A warm spicy oriental. Smooth and seductive.'),
('s035', 'Beau de Jour', 'Tom Ford', 2019, 'Eau de Parfum', 'Lavender, Rosemary, Grapefruit, Mint', 'Geranium, Black Pepper, Basil', 'Oakmoss, Amber, Patchouli', 'Classic barbershop fougere elevated to luxury.'),
('s036', 'Velvet Orchid', 'Tom Ford', 2014, 'Eau de Parfum', 'Honey, Rum, Mandarin, Bergamot', 'Orchid, Rose Oil, Heliotrope', 'Suede, Sandalwood, Myrrh, Benzoin', 'A sensual floral oriental. Warm and feminine.'),
('s037', 'Jasmin Rouge', 'Tom Ford', 2011, 'Eau de Parfum', 'Mandarin, Ginger, Pink Pepper', 'Jasmine Sambac, Cinnamon, Clary Sage', 'Sandalwood, Labdanum, Cashmeran, Musk', 'A spicy jasmine. Exotic and intoxicating.'),
('s038', 'Metallique', 'Tom Ford', 2019, 'Eau de Parfum', 'Caraway, Black Pepper, Pink Pepper', 'Jasmine, Heliotrope, Chinese Magnolia', 'Amber, Sandalwood, Musk, Patchouli', 'A floral with metallic edge. Cool and modern.'),
('s039', 'Ebene Fume', 'Tom Ford', 2020, 'Eau de Parfum', 'Black Pepper, Clove', 'Palo Santo, Leather, Cypriol', 'Ebony Wood, Vetiver, Guaiac Wood', 'Dark and smoky wood. Ritualistic and deep.'),
('s040', 'White Suede', 'Tom Ford', 2009, 'Eau de Parfum', 'Thyme, Pink Pepper', 'Rose, Lily of the Valley, Suede', 'Amber, Musk, Sandalwood', 'Clean musk and suede. Quietly magnetic.');

-- BATCH 3: Creed (s041-s050)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s041', 'Viking', 'Creed', 2017, 'Eau de Parfum', 'Bergamot, Lemon, Pink Pepper, Mandarin', 'Rose, Geranium, Jasmine', 'Sandalwood, Vetiver, Tonka Bean, Patchouli', 'Fresh spicy fragrance inspired by Norse explorers.'),
('s042', 'Royal Oud', 'Creed', 2011, 'Eau de Parfum', 'Lemon, Pink Pepper, Galbanum', 'Cedar, Angelica Root', 'Sandalwood, Oud, Tonka Bean, Musk', 'Refined woody oud. Regal and sophisticated.'),
('s043', 'Millesime Imperial', 'Creed', 1995, 'Eau de Parfum', 'Sea Salt, Bergamot, Lemon, Mandarin', 'Iris, Marine Notes', 'Musk, Amber, Woody Notes', 'Fresh aquatic classic. Sea salt and iris.'),
('s044', 'Original Santal', 'Creed', 2005, 'Eau de Parfum', 'Bergamot, Lavender, Juniper Berry', 'Cinnamon, Jasmine, Orange Blossom', 'Sandalwood, Vanilla, Musk, Tonka Bean', 'Rich creamy sandalwood. Warm and inviting.'),
('s045', 'Himalaya', 'Creed', 2002, 'Eau de Parfum', 'Grapefruit, Lemon, Bergamot', 'Sandalwood, Musk', 'Ambergris, Cedar, Musk', 'Crisp mountainous fragrance. Invigorating.'),
('s046', 'Wind Flowers', 'Creed', 2021, 'Eau de Parfum', 'Bergamot, Orange Blossom', 'Jasmine, Tuberose, Iris', 'Musk, Sandalwood, Ambroxan', 'Delicate feminine floral. Airy and elegant.'),
('s047', 'Virgin Island Water', 'Creed', 2007, 'Eau de Parfum', 'Lime, Bergamot, Mandarin, Ginger', 'Coconut, Ylang-Ylang, Hibiscus, Jasmine', 'White Musk, Rum', 'Caribbean paradise in a bottle. Tropical and sunny.'),
('s048', 'Royal Water', 'Creed', 2009, 'Eau de Parfum', 'Peppermint, Bergamot, Lemon, Pineapple', 'Basil, Juniper', 'Ambergris, Musk, Cumin', 'Crisp aquatic aromatic. Sparkling and refreshing.'),
('s049', 'Original Vetiver', 'Creed', 2004, 'Eau de Parfum', 'Bergamot, Mandarin, Iris', 'Ginger, Vetiver', 'Ambergris, Musk, Cedar', 'Pure vetiver elegance. Clean and green.'),
('s050', 'Royal Princess Oud', 'Creed', 2015, 'Eau de Parfum', 'Italian Bergamot, Pink Pepper, Aldehydes', 'Rose, Vanilla', 'Oud, Musk', 'A feminine oud. Delicate rose and oud pairing.');

-- BATCH 4: Versace, Dolce & Gabbana, Paco Rabanne, JPG (s051-s075)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s051', 'Versace Pour Homme', 'Versace', 2008, 'Eau de Toilette', 'Lemon, Neroli, Bergamot, Citron', 'Hyacinth, Cedar, Clary Sage, Blue Wisteria', 'Amber, Musk, Saffron', 'A Mediterranean aromatic. Fresh and elegant.'),
('s052', 'Bright Crystal', 'Versace', 2006, 'Eau de Toilette', 'Pomegranate, Yuzu, Iced Accord', 'Magnolia, Peony, Lotus', 'Amber, Musk, Mahogany', 'Sparkling and luminous. Crystal clarity in a bottle.'),
('s053', 'Crystal Noir', 'Versace', 2004, 'Eau de Toilette', 'Ginger, Cardamom, Pepper', 'Coconut, Gardenia, Peony', 'Sandalwood, Musk, Amber', 'Exotic and mysterious oriental floral.'),
('s054', 'Eros Pour Femme', 'Versace', 2014, 'Eau de Parfum', 'Lemon, Pomegranate, Bergamot', 'Peony, Jasmine Sambac, Lemon Blossom', 'Sandalwood, Musk, Ambroxan, Woody Notes', 'A sensual feminine counterpart to Eros.'),
('s055', 'Yellow Diamond', 'Versace', 2011, 'Eau de Toilette', 'Lemon, Bergamot, Neroli, Pear', 'Freesia, Mimosa, Water Lily, Nymphaea', 'Amber, Guaiac Wood, Musk', 'Luminous and sparkling. Pure as a diamond.'),
('s056', 'Eros Flame', 'Versace', 2018, 'Eau de Parfum', 'Mandarin, Black Pepper, Lemon, Chinotto', 'Rosemary, Pepper, Geranium', 'Tonka Bean, Cedarwood, Sandalwood, Patchouli', 'Fiery and passionate take on Eros.'),
('s057', 'The Dreamer', 'Versace', 1996, 'Eau de Toilette', 'Tarragon, Artemisia, Juniper', 'Flax Blossom, Lily, Tobacco', 'Cedar, Amber, Musk, Iris', 'Herbal and dreamy. A romantic masculine classic.'),
('s058', 'K by Dolce & Gabbana', 'Dolce & Gabbana', 2019, 'Eau de Parfum', 'Blood Orange, Juniper Berry, Citrus', 'Geranium, Clary Sage, Pimento', 'Cedarwood, Vetiver, Patchouli', 'A regal woody aromatic for the modern king.'),
('s059', 'The Only One', 'Dolce & Gabbana', 2018, 'Eau de Parfum', 'Violet, Grapefruit, Bergamot', 'Coffee, Iris, Violet', 'Patchouli, Cedar, Sugar, Caramel', 'A captivating coffee floral. Addictive and sweet.'),
('s060', 'Dolce', 'Dolce & Gabbana', 2014, 'Eau de Parfum', 'Neroli, Papaya Flower', 'White Amaryllis, White Daffodil, White Water Lily', 'Cashmeran, Musk, Sandalwood', 'A soft white floral. Delicate and feminine.'),
('s061', 'Pour Homme', 'Dolce & Gabbana', 1994, 'Eau de Toilette', 'Bergamot, Neroli, Mandarin, Lemon', 'Lavender, Sage, Pepper, Cedar', 'Tobacco, Sandalwood, Tonka Bean, Musk', 'A refined classic masculine fougere.'),
('s062', 'L''Imperatrice', 'Dolce & Gabbana', 2009, 'Eau de Toilette', 'Watermelon, Kiwi, Pink Cyclamen', 'Jasmine, Pink Cyclamen', 'Musk, Lemon', 'A fruity fresh floral. Playful and feminine.'),
('s063', 'Devotion', 'Dolce & Gabbana', 2022, 'Eau de Parfum', 'Candied Citrus, Rum', 'Orange Blossom', 'Vanilla, Cedar', 'A gourmand oriental. Sweet and devoted.'),
('s064', '1 Million', 'Paco Rabanne', 2008, 'Eau de Toilette', 'Grapefruit, Mint, Blood Mandarin', 'Cinnamon, Spicy Notes, Rose', 'Leather, Amber, Patchouli', 'Bold and brash. Spicy leather with sweet amber.'),
('s065', 'Invictus Victory', 'Paco Rabanne', 2021, 'Eau de Parfum Extreme', 'Laurel Leaf, Ginger', 'Marine Accord, Incense, Cardamom', 'Amber, Guaiac Wood, Oud', 'An intense evolution of Invictus. Dark and smoky.'),
('s066', 'Phantom', 'Paco Rabanne', 2021, 'Eau de Toilette', 'Lemon, Lavender, Styralyl Acetate', 'Smoke, Lavender, Apple', 'Cashmeran, Vanilla, Vetiver', 'Futuristic aromatic. Tech-inspired freshness.'),
('s067', '1 Million Elixir', 'Paco Rabanne', 2022, 'Parfum', 'Apple, Saffron', 'Rose, Osmanthus', 'Vanilla, Amber, Tonka Bean, Vetiver', 'The richest 1 Million. Intense apple and saffron.'),
('s068', 'Lady Million', 'Paco Rabanne', 2010, 'Eau de Parfum', 'Raspberry, Bitter Orange, Lemon', 'Orange Blossom, Jasmine, Gardenia', 'Honey, Amber, Patchouli, Cashmere Wood', 'Glamorous and bold. Floral with honey amber.'),
('s069', 'Pure XS', 'Paco Rabanne', 2017, 'Eau de Toilette', 'Ginger, Grapefruit, Thyme, Bergamot', 'Vanilla, Cinnamon, Apple, Liquor', 'Myrrh, Woody Notes, Sugar, Patchouli, Cashmeran', 'Excessive and addictive. Spicy vanilla gourmand.'),
('s070', 'Fame', 'Paco Rabanne', 2022, 'Eau de Parfum', 'Mango, Incense', 'Jasmine', 'Sandalwood, Vanilla, Cedarwood', 'A feminine mango-jasmine scent. Modern icon.'),
('s071', 'Le Male', 'Jean Paul Gaultier', 1995, 'Eau de Toilette', 'Lavender, Mint, Cardamom, Bergamot', 'Cinnamon, Cumin, Orange Blossom', 'Vanilla, Tonka Bean, Sandalwood, Cedar', 'The archetypal man. Lavender meets vanilla.'),
('s072', 'Le Male Le Parfum', 'Jean Paul Gaultier', 2020, 'Eau de Parfum', 'Cardamom, Lavender, Iris', 'Iris, Leather', 'Vanilla, Woody Notes, Tonka Bean, Oriental Notes', 'A richer Le Male with leather and iris.'),
('s073', 'Ultra Male', 'Jean Paul Gaultier', 2015, 'Eau de Toilette Intense', 'Pear, Bergamot, Lemon, Mint, Lavender', 'Cinnamon, Clary Sage, Black Lavender', 'Vanilla, Amber, Patchouli, Cedar', 'Le Male amplified. Sweet and powerful.'),
('s074', 'Scandal', 'Jean Paul Gaultier', 2017, 'Eau de Parfum', 'Blood Orange, Mandarin, Honey', 'Gardenia, Jasmine, Orange Blossom', 'Caramel, Beeswax, Patchouli, Cashmeran', 'A scandalous honeyed floral. Legs for days.'),
('s075', 'Classique', 'Jean Paul Gaultier', 1993, 'Eau de Toilette', 'Rose, Star Anise, Mandarin, Orange, Pear', 'Iris, Orchid, Ylang-Ylang, Ginger', 'Vanilla, Sandalwood, Musk, Amber', 'The feminine icon in a corset bottle.');

-- BATCH 5: YSL, Guerlain, Givenchy, Armani (s076-s100)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s076', 'L''Homme', 'Yves Saint Laurent', 2006, 'Eau de Toilette', 'Ginger, Bergamot, Lemon, Vetiver', 'Spices, Violet Leaf, White Pepper, Basil', 'Tonka Bean, Cedar, Vetiver', 'Refined ginger-vetiver masculine. Sophisticated.'),
('s077', 'Libre', 'Yves Saint Laurent', 2019, 'Eau de Parfum', 'Mandarin, Lavender, Blackcurrant', 'Orange Blossom, Jasmine, Lavender', 'Vanilla, Cedar, Musk, Ambergris', 'Free-spirited feminine. Lavender meets orange blossom.'),
('s078', 'Mon Paris', 'Yves Saint Laurent', 2016, 'Eau de Parfum', 'Strawberry, Raspberry, Pear, Bergamot', 'Peony, Datura, Jasmine', 'Patchouli, Cashmere Wood, White Musk, Ambroxan', 'A love story in Paris. Intensely romantic.'),
('s079', 'Opium', 'Yves Saint Laurent', 1977, 'Eau de Toilette', 'Mandarin, Plum, Clove, Coriander, Pepper, Bay Leaf', 'Jasmine, Rose, Carnation, Cinnamon, Peach', 'Sandalwood, Patchouli, Cedar, Vanilla, Amber, Musk', 'Legendary spicy oriental. Opulent and addictive.'),
('s080', 'Kouros', 'Yves Saint Laurent', 1981, 'Eau de Toilette', 'Coriander, Clary Sage, Artemisia, Bergamot', 'Cinnamon, Jasmine, Carnation, Geranium, Orris', 'Musk, Amber, Civet, Oakmoss, Tonka Bean, Incense', 'A powerful fougere. Bold and animalic.'),
('s081', 'Paris', 'Yves Saint Laurent', 1983, 'Eau de Parfum', 'Bergamot, Violet, Orange Blossom, Cassia', 'Rose, Iris, Lily of the Valley, Ylang-Ylang', 'Sandalwood, Cedar, Musk, Amber', 'A romantic rose. The scent of Parisian elegance.'),
('s082', 'Y Le Parfum', 'Yves Saint Laurent', 2021, 'Eau de Parfum', 'Bergamot, Ginger, Geranium', 'Sage, Juniper Berry, Lavender', 'Incense, Ambery Notes, Tonka Bean, Cedar', 'Bold and intense Y fragrance. Woody aromatic.'),
('s083', 'Libre Le Parfum', 'Yves Saint Laurent', 2022, 'Parfum', 'Mandarin, Lavender', 'Orange Blossom, Jasmine Sambac', 'Vanilla, Tonka Bean, Sandalwood', 'The richest Libre. Deep vanilla and jasmine.'),
('s084', 'Shalimar', 'Guerlain', 1925, 'Eau de Parfum', 'Bergamot, Lemon, Mandarin', 'Jasmine, Rose, May Rose, Orris', 'Vanilla, Tonka Bean, Incense, Sandalwood, Opoponax', 'Legendary oriental. A tale of eternal love.'),
('s085', 'Mon Guerlain', 'Guerlain', 2017, 'Eau de Parfum', 'Lavender, Bergamot', 'Iris, Jasmine Sambac', 'Vanilla, Sandalwood, Coumarin, Benzoin', 'A tribute to modern femininity. Lavender and vanilla.'),
('s086', 'L''Homme Ideal', 'Guerlain', 2014, 'Eau de Parfum', 'Almond, Rosemary, Bergamot', 'Jasmine, Bulgarian Rose', 'Leather, Vanilla, Tonka Bean, Sandalwood', 'The ideal man. Almond leather and vanilla.'),
('s087', 'Habit Rouge', 'Guerlain', 1965, 'Eau de Parfum', 'Bergamot, Lemon, Basil, Orange, Lime', 'Rose, Carnation, Cinnamon, Iris, Jasmine, Patchouli', 'Vanilla, Leather, Amber, Sandalwood, Cedar, Benzoin', 'The first masculine oriental. Vintage elegance.'),
('s088', 'Vetiver', 'Guerlain', 1961, 'Eau de Toilette', 'Lemon, Bergamot, Mandarin, Neroli, Coriander', 'Tobacco, Nutmeg, Geranium', 'Vetiver, Tonka Bean, Pepper, Cedar', 'The quintessential vetiver. Green and earthy.'),
('s089', 'Mitsouko', 'Guerlain', 1919, 'Eau de Parfum', 'Bergamot, Rose, Mandarin', 'Jasmine, Rose, Ylang-Ylang, Peach', 'Vetiver, Oakmoss, Amber, Spices, Cinnamon', 'A chypre legend. Mysterious and complex.'),
('s090', 'Santal Royal', 'Guerlain', 2016, 'Eau de Parfum', 'Cinnamon, Cardamom', 'Rose, Jasmine', 'Sandalwood, Oud, Leather, Amber', 'Royal sandalwood and oud. Majestic and warm.'),
('s091', 'L''Interdit', 'Givenchy', 2018, 'Eau de Parfum', 'Pear, Bergamot, Aldehydes', 'Tuberose, Orange Blossom, Jasmine', 'Patchouli, Vetiver, Ambroxan', 'A daring white floral. The thrill of the forbidden.'),
('s092', 'Gentleman Boisee', 'Givenchy', 2020, 'Eau de Parfum', 'Cardamom, Cinnamon', 'Iris, Orange Blossom', 'Patchouli, Sandalwood, Cocoa', 'A warm woody iris. Refined and commanding.'),
('s093', 'Irresistible', 'Givenchy', 2020, 'Eau de Parfum', 'Pear, Ambrette', 'Rose, Iris', 'Musk, Amber, Cedarwood', 'An irresistible rose with sparkling pear.'),
('s094', 'Ange ou Demon', 'Givenchy', 2006, 'Eau de Parfum', 'Saffron, Mandarin, Thyme', 'Lily, Orchid, White Freesia', 'Tonka Bean, Vanilla, Blond Wood', 'Angel or demon? A duality in fragrance.'),
('s095', 'Very Irresistible', 'Givenchy', 2003, 'Eau de Toilette', 'Anise, Lemon, Rose', 'Rose, Peony, Fantasy Rose', 'Patchouli, Vanilla, Musk', 'A joyful cascade of five roses.'),
('s096', 'Armani Code', 'Giorgio Armani', 2004, 'Eau de Toilette', 'Bergamot, Lemon', 'Olive Blossom, Star Anise', 'Guaiac Wood, Tonka Bean, Leather', 'A seductive code for men. Smooth and elegant.'),
('s097', 'Si', 'Giorgio Armani', 2013, 'Eau de Parfum', 'Blackcurrant, Mandarin', 'Rose, Freesia, May Rose', 'Vanilla, Patchouli, Woody Notes, Ambroxan', 'A modern chypre reinvention. Elegant yes.'),
('s098', 'Acqua di Gio Profondo', 'Giorgio Armani', 2020, 'Eau de Parfum', 'Bergamot, Green Mandarin, Aquatic Notes', 'Rosemary, Cypress, Lavender, Lentisk', 'Patchouli, Musk, Amber, Mineral Notes', 'An oceanic depth. Aquatic and mineral.'),
('s099', 'My Way', 'Giorgio Armani', 2020, 'Eau de Parfum', 'Orange Blossom, Bergamot', 'Tuberose, Jasmine Sambac', 'Cedarwood, White Musk, Vanilla', 'Discover who you are. Floral and luminous.'),
('s100', 'Si Passione', 'Giorgio Armani', 2018, 'Eau de Parfum', 'Pink Pepper, Pear, Bergamot', 'Rose, Jasmine, Heliotrope', 'Vanilla, Cedar, Patchouli, Amber, Musk', 'Passionate and bold. Red-lipped confidence.');

-- BATCH 6: Hermes, Prada, Burberry, Valentino, Carolina Herrera (s101-s125)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s101', 'Terre d''Hermes', 'Hermes', 2006, 'Eau de Toilette', 'Orange, Grapefruit, Flint', 'Pepper, Geranium, Patchouli', 'Vetiver, Benzoin, Cedar', 'Earth to sky. A woody mineral masterpiece.'),
('s102', 'Un Jardin sur le Nil', 'Hermes', 2005, 'Eau de Toilette', 'Green Mango, Lotus, Grapefruit', 'Calamus, Peony, Orange Blossom', 'Incense, Sycamore, Oakmoss', 'A garden on the Nile. Green and exotic.'),
('s103', 'Voyage d''Hermes', 'Hermes', 2010, 'Eau de Toilette', 'Cardamom, Lemon, Litsea Cubeba, Orange', 'Tea, Lily, Magnolia, Rose', 'Blonde Wood, Musk, Amber, Benzoin', 'A fragrant journey. Woody and aromatic.'),
('s104', 'Twilly d''Hermes', 'Hermes', 2017, 'Eau de Parfum', 'Ginger', 'Tuberose', 'Sandalwood, Vanilla', 'Young and free. Ginger-tuberose-sandalwood trio.'),
('s105', 'Un Jardin en Mediterranee', 'Hermes', 2003, 'Eau de Toilette', 'Lemon, Orange, Mandarin, Bergamot', 'Fig Leaf, Fig, Red Cedar', 'Olive Wood, Juniper, Cypress, Mastic', 'A fig garden by the Mediterranean Sea.'),
('s106', 'H24', 'Hermes', 2021, 'Eau de Toilette', 'Clary Sage, Narcissus', 'Sclarene, Rosemary', 'Iron Accord, Ambrox', 'A metallic green scent. Futuristic and clean.'),
('s107', 'Luna Rossa Carbon', 'Prada', 2017, 'Eau de Toilette', 'Bergamot, Pepper', 'Lavender', 'Ambroxan, Patchouli', 'Sleek and modern. Clean lavender-ambroxan.'),
('s108', 'L''Homme Prada', 'Prada', 2016, 'Eau de Toilette', 'Neroli, Cardamom, Iris', 'Iris, Geranium, Violet', 'Amber, Patchouli, Cedar, Sandalwood', 'A sophisticated iris masculine. Powdery elegance.'),
('s109', 'Luna Rossa Black', 'Prada', 2018, 'Eau de Parfum', 'Bergamot, Angelica', 'Coumarin, Patchouli', 'Amber, Sandalwood', 'Dark and mysterious Luna Rossa flanker.'),
('s110', 'Luna Rossa Ocean', 'Prada', 2021, 'Eau de Toilette', 'Bergamot, Iris', 'Vetiver, Sea Sage', 'Musk, Cashmere Wood, Patchouli', 'An oceanic fougere. Aquatic and fresh.'),
('s111', 'Candy', 'Prada', 2011, 'Eau de Parfum', 'Aldehydes', 'Caramel, Benzoin, Musks', 'Vanilla, Benzoin, Honey', 'Sweet as candy. Caramel and vanilla treat.'),
('s112', 'Infusion d''Iris', 'Prada', 2007, 'Eau de Parfum', 'Mandarin, Orange, Galbanum', 'Iris, Iris Butter, Incense', 'Cedar, Vetiver, Benzoin', 'Refined iris. Understated luxury.'),
('s113', 'Paradoxe', 'Prada', 2022, 'Eau de Parfum', 'Pear, Bergamot', 'Jasmine, Neroli', 'Amber, Musk, Vanilla', 'A paradox of contradictions. Modern femininity.'),
('s114', 'Burberry Her', 'Burberry', 2018, 'Eau de Parfum', 'Dark Berries, Blackcurrant, Blueberry, Raspberry', 'Jasmine, Violet', 'Amber, Musk, Dry Cocoa, Cashmeran', 'A London berry cocktail. Fun and sparkling.'),
('s115', 'Burberry Hero', 'Burberry', 2021, 'Eau de Parfum', 'Bergamot, Black Pepper, Elemi, Juniper', 'Cedarwood, Pine', 'Black Vanilla, Benzoin', 'Heroic and bold. Cedar and vanilla fusion.'),
('s116', 'Mr. Burberry', 'Burberry', 2016, 'Eau de Parfum', 'Lavender, Mint, Grapefruit, Tarragon', 'Cinnamon, Nutmeg, Birch', 'Benzoin, Sandalwood, Guaiac Wood, Oakmoss', 'A sophisticated modern British gentleman.'),
('s117', 'My Burberry', 'Burberry', 2014, 'Eau de Parfum', 'Sweet Pea, Bergamot', 'Geranium, Golden Quince, Freesia', 'Patchouli, Rain Notes', 'A London garden after the rain.'),
('s118', 'London', 'Burberry', 1995, 'Eau de Parfum', 'Honeysuckle, Green Apple, Black Currant', 'Jasmine, Rose, Sandalwood, Peach, Tiare Flower', 'Musk, Cedar, Vanilla', 'Classic British feminine. Warm and inviting.'),
('s119', 'Valentino Uomo Intense', 'Valentino', 2016, 'Eau de Parfum', 'Myrtle, Iris', 'Leather, Tonka Bean', 'Guaiac Wood, Vanilla', 'Intense leather and iris. Dark sophistication.'),
('s120', 'Born in Roma Uomo', 'Valentino', 2019, 'Eau de Toilette', 'Ginger, Sage, Mineral Accord', 'Smoked Vetiver, Violet Leaf', 'Guaiac Wood, Cashmeran, Benzoin', 'Roman-inspired aromatic. Smoky and refined.'),
('s121', 'Donna Born in Roma', 'Valentino', 2019, 'Eau de Parfum', 'Blackcurrant, Bergamot, Pink Pepper', 'Jasmine Grandiflorum, Vanilla Bourbon', 'Cashmeran, Benzoin, Woody Notes', 'A romantic feminine. Jasmine and bourbon vanilla.'),
('s122', 'Voce Viva', 'Valentino', 2020, 'Eau de Parfum', 'Bergamot, Italian Mandarin, Ginger', 'Gardenia, Orange Blossom', 'Crystal Moss, Sandalwood, Vanilla', 'The voice of a new generation. Bold floral.'),
('s123', 'Good Girl Supreme', 'Carolina Herrera', 2020, 'Eau de Parfum', 'Egyptian Jasmine, Berries, Raspberry', 'Tuberose, Toffee', 'Tonka Bean, Vanilla, Sandalwood', 'A berry-kissed Good Girl. Sweet and rebellious.'),
('s124', 'Very Good Girl', 'Carolina Herrera', 2021, 'Eau de Parfum', 'Lychee, Red Currant', 'Rose, Vetiver', 'Vanilla, Tonka Bean, Benzoin', 'Very good indeed. Fruity rose and vanilla.'),
('s125', 'CH Men Prive', 'Carolina Herrera', 2015, 'Eau de Toilette', 'Grapefruit, Pomelo', 'Benzoin, Leather, Cardamom', 'Sandalwood, Tonka Bean, Woody Notes, Suede', 'Private and exclusive. Smoky leather gourmand.');

-- BATCH 7: Hugo Boss, Calvin Klein, Montblanc, Issey Miyake, Narciso Rodriguez (s126-s150)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s126', 'Boss Bottled', 'Hugo Boss', 1998, 'Eau de Toilette', 'Apple, Plum, Lemon, Bergamot, Oakmoss', 'Geranium, Cinnamon, Clove, Carnation', 'Sandalwood, Vetiver, Cedar, Olive Tree, Vanilla', 'Classic business masculine. Apple and cinnamon warmth.'),
('s127', 'Boss Bottled Parfum', 'Hugo Boss', 2022, 'Parfum', 'Mango, Apple', 'Cardamom, Cinnamon', 'Maninka, Sandalwood, Vetiver, Musk', 'The most intense Boss Bottled. Fruity and spicy.'),
('s128', 'Hugo Man', 'Hugo Boss', 1995, 'Eau de Toilette', 'Green Apple, Lavender, Mint', 'Sage, Jasmine, Geranium, Pine', 'Sandalwood, Cedar, Musk, Fir Balsam', 'An invigorating green fougere.'),
('s129', 'Boss The Scent', 'Hugo Boss', 2015, 'Eau de Toilette', 'Ginger, Mandarin, Bergamot', 'Maninka Fruit, Lavender', 'Leather, Vanilla', 'Seductive and magnetic. Ginger and leather.'),
('s130', 'CK One', 'Calvin Klein', 1994, 'Eau de Toilette', 'Pineapple, Mandarin, Papaya, Bergamot, Cardamom, Lemon', 'Jasmine, Violet, Rose, Nutmeg, Lily of the Valley', 'Musk, Amber, Sandalwood, Cedar, Oakmoss', 'The original shared fragrance. Clean and universal.'),
('s131', 'Eternity for Men', 'Calvin Klein', 1989, 'Eau de Toilette', 'Lavender, Mandarin, Green Notes', 'Jasmine, Sage, Basil, Geranium, Rose', 'Sandalwood, Vetiver, Amber, Rosewood', 'A timeless fresh aromatic masculine.'),
('s132', 'Euphoria', 'Calvin Klein', 2005, 'Eau de Parfum', 'Pomegranate, Persimmon, Green Notes', 'Orchid, Lotus Blossom, Champaca', 'Mahogany, Amber, Musk, Cream Accord, Violet', 'An exotic and mysterious oriental.'),
('s133', 'Obsession for Men', 'Calvin Klein', 1986, 'Eau de Toilette', 'Mandarin, Bergamot, Lime, Lavender, Grapefruit', 'Coriander, Red Carnation, Cinnamon, Nutmeg, Pine', 'Sandalwood, Amber, Vanilla, Patchouli, Vetiver, Musk', 'The original obsession. Bold amber and spice.'),
('s134', 'CK Be', 'Calvin Klein', 1996, 'Eau de Toilette', 'Bergamot, Mandarin, Juniper Berry, Mint', 'Magnolia, Peach, Sandalwood', 'Musk, Patchouli, Amber, Opoponax, Tonka Bean', 'A unisex statement. Clean minimalism.'),
('s135', 'Explorer', 'Montblanc', 2019, 'Eau de Parfum', 'Bergamot, Pink Pepper, Clary Sage', 'Leather, Vetiver, Geranium', 'Patchouli, Indonesian Vetiver, Cacao, Ambroxan', 'An explorer spirit. Woody leather adventure.'),
('s136', 'Legend', 'Montblanc', 2011, 'Eau de Toilette', 'Bergamot, Lavender, Pineapple', 'Geranium, Coumarin, Rose, Apple', 'Sandalwood, Tonka Bean, Oakmoss, Evernyl', 'A legendary aromatic fougere. Reliable everyday.'),
('s137', 'Explorer Ultra Blue', 'Montblanc', 2021, 'Eau de Parfum', 'Bergamot, Grapefruit, Lemon', 'Patchouli, Amber', 'Vetiver, Woody Notes, Leather', 'A deeper marine explorer. Fresh and invigorating.'),
('s138', 'L''Eau d''Issey Pour Homme', 'Issey Miyake', 1994, 'Eau de Toilette', 'Yuzu, Bergamot, Lemon, Tarragon', 'Sage, Nutmeg, Blue Water Lily, Geranium', 'Vetiver, Sandalwood, Musk, Amber, Cedar', 'The original Japanese water column. Zen-like freshness.'),
('s139', 'L''Eau d''Issey', 'Issey Miyake', 1992, 'Eau de Toilette', 'Lotus, Freesia, Cyclamen, Rose Water, Calone', 'Peony, Carnation, Lily, Lily of the Valley', 'Cedar, Musk, Amber, Sandalwood, Osmanthus', 'Iconic aquatic floral. Purity of water.'),
('s140', 'Nuit d''Issey', 'Issey Miyake', 2014, 'Eau de Toilette', 'Bergamot, Grapefruit, Pink Pepper', 'Leather, Incense', 'Patchouli, Vetiver, Tonka Bean, Gaiac Wood, Black Pepper', 'A dark nocturnal leather. Mysterious and bold.'),
('s141', 'Fusion d''Issey', 'Issey Miyake', 2020, 'Eau de Toilette', 'Lemon, Bergamot, Grapefruit', 'Coconut Water, Lavender', 'Sandalwood, Cashmeran, Musk', 'A solar-aquatic fusion. Light and energetic.'),
('s142', 'For Her', 'Narciso Rodriguez', 2003, 'Eau de Toilette', 'Rose, Peach, Bergamot', 'Musk, Amber, Orange Blossom, Jasmine', 'Patchouli, Sandalwood, Vetiver, Vanilla', 'A musky masterpiece. Skin-like and intimate.'),
('s143', 'For Her Musc Noir', 'Narciso Rodriguez', 2021, 'Eau de Parfum', 'Pink Pepper, Plum', 'Rose, Musk', 'Cedarwood, Cashmeran, Patchouli', 'Dark musc seduction. Mysterious femininity.'),
('s144', 'Bleu Noir', 'Narciso Rodriguez', 2018, 'Eau de Parfum', 'Cardamom, Nutmeg, Blue Lavender', 'Musk, Ebony, Iris', 'Cedar, Vetiver, Amber', 'A midnight blue masculine. Musky and deep.'),
('s145', 'Pure Musc', 'Narciso Rodriguez', 2019, 'Eau de Parfum', 'Bergamot, Pink Pepper, Orange Blossom', 'Rose, Jasmine, Musk', 'Cashmeran, Patchouli, Ambrette', 'Distilled musc purity. Soft and enveloping.'),
('s146', 'For Him', 'Narciso Rodriguez', 2007, 'Eau de Parfum', 'Lavender, Musk', 'Musk, Violet Leaf, Amber', 'Vetiver, Patchouli, Sandalwood, Cedar', 'A masculine musc signature. Subtle and refined.'),
('s147', 'Bad Boy', 'Carolina Herrera', 2019, 'Eau de Toilette', 'Green Pepper, Bergamot, White Pepper', 'Sage, Cedarwood', 'Tonka Bean, Cacao, Amber', 'A duality of good and bad. Dark yet fresh.'),
('s148', '212 Men', 'Carolina Herrera', 1999, 'Eau de Toilette', 'Grapefruit, Lavender, Petit Grain, Spices', 'Gardenia, Ginger, Sage, Green Pepper', 'Sandalwood, Musk, Guaiac Wood, Labdanum, Incense', 'A New York night out. Urban and magnetic.'),
('s149', '212 VIP', 'Carolina Herrera', 2010, 'Eau de Parfum', 'Passion Fruit, Rum, Gardenia', 'Musk, Tonka Bean, King''s Mantle', 'Vanilla, Benzoin, Labdanum', 'Nightlife glamour in a bottle.'),
('s150', 'CH', 'Carolina Herrera', 2007, 'Eau de Toilette', 'Bergamot, Grapefruit, Lemon, Orange', 'Rose, Jasmine, Tuberose', 'Sandalwood, Suede, Musk, Praline, Civet', 'Classic casual elegance. Leathery floral.');

-- BATCH 8: Parfums de Marly, MFK, Nishane, Initio, Xerjoff (s151-s195)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s151', 'Layton Exclusif', 'Parfums de Marly', 2016, 'Eau de Parfum', 'Apple, Mandarin, Bergamot, Lavender', 'Geranium, Violet, Jasmine', 'Vanilla, Guaiac Wood, Patchouli, Sandalwood, Cardamom', 'A richer Layton with added depth and warmth.'),
('s152', 'Percival', 'Parfums de Marly', 2018, 'Eau de Parfum', 'Bergamot, Mandarin, Lavender, Pink Pepper', 'Geranium, Sage, Jasmine', 'Musk, Amber, Cashmeran, Woody Notes', 'A fresh aromatic knight. Lavender and musk.'),
('s153', 'Carlisle', 'Parfums de Marly', 2015, 'Eau de Parfum', 'Thyme, Nutmeg, Green Apple, Lavender', 'Rose, Patchouli, Osmanthus, Agarwood', 'Vanilla, Tonka Bean, Musk, Amber', 'A sophisticated oud rose. Warm and regal.'),
('s154', 'Godolphin', 'Parfums de Marly', 2017, 'Eau de Parfum', 'Plum, Rose, Cinnamon, Pepper', 'Saffron, Iris, Jasmine, Leather', 'Oud, Amber, Vanilla, Tonka Bean', 'Noble leather and plum. Deep and rugged.'),
('s155', 'Sedley', 'Parfums de Marly', 2019, 'Eau de Parfum', 'Bergamot, Grapefruit, Spearmint, Lavender', 'Violet Leaf, Geranium', 'Sandalwood, Musk, Cedar', 'A crisp minty fresh scent. Clean and modern.'),
('s156', 'Pegasus', 'Parfums de Marly', 2011, 'Eau de Parfum', 'Bergamot, Heliotrope', 'Almond, Jasmine, Vanilla', 'Sandalwood, Amber, Vanilla', 'Sweet almond and vanilla. Mythical elegance.'),
('s157', 'Delina Exclusif', 'Parfums de Marly', 2018, 'Parfum', 'Litchi, Pear, Grapefruit, Bergamot', 'Turkish Rose, Peony, Incense', 'Vanilla, Musk, Evernyl, Cashmeran, Vetiver', 'An exclusive rose. Darker and richer Delina.'),
('s158', 'Oriana', 'Parfums de Marly', 2021, 'Eau de Parfum', 'Litchi, Raspberry, Blackcurrant', 'Jasmine, Orange Blossom, Chantilly Cream', 'Sandalwood, Vanilla, Musk, Marshmallow', 'A fruity cream dream. Playful and feminine.'),
('s159', 'Kalan', 'Parfums de Marly', 2019, 'Eau de Parfum', 'Orange, Bergamot, Grapefruit', 'Ginger, Cinnamon, Pink Pepper', 'Sandalwood, Vetiver, Benzoin, Musk', 'A warm spicy citrus. Fiery and bold.'),
('s160', 'Althair', 'Parfums de Marly', 2021, 'Eau de Parfum', 'Apple, Bergamot', 'Tonka Bean, Vanilla', 'Sandalwood, Musk', 'A cozy vanilla apple. Sweet and comforting.'),
('s161', 'Aqua Universalis', 'Maison Francis Kurkdjian', 2009, 'Eau de Toilette', 'Bergamot, Lemon, Orange, Petit Grain', 'Lily of the Valley, White Flowers, Hedione', 'Musk, Cedar', 'Universal freshness. A clean white fragrance.'),
('s162', 'Petit Matin', 'Maison Francis Kurkdjian', 2016, 'Eau de Parfum', 'Litchi, Lemon, Green Notes', 'Rose, Iris, Musk', 'Musk, White Amber', 'A small morning delight. Fresh and musky.'),
('s163', 'Amyris Homme', 'Maison Francis Kurkdjian', 2012, 'Eau de Toilette', 'Rosemary, Pink Pepper', 'Iris, Tonka Bean', 'Amyris, Cedar, Musk', 'Sophisticated woody iris. Business elegance.'),
('s164', 'A la Rose', 'Maison Francis Kurkdjian', 2014, 'Eau de Parfum', 'Lemon, Pink Pepper, Rose', 'Centifolia Rose, Damask Rose', 'Musk, Amber', 'Pure rose poetry. Elegant and multi-faceted.'),
('s165', 'Gentle Fluidity Gold', 'Maison Francis Kurkdjian', 2019, 'Eau de Parfum', 'Juniper Berry, Coriander, Nutmeg', 'Musk, Amber', 'Vanilla, Sandalwood, Amber', 'Warm and golden. A gentle vanilla musk.'),
('s166', 'Oud Satin Mood', 'Maison Francis Kurkdjian', 2015, 'Eau de Parfum', 'Violet', 'Bulgarian Rose, Oud', 'Benzoin, Vanilla', 'A silky oud-rose blend. Luxurious and smooth.'),
('s167', 'BR540 Extrait', 'Maison Francis Kurkdjian', 2017, 'Extrait de Parfum', 'Jasmine, Saffron', 'Amberwood, Ambergris, Cedar', 'Fir Resin, Cedar', 'The extrait version. Even more potent and crystalline.'),
('s168', 'Gentle Fluidity Silver', 'Maison Francis Kurkdjian', 2019, 'Eau de Parfum', 'Juniper Berry, Coriander, Nutmeg', 'Musk, Amber', 'Musks, Woody Notes', 'Cool and fresh. A silvery citrus musk.'),
('s169', 'Ani', 'Nishane', 2019, 'Extrait de Parfum', 'Bergamot, Mandarin, Pink Pepper', 'Cardamom, Iris, Rose, Jasmine', 'Vanilla, Tonka Bean, Benzoin, Patchouli', 'A warm vanilla oriental. Comforting and rich.'),
('s170', 'Fan Your Flames', 'Nishane', 2015, 'Extrait de Parfum', 'Clove, Cardamom, Black Pepper', 'Rose, Saffron, Labdanum', 'Sandalwood, Vanilla, Benzoin, Musk', 'Fiery and passionate. A spice-rose extrait.'),
('s171', 'Hundred Silent Ways', 'Nishane', 2017, 'Extrait de Parfum', 'Rose, Raspberry, Mandarin', 'Jasmine, Tuberose, Osmanthus', 'Vanilla, Musk, Sandalwood, Patchouli', 'A hundred ways to love. Floral gourmand.'),
('s172', 'Wulong Cha', 'Nishane', 2017, 'Extrait de Parfum', 'Bergamot, Elemi, Green Tea', 'Jasmine, Rose, Lily of the Valley', 'Musk, Amber, Vetiver, Cedar', 'Oolong tea in perfume form. Serene and refined.'),
('s173', 'Tempfluo', 'Nishane', 2020, 'Extrait de Parfum', 'Mandarin, Rose, Black Pepper', 'Iris, Jasmine, Rose', 'Ambrox, Benzoin, Musk, Vanilla', 'A flowing tempest. Sweet and spicy.'),
('s174', 'Side Effect', 'Initio', 2018, 'Eau de Parfum', 'Cinnamon, Rum', 'Tobacco, Vanilla, Benzoin', 'Musk, Cashmeran', 'A boozy tobacco vanilla. Addictive side effect.'),
('s175', 'Oud for Greatness', 'Initio', 2018, 'Eau de Parfum', 'Saffron, Nutmeg, Lavender', 'Oud, Patchouli', 'Musk, Amberwood', 'An oud for the extraordinary. Smoky and grand.'),
('s176', 'Rehab', 'Initio', 2020, 'Eau de Parfum', 'Lavender, Musk, Bergamot', 'Iris, Ambrette', 'Sandalwood, Cashmere Musk, Amber', 'A clean musk rehabilitation. Fresh and addictive.'),
('s177', 'Atomic Rose', 'Initio', 2018, 'Eau de Parfum', 'Rose, Saffron', 'Rose, Raspberry', 'Amberwood, Patchouli, Musk, Vanilla', 'An explosive rose. Atomic intensity.'),
('s178', 'Musk Therapy', 'Initio', 2015, 'Eau de Parfum', 'Tangerine, Bergamot', 'Rose, Jasmine, Musk', 'White Musk, Amber, Cedar', 'Therapeutic clean musk. Soothing and pure.'),
('s179', 'Absolute Aphrodisiac', 'Initio', 2015, 'Eau de Parfum', 'Saffron, Rum', 'Rose, Vanilla', 'Oud, Chocolate, Musk', 'An aphrodisiac blend. Rich and intoxicating.'),
('s180', 'Psychedelic Love', 'Initio', 2019, 'Eau de Parfum', 'Pink Pepper, Rose', 'Heliotrope, Vanilla', 'Musk, Ambrox, Cashmeran', 'A psychedelic love potion. Sweet and hypnotic.'),
('s181', 'Naxos', 'Xerjoff', 2015, 'Eau de Parfum', 'Lavender, Bergamot, Lemon', 'Cinnamon, Cashmeran, Honey', 'Vanilla, Tonka Bean, Tobacco', 'A Sicilian honey tobacco. Warm and golden.'),
('s182', 'Erba Pura', 'Xerjoff', 2019, 'Eau de Parfum', 'Orange, Mandarin, Bergamot, Sicilian Lemon', 'White Peach, Melon, Fruits', 'Madagascar Vanilla, White Musk, Amber', 'Pure herb-fruit elixir. Bright and sweet.'),
('s183', 'Mefisto', 'Xerjoff', 2009, 'Eau de Parfum', 'Grapefruit, Bergamot, Lemon, Violet Leaf', 'Rose, Jasmine, Geranium', 'Sandalwood, Cedar, Musk, Amber', 'Devilishly charming citrus-floral.'),
('s184', 'Alexandria II', 'Xerjoff', 2009, 'Eau de Parfum', 'Peach, Blackcurrant', 'Rose, Jasmine, Iris', 'Sandalwood, Vanilla, Musk, Benzoin', 'A sweet fruity floral. Luxurious and smooth.'),
('s185', 'Lira', 'Xerjoff', 2012, 'Eau de Parfum', 'Bergamot, Orange, Lavender', 'Cinnamon, Caramel, Vanilla', 'Tonka Bean, Benzoin, Musk', 'A caramel citrus gourmand. Italian sweetness.'),
('s186', 'Nio', 'Xerjoff', 2010, 'Eau de Parfum', 'Lemon, Bergamot, Pink Pepper', 'Jasmine, Geranium, Cedar', 'Musk, Amber, Vetiver', 'A crisp Italian citrus masculine.'),
('s187', 'Renaissance', 'Xerjoff', 2010, 'Eau de Parfum', 'Apple, Pink Pepper, Bergamot', 'Rose, Jasmine, Violet', 'Sandalwood, Vanilla, Musk, Amber', 'A Renaissance of beauty. Fruity and floral.'),
('s188', 'Starlight', 'Xerjoff', 2020, 'Eau de Parfum', 'Bergamot, Peach, Mandarin', 'Rose, Jasmine, Ylang-Ylang', 'Sandalwood, Musk, Vanilla, Benzoin', 'A starlit floral. Elegant and radiant.'),
('s189', 'Richwood', 'Xerjoff', 2008, 'Eau de Parfum', 'Bergamot, Pepper, Cardamom', 'Iris, Violet, Geranium', 'Oud, Sandalwood, Vetiver, Patchouli', 'Rich exotic woods. Deep and contemplative.'),
('s190', 'Halfeti', 'Penhaligon''s', 2015, 'Eau de Parfum', 'Bergamot, Grapefruit, Artemisia, Green Notes', 'Rose, Jasmine, Saffron, Cardamom', 'Oud, Leather, Sandalwood, Amber, Tonka Bean', 'A Turkish garden town in perfume. Dark rose and oud.'),
('s191', 'Sartorial', 'Penhaligon''s', 2010, 'Eau de Toilette', 'Bergamot, Metallic Notes, Violet Leaf', 'Beeswax, Leather, Cyclamen', 'Sandalwood, Musk, Oakmoss, Honeycomb', 'Savile Row tailoring in a bottle.'),
('s192', 'Endymion', 'Penhaligon''s', 2003, 'Cologne', 'Mandarin, Bergamot, Sage, Green Notes', 'Coffee, Jasmine, Lavender, Geranium', 'Musk, Sandalwood, Incense, Vanilla, Labdanum', 'A club gentleman cologne. Coffee and lavender.'),
('s193', 'Blenheim Bouquet', 'Penhaligon''s', 1902, 'Eau de Toilette', 'Lemon, Lavender, Lime', 'Pine, Black Pepper, Musk', 'Cedar, Musk', 'A heritage citrus aromatic. English refinement since 1902.'),
('s194', 'The Tragedy of Lord George', 'Penhaligon''s', 2016, 'Eau de Parfum', 'Lavender, Rum, Elemi', 'Orris, Davana', 'Tonka Bean, Benzoin, Olibanum', 'A noble portrait in fragrance. Rich and complex.'),
('s195', 'Empressa', 'Penhaligon''s', 2016, 'Eau de Parfum', 'Rose, Bergamot', 'Turkish Rose, Peach, Osmanthus', 'Musk, Amber, Patchouli', 'A royal empress in a bottle. Rose and peach.');

-- BATCH 9: Le Labo, Byredo, Diptyque, Jo Malone (s196-s235)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s196', 'Rose 31', 'Le Labo', 2006, 'Eau de Parfum', 'Cumin, Rose', 'Cistus, Gaiac Wood', 'Cedar, Vetiver, Musk, Amber, Oud', 'A masculine rose. Woody and spiced.'),
('s197', 'Bergamote 22', 'Le Labo', 2006, 'Eau de Parfum', 'Bergamot, Grapefruit, Petit Grain', 'Amber, Cedar, Vetiver', 'Musk', 'A bergamot celebration. Bright and transparent.'),
('s198', 'Iris 39', 'Le Labo', 2013, 'Eau de Parfum', 'Rose, Iris, Jasmine', 'Iris, Violet, Patchouli', 'Musk, Leather, Amber', 'A Florentine iris. Powdery and elegant.'),
('s199', 'The Noir 29', 'Le Labo', 2015, 'Eau de Parfum', 'Bergamot, Fig Leaf, Bay Leaf', 'Black Tea, Tobacco, Cedar', 'Vetiver, Musk, Gaiac Wood', 'A smoky black tea. Literary and warm.'),
('s200', 'Vanille 44', 'Le Labo', 2006, 'Eau de Parfum', 'Cassis, Mandarin', 'Vanilla, Jasmine, Benzoin', 'Gaiac Wood, Cedar, Sandalwood, Musk', 'Paris in vanilla. Smoky and sophisticated.'),
('s201', 'Gaiac 10', 'Le Labo', 2008, 'Eau de Parfum', 'Frankincense, Cashmeran', 'Gaiac Wood, Musk', 'Amber, Cedar, Oud', 'Tokyo smoky wood. Incense and gaiac.'),
('s202', 'Baie 19', 'Le Labo', 2019, 'Eau de Parfum', 'Bergamot, Green Notes', 'Juniper Berry, Lily of the Valley', 'Patchouli, Musks, Amber', 'A rain-drenched garden. Green and petrichor.'),
('s203', 'Vetiver 46', 'Le Labo', 2006, 'Eau de Parfum', 'Pink Pepper, Grapefruit', 'Violet, Vetiver', 'Olibanum, Amber, Cedar, Musk', 'Pure vetiver virtue. Green and smoky.'),
('s204', 'Lys 41', 'Le Labo', 2006, 'Eau de Parfum', 'Lily, Tuberose', 'Lily of the Valley, Jasmine', 'Musk, Vanilla, Amber', 'A white floral bouquet. Pure and intoxicating.'),
('s205', 'Mojave Ghost', 'Byredo', 2014, 'Eau de Parfum', 'Ambrette, Sapodilla', 'Violet, Sandalwood, Magnolia', 'Choya, Cedar, Musk, Crisp Amber', 'A ghostly desert bloom. Woody and musky.'),
('s206', 'Black Saffron', 'Byredo', 2012, 'Eau de Parfum', 'Saffron, Juniper Berry', 'Black Violet, Leather, Raspberry', 'Cashmeran, Vetiver, Blonde Wood', 'A dark saffron leather. Oriental and luxurious.'),
('s207', 'Super Cedar', 'Byredo', 2016, 'Eau de Parfum', 'Rose, Virginian Cedar, Haitian Vetiver', 'Cedar, Musk', 'Amber', 'A super-charged cedarwood. Minimalist and modern.'),
('s208', 'Bibliotheque', 'Byredo', 2017, 'Eau de Parfum', 'Peach, Plum, Aldehydes', 'Violet, Orris, Patchouli, Peony', 'Leather, Vanilla, Papyrus', 'An old library. Leather-bound pages and peach.'),
('s209', 'Blanche', 'Byredo', 2009, 'Eau de Parfum', 'Aldehyde, Pink Pepper', 'Violet, Neroli, Peony, Rose', 'Sandalwood, Musk, Blonde Wood', 'Pure white linen. Clean and ethereal.'),
('s210', 'Rose of No Man''s Land', 'Byredo', 2015, 'Eau de Parfum', 'Pink Pepper, Turkish Rose Petals', 'Turkish Rose, Raspberry Blossom', 'Papyrus, White Amber', 'A tribute to nurses. Rose and pink pepper.'),
('s211', 'Sundazed', 'Byredo', 2019, 'Eau de Parfum', 'Mandarin, Lemon, Neroli', 'Jasmine, Orange Blossom', 'Blond Woods, Musk, Cotton Candy', 'Summer daze. Carefree citrus and cotton candy.'),
('s212', 'Slow Dance', 'Byredo', 2019, 'Eau de Parfum', 'Opoponax, Geranium', 'Violet, Labdanum', 'Vanilla, Patchouli, Elemi', 'A slow swaying dance. Resinous and warm.'),
('s213', 'Mixed Emotions', 'Byredo', 2021, 'Eau de Parfum', 'Cassis, Mate', 'Violet Leaf, Iris', 'Birch, Musk', 'Emotional complexity in a bottle. Green and earthy.'),
('s214', 'Philosykos', 'Diptyque', 2001, 'Eau de Toilette', 'Fig Leaf, Green Notes', 'Fig, Coconut', 'Cedar, Woody Notes, Musk', 'A fig tree in summer. Green and milky.'),
('s215', 'Tam Dao', 'Diptyque', 2003, 'Eau de Parfum', 'Rosewood, Myrtle, Cypress, Italian Cypress', 'Rose, Sandalwood, Amyris', 'Sandalwood, Cedar, Musk, Amber', 'Laotian sandalwood. Creamy and meditative.'),
('s216', 'Do Son', 'Diptyque', 2005, 'Eau de Toilette', 'Orange Blossom, Tuberose, Pink Pepper', 'Tuberose, Jasmine, Iris, Rose', 'Musk, Benzoin', 'A Vietnamese tuberose. Heady and floral.'),
('s217', 'Eau Duelle', 'Diptyque', 2010, 'Eau de Parfum', 'Pink Pepper, Elemi', 'Saffron, Juniper Berry', 'Vanilla, Vetiver, Benzoin, Frankincense', 'A spicy vanilla duality. Dry and refined.'),
('s218', 'Fleur de Peau', 'Diptyque', 2019, 'Eau de Parfum', 'Pink Pepper, Aldehydes', 'Iris Absolute, Musk', 'Ambrette, Musks', 'Skin-like musk. Intimate and delicate.'),
('s219', 'Oud Palao', 'Diptyque', 2015, 'Eau de Parfum', 'Bergamot, Saffron', 'Rose, Oud', 'Patchouli, Musk, Amber', 'A palace of oud and rose. Opulent.'),
('s220', 'Wood Sage & Sea Salt', 'Jo Malone', 2014, 'Cologne', 'Ambrette, Sea Salt', 'Sea Sage', 'Driftwood, Grapefruit', 'Windswept coastal walk. Earthy and salty.'),
('s221', 'English Pear & Freesia', 'Jo Malone', 2010, 'Cologne', 'Pear, Melon', 'Freesia, Rose', 'Patchouli, Amber, Rhubarb', 'An autumnal English pear. Sweet and crisp.'),
('s222', 'Peony & Blush Suede', 'Jo Malone', 2013, 'Cologne', 'Red Apple, Peony', 'Peony, Rose, Carnation, Jasmine, Lily, Gillyflower', 'Suede', 'A blush-toned peony. Feminine and soft.'),
('s223', 'Lime Basil & Mandarin', 'Jo Malone', 1999, 'Cologne', 'Mandarin, Basil, Bergamot', 'Lime, Lilac, Iris', 'Vetiver, Patchouli', 'The original Jo Malone. Citrus and basil herbaceous.'),
('s224', 'Pomegranate Noir', 'Jo Malone', 2005, 'Cologne', 'Pomegranate, Raspberry, Plum', 'Casablanca Lily, Pink Pepper, Clove', 'Guaiac Wood, Patchouli, Frankincense', 'A bold fruity spice. Exotic and rich.'),
('s225', 'Velvet Rose & Oud', 'Jo Malone', 2012, 'Cologne Intense', 'Clove', 'Damask Rose', 'Oud, Praline, Musks', 'Opulent oud meets damask rose. Rich and dark.'),
('s226', 'Myrrh & Tonka', 'Jo Malone', 2017, 'Cologne Intense', 'Lavender, Namibian Myrrh', 'Almond, Omumbiri Myrrh, Tonka Bean', 'Vanilla, Dried Fruits, Lentisk', 'A warm myrrh-tonka embrace. Creamy and addictive.'),
('s227', 'Oud & Bergamot', 'Jo Malone', 2010, 'Cologne Intense', 'Bergamot', 'Orange Flower, Oud', 'Amber, Cedarwood', 'Bright bergamot meets smoky oud.'),
('s228', 'Wild Bluebell', 'Jo Malone', 2011, 'Cologne', 'Bluebell, Clove', 'Lily of the Valley, Persimmon, Jasmine', 'White Amber, Musk', 'A dewy woodland in spring. Delicate and blue.'),
('s229', 'Blackberry & Bay', 'Jo Malone', 2012, 'Cologne', 'Blackberry, Grapefruit, Pink Pepper', 'Bay Leaf, Plum, Rose Hip', 'Cedar, Vetiver, Musk', 'Hedgerow blackberries. Tart and autumnal.'),
('s230', 'Scarlet Poppy', 'Jo Malone', 2020, 'Cologne Intense', 'Iris, Barley, Tonka Bean', 'Poppy, Rose', 'Smoked Agarwood', 'A poppy field in fragrance. Red and smoky.');

-- BATCH 10: Amouage, Roja, Kilian, Acqua di Parma (s231-s265)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s231', 'Reflection Man', 'Amouage', 2007, 'Eau de Parfum', 'Rosemary, Pink Pepper, Petit Grain, Neroli', 'Jasmine, Orris, Ylang-Ylang, Rose', 'Sandalwood, Vetiver, Cedar, Musk', 'A mirror of sophistication. Jasmine for men.'),
('s232', 'Jubilation XXV', 'Amouage', 2007, 'Eau de Parfum', 'Orange, Tarragon, Labdanum, Olibanum', 'Rose, Orchid, Guaiac Wood, Cinnamon', 'Oud, Myrrh, Musk, Cedar', 'A grand celebration. Rich and majestic.'),
('s233', 'Lyric Man', 'Amouage', 2008, 'Eau de Parfum', 'Lime, Angelica, Cyclamen', 'Rose, Jasmine, Geranium', 'Sandalwood, Musk, Vanilla, Benzoin', 'A lyrical rose composition. Poetic and refined.'),
('s234', 'Epic Man', 'Amouage', 2009, 'Eau de Parfum', 'Cardamom, Cumin, Pink Pepper, Nutmeg', 'Rose, Geranium, Orris', 'Oud, Leather, Sandalwood, Musk, Frankincense', 'An epic adventure in a bottle. Smoky and spiced.'),
('s235', 'Dia Man', 'Amouage', 2002, 'Eau de Parfum', 'Bergamot, Mandarin', 'Rose, Jasmine, Peony, Lily of the Valley', 'Sandalwood, Musk, Amber, Cedar', 'A bright floral day. Classic and transparent.'),
('s236', 'Gold Man', 'Amouage', 1983, 'Eau de Parfum', 'Aldehydes, Bergamot, Rose', 'Jasmine, Lily of the Valley, Myrrh, Orris', 'Frankincense, Sandalwood, Civet, Musk, Cedar', 'The original Amouage. Arabian gold and incense.'),
('s237', 'Honour Woman', 'Amouage', 2011, 'Eau de Parfum', 'Pepper, Rhubarb', 'Tuberose, Gardenia, Jasmine, Lily of the Valley', 'Sandalwood, Amber, Musk, Vanilla', 'An honourable white floral. Elegant and powerful.'),
('s238', 'Beach Hut Man', 'Amouage', 2017, 'Eau de Parfum', 'Lemon, Bergamot, Artemisia, Oregano', 'Orange Blossom, Geranium', 'Cedar, Vetiver, Amber, Cashmeran', 'A Mediterranean beach hut. Herbal and citrus.'),
('s239', 'Enclave', 'Amouage', 2022, 'Eau de Parfum', 'Ginger, Cardamom, Saffron, Bergamot', 'Jasmine, Rose, Orris', 'Oud, Amber, Musk, Patchouli, Sandalwood', 'A new territory. Bold and precious.'),
('s240', 'Sunshine Man', 'Amouage', 2014, 'Eau de Parfum', 'Mandarin, Lavender, Bergamot', 'Heliotrope, Osmanthus, Cloves', 'Rum, Vanilla, Tonka Bean, Benzoin', 'Liquid sunshine. Rum and lavender warmth.'),
('s241', 'Elysium', 'Roja Parfums', 2017, 'Parfum Cologne', 'Bergamot, Grapefruit, Lemon, Lime, Pink Pepper', 'Jasmine, Rose, Lily of the Valley, Geranium', 'Vetiver, Cedar, Musk, Amber, Juniper', 'The Elysian fields in a bottle. Uplifting and fresh.'),
('s242', 'Enigma', 'Roja Parfums', 2014, 'Parfum', 'Bergamot, Lemon, Grapefruit', 'Jasmine, Rose, Iris, Lily of the Valley', 'Oud, Sandalwood, Vanilla, Amber, Musk, Cedar', 'An enigmatic creation. Deep and complex.'),
('s243', 'Scandal Pour Homme', 'Roja Parfums', 2016, 'Parfum', 'Bergamot, Pineapple, Mandarin', 'Rose, Jasmine, Lavender', 'Sandalwood, Vanilla, Amber, Oud, Musk', 'A scandalous niche masculine. Opulent.'),
('s244', 'Amber Aoud', 'Roja Parfums', 2012, 'Parfum', 'Bergamot, Lemon', 'Jasmine, Saffron, Rose', 'Oud, Amber, Sandalwood, Musk', 'Amber meets aoud. Rich and precious.'),
('s245', 'Angels'' Share', 'Kilian', 2020, 'Eau de Parfum', 'Cognac, Cinnamon, Nutmeg', 'Oak, Praline', 'Tonka Bean, Sandalwood, Vanilla', 'Aged cognac in the cellar. Warm boozy gourmand.'),
('s246', 'Good Girl Gone Bad', 'Kilian', 2012, 'Eau de Parfum', 'Jasmine Sambac, May Rose, Narcissus', 'Tuberose, Osmanthus', 'Cedar, Amber, Musk, Vetiver', 'A floral gone rogue. Lush white flowers and cedar.'),
('s247', 'Love Don''t Be Shy', 'Kilian', 2007, 'Eau de Parfum', 'Neroli, Pink Pepper, Coriander, Bergamot', 'Rose, Jasmine, Iris', 'Sugar, Caramel, Vanilla, Musk, Ambrette, Civet', 'Fearless love. Sweet marshmallow and orange blossom.'),
('s248', 'Straight to Heaven', 'Kilian', 2007, 'Eau de Parfum', 'Rum, Anise', 'Cedar, Iris, Davana', 'Patchouli, Musk, Vetiver', 'Straight to heaven indeed. Rum and cedar drydown.'),
('s249', 'Rolling in Love', 'Kilian', 2019, 'Eau de Parfum', 'Almond, Turkish Rose, Pink Pepper', 'Rose, Jasmine, Iris', 'Musk, Ambroxan, Cashmeran', 'Rolling in almond and rose. Romantic and soft.'),
('s250', 'Black Phantom', 'Kilian', 2017, 'Eau de Parfum', 'Rum, Dark Chocolate', 'Coffee, Caramel', 'Sandalwood, Vetiver, Sugar Cane', 'A dark phantom. Rum-coffee-chocolate trio.'),
('s251', 'Apple Brandy on the Rocks', 'Kilian', 2021, 'Eau de Parfum', 'Apple, Cognac', 'Tuberose, Jasmine, Iris', 'Cedar, Sandalwood, Amberwood', 'Apple brandy served cold. Boozy and fresh.'),
('s252', 'Colonia', 'Acqua di Parma', 1916, 'Eau de Cologne', 'Lemon, Orange, Bergamot, Lavender, Rosemary', 'Rose, Verbena, Jasmine', 'Vetiver, Patchouli, Sandalwood, Musk', 'The original Italian cologne. Timeless citrus elegance.'),
('s253', 'Colonia Essenza', 'Acqua di Parma', 2010, 'Eau de Cologne', 'Lemon, Bergamot, Mandarin, Petit Grain, Rosemary', 'Rose, Jasmine, Clove', 'Musk, Patchouli, Vetiver, Amber, White Cedar', 'A richer Colonia. More woody and lasting.'),
('s254', 'Fico di Amalfi', 'Acqua di Parma', 2006, 'Eau de Toilette', 'Bergamot, Lemon, Grapefruit, Citron', 'Fig Nectar, Pink Pepper, Jasmine, Fig Leaf', 'Cedar, Benzoin, Woody Notes', 'Amalfi figs in the sun. Mediterranean delight.'),
('s255', 'Quercia', 'Acqua di Parma', 2019, 'Eau de Parfum', 'Cardamom, Pink Pepper, Grapefruit', 'Vetiver, Musks', 'Cashmeran, Guaiac Wood, Virginia Cedar', 'An ancient Italian oak tree. Green and earthy.');

-- BATCH 11: Serge Lutens, Frederic Malle, Montale, Mancera, Memo Paris (s256-s295)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s256', 'La Fille de Berlin', 'Serge Lutens', 2013, 'Eau de Parfum', 'Rose, Raspberry, Pink Pepper', 'Rose, Geranium', 'Frankincense, Amber, Musk, Tolu Balsam', 'A red-lipstick rose. Tart and defiant.'),
('s257', 'Ambre Sultan', 'Serge Lutens', 2000, 'Eau de Parfum', 'Bay Leaf, Myrtle, Coriander, Oregano', 'Angelica, Amber', 'Sandalwood, Patchouli, Benzoin, Vanilla, Amber', 'A resinous amber legend. Herbal and warm.'),
('s258', 'Chergui', 'Serge Lutens', 2005, 'Eau de Parfum', 'Honey, Tobacco Leaf', 'Iris, Rose, Incense', 'Sandalwood, Musk, Benzoin, Amber, Vanilla', 'Saharan warmth. Honeyed tobacco and iris.'),
('s259', 'Nuit de Cellophane', 'Serge Lutens', 2006, 'Eau de Parfum', 'Osmanthus, Bergamot, Green Notes', 'White Musk, Almond, Jasmine', 'Sandalwood, Musk, Vanilla', 'Transparent night. Osmanthus and white musk.'),
('s260', 'L''Orpheline', 'Serge Lutens', 2014, 'Eau de Parfum', 'Beeswax, Incense', 'Iris, Orris', 'Musk, Amber, Cedar', 'An orphan scent. Waxy iris and incense.'),
('s261', 'Portrait of a Lady', 'Frederic Malle', 2010, 'Eau de Parfum', 'Rose, Raspberry, Blackcurrant, Clove', 'Turkish Rose, Patchouli, Cinnamon, Benzoin', 'Sandalwood, Incense, Musk, Amber', 'A masterpiece by Dominique Ropion. Opulent dark rose.'),
('s262', 'Musc Ravageur', 'Frederic Malle', 2000, 'Eau de Parfum', 'Lavender, Bergamot', 'Musk, Amber', 'Vanilla, Sandalwood, Cedar, Gaiac Wood', 'A devastatingly musky amber. Sensual and carnal.'),
('s263', 'Carnal Flower', 'Frederic Malle', 2005, 'Eau de Parfum', 'Melon, Eucalyptus, Bergamot', 'Tuberose, Jasmine, Orange Blossom, Ylang-Ylang', 'Musk, Coconut', 'The greatest tuberose fragrance. Green and indolic.'),
('s264', 'En Passant', 'Frederic Malle', 2000, 'Eau de Parfum', 'Lilac, Cucumber, Wheat', 'Lilac, White Musk', 'Cedar', 'A walk in a lilac garden after rain. Fleeting beauty.'),
('s265', 'The Night', 'Frederic Malle', 2013, 'Eau de Parfum', 'Rose, Cumin, Clove', 'Oud, Saffron, Cinnamon, Rose', 'Incense, Musk, Amber', 'A Middle Eastern night. Oud and rose intertwined.'),
('s266', 'Lipstick Rose', 'Frederic Malle', 2000, 'Eau de Parfum', 'Grapefruit, Violet, Rose', 'Rose, Iris, Vetiver', 'Musk, Vanilla, Amber, White Musk', 'The smell of lipstick. Powdery rose nostalgia.'),
('s267', 'Intense Cafe', 'Montale', 2013, 'Eau de Parfum', 'Coffee', 'Rose, Amber', 'Vanilla, White Musk', 'A Turkish coffee and rose pairing. Sweet and addictive.'),
('s268', 'Black Aoud', 'Montale', 2006, 'Eau de Parfum', 'Rose, Oud', 'Oud, Rose, Patchouli', 'Musk, Amber, Sandalwood', 'A pure oud and rose duet. Dark and potent.'),
('s269', 'Chocolate Greedy', 'Montale', 2007, 'Eau de Parfum', 'Orange, Mandarin', 'Chocolate, Coffee, Tonka Bean', 'Vanilla, Cocoa, Dried Fruits', 'Chocolate addiction in a bottle. Gourmand heaven.'),
('s270', 'Arabians Tonka', 'Montale', 2016, 'Eau de Parfum', 'Lavender, Bergamot', 'Tonka Bean, Amber', 'Vanilla, Oud, Musk, Benzoin', 'Arabian tonka warmth. Creamy and exotic.'),
('s271', 'Roses Musk', 'Montale', 2009, 'Eau de Parfum', 'Rose', 'Rose, Musk, Jasmine', 'White Musk, Amber', 'Rose draped in white musk. Soft and luminous.'),
('s272', 'Honey Aoud', 'Montale', 2011, 'Eau de Parfum', 'Honey, Rose, Saffron', 'Oud, Patchouli', 'Vanilla, Amber, Sandalwood', 'Sweet honey meets smoky oud. Unusual and lovely.'),
('s273', 'Cedrat Boise', 'Mancera', 2012, 'Eau de Parfum', 'Citron, Bergamot, Sicilian Lemon, Black Pepper', 'Jasmine, Patchouli, Guaiac Wood, Juniper', 'Sandalwood, Oakmoss, Leather, Vanilla, White Musk', 'A vigorous citrus woody. Bright and long-lasting.'),
('s274', 'Red Tobacco', 'Mancera', 2017, 'Eau de Parfum', 'Saffron, Cinnamon, Nutmeg', 'Tobacco, Jasmine, Patchouli', 'Vanilla, Oud, Sandalwood, Amber, Woody Notes', 'A spicy tobacco feast. Rich and smoky.'),
('s275', 'Instant Crush', 'Mancera', 2019, 'Eau de Parfum', 'Bergamot, Grapefruit, Black Pepper', 'Rose, Jasmine, Iris', 'Sandalwood, Musk, Vanilla, Patchouli, Amber', 'Instant infatuation. Sweet and rosy.'),
('s276', 'Roses Vanille', 'Mancera', 2011, 'Eau de Parfum', 'Rose, Lemon, Bergamot', 'Rose, Plum, Jasmine', 'Vanilla, White Musk, Amber, Cedar', 'Rose and vanilla romance. Sweet and feminine.'),
('s277', 'Aoud Blue Notes', 'Mancera', 2014, 'Eau de Parfum', 'Bergamot, Lavender', 'Oud, Jasmine, Pepper', 'Vetiver, Musk, Amber, Cedar', 'Oud with a fresh blue twist. Modern and clean.'),
('s278', 'Intense Oud', 'Mancera', 2012, 'Eau de Parfum', 'Saffron, Rose', 'Oud, Patchouli, Amber', 'Musk, Sandalwood, Cedar, Vanilla', 'An intense oud-rose accord. Dark and resinous.'),
('s279', 'African Leather', 'Memo Paris', 2013, 'Eau de Parfum', 'Cardamom, Bergamot, Geranium', 'Oud, Saffron, Leather, Cumin', 'Vetiver, Musk, Birch Tar, Castoreum', 'The scent of African leather. Raw and exotic.'),
('s280', 'Winter Palace', 'Memo Paris', 2015, 'Eau de Parfum', 'Bergamot, Mandarin', 'Jasmine, Rose, Orange Blossom', 'Amber, Vanilla, Tonka Bean, Sandalwood', 'A warm Russian palace. Amber and florals.'),
('s281', 'French Leather', 'Memo Paris', 2014, 'Eau de Parfum', 'Aldehydes, Grapefruit', 'Leather, Iris, Rose', 'Sandalwood, Vetiver, Musk, Cedar', 'Refined French leather. Powdery and elegant.'),
('s282', 'Marfa', 'Memo Paris', 2014, 'Eau de Parfum', 'Mandarin, Bergamot', 'Cedar, Saffron, Leather', 'Amber, Musk, Sandalwood, Benzoin', 'The Texas desert town. Warm wood and saffron.'),
('s283', 'Sintra', 'Memo Paris', 2019, 'Eau de Parfum', 'Mandarin, Bergamot', 'Orange Blossom, Rose, Jasmine', 'Sandalwood, Musk, Amber', 'Portuguese garden escape. Sun-kissed florals.'),
('s284', 'Sicilian Leather', 'Memo Paris', 2016, 'Eau de Parfum', 'Bergamot, Lemon, Mandarin', 'Leather, Rose, Jasmine', 'Cedar, Musk, Amber, Tonka Bean', 'Mediterranean leather. Citrus-kissed and warm.'),
('s285', 'Inle', 'Memo Paris', 2007, 'Eau de Parfum', 'Lotus, Bergamot, Mandarin', 'Jasmine, Rose, Ylang-Ylang', 'Sandalwood, Musk, Cedar, Amber', 'A Burmese lake. Aquatic and serene.');

-- BATCH 12: Maison Margiela Replica, Atelier Cologne, Mugler, Marc Jacobs (s286-s325)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s286', 'Replica Jazz Club', 'Maison Margiela', 2013, 'Eau de Toilette', 'Pink Pepper, Lemon, Neroli', 'Rum, Clary Sage, Java Vetiver', 'Tobacco Leaf, Vanilla, Styrax, Tonka Bean', 'A smoky jazz bar. Rum, tobacco, and leather.'),
('s287', 'Replica Beach Walk', 'Maison Margiela', 2012, 'Eau de Toilette', 'Bergamot, Lemon, Pink Pepper', 'Ylang-Ylang, Coconut Milk, Heliotrope', 'Musk, Cedar, Benzoin', 'Warm sand and ocean breeze. Solar and salty.'),
('s288', 'Replica Lazy Sunday Morning', 'Maison Margiela', 2012, 'Eau de Toilette', 'Pear, Aldehydes, Lily of the Valley', 'Iris, Rose, White Musk', 'Ambroxan, White Cedar', 'Clean white sheets on a lazy Sunday. Crisp and musky.'),
('s289', 'Replica Coffee Break', 'Maison Margiela', 2018, 'Eau de Toilette', 'Coffee, Lavender', 'Milk Mousse', 'Vanilla, Tonka Bean, Cedar', 'A mid-morning coffee pause. Creamy and comforting.'),
('s290', 'Replica Bubble Bath', 'Maison Margiela', 2020, 'Eau de Toilette', 'Soap, Lavender, Rose Superessence', 'Coconut, Jasmine', 'Musk, White Cedar', 'The comfort of a warm bath. Clean and soapy.'),
('s291', 'Replica Whispers in the Library', 'Maison Margiela', 2019, 'Eau de Toilette', 'Pepper, Elemi', 'Benzoin, Cedarwood, Vanilla', 'Musk, Tonka Bean', 'Old book pages and wood shelves. Quiet and warm.'),
('s292', 'Replica Autumn Vibes', 'Maison Margiela', 2019, 'Eau de Toilette', 'Cardamom, Pink Pepper', 'Cedarwood, Styrax', 'Woody Notes, Musk, Elemi', 'Crunchy autumn leaves underfoot. Woody and spiced.'),
('s293', 'Replica Sailing Day', 'Maison Margiela', 2016, 'Eau de Toilette', 'Calone, Aquatic Notes, Juniper Berry', 'Red Seaweed, Red Cedar', 'Iris, Musk, Ambroxan', 'Open sea and wind. Fresh and invigorating.'),
('s294', 'Replica At the Barber''s', 'Maison Margiela', 2015, 'Eau de Toilette', 'Basil, Black Pepper, Pink Pepper', 'Lavender, Geranium', 'Tonka Bean, White Musk, Cedar', 'A classic barbershop shave. Clean and aromatic.'),
('s295', 'Replica Under the Lemon Trees', 'Maison Margiela', 2021, 'Eau de Toilette', 'Lemon, Bergamot, Green Notes', 'Green Tea, Mate', 'Cedar, Musk', 'A Sicilian lemon grove. Bright and green.'),
('s296', 'Clementine California', 'Atelier Cologne', 2017, 'Cologne Absolue', 'Clementine, Mandarin, Pink Pepper', 'Iris, Cypress, Vetiver', 'Juniper Berry, Sandalwood, Musk', 'California sunshine in a clementine. Zesty and bright.'),
('s297', 'Orange Sanguine', 'Atelier Cologne', 2011, 'Cologne Absolue', 'Blood Orange, Mandarin', 'Geranium, Jasmine', 'Sandalwood, Tonka Bean, Amber', 'A freshly squeezed blood orange. Juicy and vivid.'),
('s298', 'Vanille Insensee', 'Atelier Cologne', 2011, 'Cologne Absolue', 'Lime, Coriander, Bergamot', 'Jasmine, Oak, Vanilla', 'Vetiver, Musk, Amber, Ebony Wood', 'An unexpected dry vanilla with lime and oak.'),
('s299', 'Pacific Lime', 'Atelier Cologne', 2019, 'Cologne Absolue', 'Lime, Grapefruit, Starfruit', 'Coconut, Pepper, Geranium', 'Vetiver, Sandalwood, Musk', 'A Pacific island lime cocktail. Tropical and fresh.'),
('s300', 'Angel', 'Mugler', 1992, 'Eau de Parfum', 'Bergamot, Melon, Coconut, Mandarin, Cassia, Pineapple, Cotton Candy', 'Honey, Apricot, Blackberry, Plum, Jasmine, Orchid, Rose, Lily', 'Chocolate, Tonka Bean, Caramel, Vanilla, Patchouli, Musk', 'The original gourmand. Revolutionary patchouli-chocolate.'),
('s301', 'A*Men', 'Mugler', 1996, 'Eau de Toilette', 'Lavender, Mint, Peppermint', 'Coffee, Tar', 'Patchouli, Vanilla, Tonka Bean, Caramel', 'Angel for men. Coffee and patchouli darkness.'),
('s302', 'Angel Nova', 'Mugler', 2020, 'Eau de Parfum', 'Lychee, Raspberry', 'Damask Rose, Peony', 'Akigalawood, Benzoin, Vanilla', 'A new Angel star. Rose and lychee brightness.'),
('s303', 'Alien Goddess', 'Mugler', 2021, 'Eau de Parfum', 'Bergamot, Coconut', 'Jasmine Sambac', 'Cashmere Wood, Vanilla, Bourbon', 'A divine feminine. Coconut jasmine glow.'),
('s304', 'Aura', 'Mugler', 2017, 'Eau de Parfum', 'Green Notes, Rhubarb Leaf', 'Orange Blossom, Tiger Liana', 'Bourbon Vanilla, Wolfwood, Amber', 'A wild botanical aura. Green and animalic.'),
('s305', 'Daisy', 'Marc Jacobs', 2007, 'Eau de Toilette', 'Strawberry, Violet Leaves, Blood Grapefruit', 'Gardenia, Violet Petal, Jasmine', 'Musk, Vanilla, White Wood', 'A playful floral. Fresh and girlish.'),
('s306', 'Daisy Dream', 'Marc Jacobs', 2014, 'Eau de Toilette', 'Blackberry, Grapefruit, Pear', 'Jasmine, Wisteria, Blue Lychee', 'White Wood, Musk, Coconut Water', 'A dreamy blue daisy. Airy and fruity.'),
('s307', 'Decadence', 'Marc Jacobs', 2015, 'Eau de Parfum', 'Italian Plum, Iris, Saffron', 'Bulgarian Rose, Jasmine Sambac, Orris', 'Papyrus Wood, Vetiver, Amber, Liquid Gold', 'Decadent luxury. Plum and iris in a green bag.'),
('s308', 'Perfect', 'Marc Jacobs', 2020, 'Eau de Parfum', 'Rhubarb, Bright Daffodil', 'Almond Milk, Orange Blossom', 'Cedarwood, Cashmeran, Musk', 'Perfectly imperfect. Fresh floral musk.'),
('s309', 'Daisy Love', 'Marc Jacobs', 2018, 'Eau de Toilette', 'Cloudberry, Cashmere Musk, Daisy Tree Petals', 'Driftwood, Radiant Musks', 'Cashmere Musk, White Woods', 'Warm and radiant. A sunny daisy love.'),
('s310', 'Viktor & Rolf Bonbon', 'Viktor & Rolf', 2014, 'Eau de Parfum', 'Mandarin, Orange, Peach', 'Caramel, Orange Blossom, Jasmine', 'Sandalwood, Cedar, Guaiac Wood, Amber', 'A candied caramel bonbon. Gourmand delight.');

-- BATCH 13: Juliette Has A Gun, Escentric Molecules, Clean, Commodity, Lattafa, misc niche (s311-s355)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s311', 'Not a Perfume Superdose', 'Juliette Has A Gun', 2020, 'Eau de Parfum', 'Ambroxan', 'Ambroxan, Cetalox', 'Ambroxan, Musks', 'A superdose of Ambroxan. Skin-like warmth amplified.'),
('s312', 'Vanilla Vibes', 'Juliette Has A Gun', 2018, 'Eau de Parfum', 'Sea Salt, Orchid', 'Vanilla, Coconut', 'Sandalwood, Musk', 'Beach vanilla. Salty and creamy.'),
('s313', 'Lady Vengeance', 'Juliette Has A Gun', 2006, 'Eau de Parfum', 'Rose, Bergamot', 'Bulgarian Rose, Patchouli', 'Vanilla, Musk', 'A vengeful rose. Dark and seductive.'),
('s314', 'Moscow Mule', 'Juliette Has A Gun', 2017, 'Eau de Parfum', 'Ginger, Bergamot, Lime', 'Musk, Amber', 'Cedar, Musk, Amber', 'A cocktail fragrance. Spicy ginger-lime fizz.'),
('s315', 'Sunny Side Up', 'Juliette Has A Gun', 2019, 'Eau de Parfum', 'White Flowers, Jasmine', 'Jasmine, Iris, Heliotrope', 'Sandalwood, Musk', 'A bright floral optimism. Sunny and clean.'),
('s316', 'Escentric 01', 'Escentric Molecules', 2006, 'Eau de Toilette', 'Lime, Pink Pepper', 'Iso E Super, Iris, White Musk', 'Woody Notes, Musk', 'Iso E Super as the star. Warm and woody.'),
('s317', 'Molecule 02', 'Escentric Molecules', 2008, 'Eau de Toilette', 'Ambroxan', 'Ambroxan', 'Ambroxan', 'Pure Ambroxan. A warm amber skin scent.'),
('s318', 'Escentric 02', 'Escentric Molecules', 2008, 'Eau de Toilette', 'Ambroxan, Elemi, Hedione, Orris, Green Apple', 'Musk, Violet', 'Amber, Vetiver', 'Ambroxan amplified. Musky and transparent.'),
('s319', 'Molecule 03', 'Escentric Molecules', 2010, 'Eau de Toilette', 'Vetiveryl Acetate', 'Vetiveryl Acetate', 'Vetiveryl Acetate', 'Pure vetiver molecule. Woody and green.'),
('s320', 'Escentric 04', 'Escentric Molecules', 2017, 'Eau de Toilette', 'Grapefruit, Pink Pepper, Juniper Berry', 'Javanol, Musk, Orris', 'Woody Notes, Amber', 'Javanol at the center. Creamy sandalwood.'),
('s321', 'Clean Reserve Skin', 'Clean', 2016, 'Eau de Parfum', 'Pink Pepper, Fig Leaf', 'Violet, Jasmine, Musk', 'Sandalwood, Musk, Amber', 'Your skin but better. Clean and musky.'),
('s322', 'Clean Reserve Sueded Oud', 'Clean', 2016, 'Eau de Parfum', 'Bergamot, Cardamom', 'Rose, Oud, Leather', 'Sandalwood, Musk, Amber', 'A clean take on oud. Approachable and soft.'),
('s323', 'Clean Reserve Radiant Nectar', 'Clean', 2020, 'Eau de Parfum', 'Nectarine, Bergamot', 'Orange Blossom, Jasmine', 'Musk, Amber, Cedar', 'Sun-soaked nectar. Bright and sheer.'),
('s324', 'Commodity Gold', 'Commodity', 2014, 'Eau de Parfum', 'White Pepper, Mandarin', 'Tuberose, Jasmine, Orris', 'Amber, Vetiver, Sandalwood, Gold', 'A golden shimmer. Warm and luminous.'),
('s325', 'Commodity Book', 'Commodity', 2017, 'Eau de Parfum', 'Ginger, Elemi, Pink Pepper', 'Cedar, Muslin', 'Sandalwood, Amber, Musk, Suede', 'An old library. Cozy and intellectual.'),
('s326', 'Commodity Velvet', 'Commodity', 2019, 'Eau de Parfum', 'Saffron, Cardamom', 'Rose, Oud, Leather', 'Vanilla, Amber, Musk', 'Plush velvet. Oriental and rich.'),
('s327', 'Asad', 'Lattafa', 2022, 'Eau de Parfum', 'Black Pepper, Pineapple, Tobacco', 'Iris, Lavender, Benzoin', 'Amber, Vanilla, Oud, Patchouli, Dried Fruits', 'A fierce lion. Bold spicy tobacco for the price.'),
('s328', 'Raghba', 'Lattafa', 2015, 'Eau de Parfum', 'Bergamot, Spices', 'Musk, Vanilla, Amber', 'Vanilla, Caramel, Praline, Musk', 'Arabian vanilla. Sweet and opulent.'),
('s329', 'Fakhar', 'Lattafa', 2018, 'Eau de Parfum', 'Bergamot, Leather', 'Oud, Rose, Saffron', 'Musk, Amber, Sandalwood', 'A proud scent. Leather and oud richness.'),
('s330', 'Bade''e Al Oud Amethyst', 'Lattafa', 2020, 'Eau de Parfum', 'Plum, Rose', 'Oud, Patchouli, Saffron', 'Vanilla, Musk, Amber, Cedar', 'A purple gem. Plum and oud harmony.'),
('s331', 'L''Aventure', 'Al Haramain', 2016, 'Eau de Parfum', 'Pineapple, Bergamot, Apple', 'Birch, Rose, Jasmine, Patchouli', 'Musk, Oakmoss, Vanilla, Ambergris', 'An Arabian adventure inspired by pineapple-birch combos.'),
('s332', 'Amber Oud Gold Edition', 'Al Haramain', 2019, 'Eau de Parfum', 'Rose, Honey', 'Oud, Amber, Saffron', 'Vanilla, Musk, Sandalwood', 'Gold edition amber. Sweet oud and honey.'),
('s333', 'Encre Noire', 'Lalique', 2006, 'Eau de Toilette', 'Cypress', 'Vetiver, Cashmere Wood', 'Musk', 'Black ink. Dark and smoky vetiver.'),
('s334', 'Encre Noire A L''Extreme', 'Lalique', 2012, 'Eau de Parfum', 'Cypress, Grapefruit', 'Vetiver, Cashmere Wood', 'Sandalwood, Musk, Amber', 'Encre Noire intensified. Deeper and richer.'),
('s335', 'Bentley for Men Intense', 'Bentley', 2013, 'Eau de Parfum', 'Black Pepper, Bay Leaf, Bergamot', 'Clary Sage, Cinnamon, African Geranium', 'Incense, Cedar, Patchouli, Leather, Labdanum, Musk', 'Luxury automotive leather. Distinguished and smoky.'),
('s336', 'Dunhill Icon', 'Alfred Dunhill', 2015, 'Eau de Parfum', 'Bergamot, Neroli, Black Pepper, Cardamom', 'Lavender, Sage, Iris', 'Vetiver, Oud, Leather, Agarwood', 'A British icon. Spiced iris and leather.'),
('s337', 'Tauer L''Air du Desert Marocain', 'Tauer Perfumes', 2005, 'Eau de Toilette', 'Coriander, Pepper, Petitgrain', 'Jasmine, Geranium, Frankincense', 'Cedar, Vetiver, Amber, Tolu Balsam, Vanilla', 'The Moroccan desert air. Dry spices and resins.'),
('s338', 'Imaginary Authors Saint Julep', 'Imaginary Authors', 2016, 'Eau de Parfum', 'Mint, Sugar, Bourbon', 'Orange Blossom, Honeysuckle', 'Musk, Vanilla', 'A southern mint julep. Sweet and refreshing.'),
('s339', 'Imaginary Authors Every Storm a Serenade', 'Imaginary Authors', 2014, 'Eau de Parfum', 'Eucalyptus, Vetiver, Black Moss', 'Wildflowers, Sea Salt', 'Musk, Driftwood', 'A Pacific Northwest storm. Green and salty.'),
('s340', 'D.S. & Durga Rose Atlantic', 'D.S. & Durga', 2015, 'Eau de Parfum', 'Bergamot, Lemon', 'Rose, Salt, Seaweed', 'Musk, Wood', 'A salty rose on the coast. Marine and floral.');

-- BATCH 14: Lancôme, Gucci, Ralph Lauren, Bvlgari, various classics (s341-s385)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s341', 'La Vie Est Belle Intensement', 'Lancôme', 2020, 'Eau de Parfum Intense', 'Red Berries, Raspberry, Orange Blossom', 'Iris, Rose, Jasmine', 'Patchouli, Vanilla, Praline, Benzoin, Sandalwood', 'A more intense La Vie. Deeper iris and vanilla.'),
('s342', 'Idole', 'Lancôme', 2019, 'Eau de Parfum', 'Pear, Bergamot, Pink Pepper', 'Rose, Jasmine', 'White Musk, Cedar, Cashmere Wood, Vanilla', 'A modern idol. Clean rose and pear. Thinnest bottle.'),
('s343', 'Tresor', 'Lancôme', 1990, 'Eau de Parfum', 'Rose, Lily of the Valley, Lilac, Peach, Apricot, Pineapple, Bergamot', 'Iris, Jasmine, Heliotrope, Rose', 'Sandalwood, Amber, Musk, Vanilla, Apricot', 'A precious treasure. Powdery rose and peach.'),
('s344', 'Miracle', 'Lancôme', 2000, 'Eau de Parfum', 'Litchi, Magnolia, Freesia, Mandarin, Ginger', 'Jasmine, Pepper, Rose', 'Musk, Amber, Cedar', 'A morning miracle. Fresh magnolia and spice.'),
('s345', 'La Nuit Tresor', 'Lancôme', 2015, 'Eau de Parfum', 'Litchi, Mandarin, Bergamot, Rose', 'Orchid, Tahitian Vanilla, Praline', 'Patchouli, Papyrus, Vanilla, Cocoa', 'A nocturnal treasure. Orchid and vanilla seduction.'),
('s346', 'Gucci Guilty', 'Gucci', 2010, 'Eau de Toilette', 'Mandarin, Pink Pepper, Lavender', 'Geranium, Lilac', 'Patchouli, Amber, Cedar', 'Unapologetically guilty. Lavender and patchouli.'),
('s347', 'Gucci Bloom', 'Gucci', 2017, 'Eau de Parfum', 'Natural Tuberose', 'Jasmine Bud Extract', 'Rangoon Creeper', 'A blooming garden. Rich white florals.'),
('s348', 'Gucci Guilty Pour Homme', 'Gucci', 2011, 'Eau de Toilette', 'Lavender, Lemon', 'Orange Blossom, Neroli', 'Patchouli, Cedar', 'Masculine guilt. Lavender-orange-patchouli.'),
('s349', 'Flora Gorgeous Gardenia', 'Gucci', 2021, 'Eau de Parfum', 'Pear Blossom, Red Berries', 'Gardenia, Jasmine Grandiflorum', 'Brown Sugar, Musk', 'A gorgeous gardenia. Sweet and floral.'),
('s350', 'Gucci Rush', 'Gucci', 1999, 'Eau de Toilette', 'Freesia, Gardenia, Mandarin', 'Coriander, Rose, Jasmine, Carnation', 'Patchouli, Vanilla, Vetiver, Musk', 'An adrenaline rush. Synthetic but iconic.'),
('s351', 'Polo Blue', 'Ralph Lauren', 2003, 'Eau de Toilette', 'Melon, Cucumber, Mandarin', 'Basil, Clary Sage, Geranium', 'Musk, Suede, Patchouli, Woodsy Notes', 'A preppy blue aquatic. Clean and sporty.'),
('s352', 'Polo Green', 'Ralph Lauren', 1978, 'Eau de Toilette', 'Artemisia, Basil, Thyme, Chamomile, Clary Sage', 'Pine, Juniper, Rose, Carnation, Pepper', 'Oakmoss, Patchouli, Tobacco, Leather, Cedar, Musk', 'The original Polo. A herbal green powerhouse.'),
('s353', 'Polo Red', 'Ralph Lauren', 2013, 'Eau de Toilette', 'Grapefruit, Lemon, Italian Mandarin, Cranberry', 'Saffron, Sage', 'Coffee, Amber, Ebony Wood', 'A red-hot masculine. Spicy coffee and saffron.'),
('s354', 'Ralph Lauren Woman', 'Ralph Lauren', 2017, 'Eau de Parfum', 'Pear, Pink Pepper, Grapefruit', 'Turkish Rose, Osmanthus, Ylang-Ylang', 'Sandalwood, Cashmeran, Musk', 'Modern femininity by Ralph Lauren.'),
('s355', 'Bvlgari Man in Black', 'Bvlgari', 2014, 'Eau de Parfum', 'Rum, Tobacco', 'Tuberose, Iris, Leather', 'Guaiac Wood, Tonka Bean, Benzoin', 'A man in black. Dark rum, leather, iris.'),
('s356', 'Bvlgari Aqva', 'Bvlgari', 2005, 'Eau de Toilette', 'Mandarin, Petit Grain', 'Seaweed, Cotton Flower, Posidonia', 'Amber, Woody Notes, White Cedar', 'Aquatic minimalism. Salty seaweed and amber.'),
('s357', 'Bvlgari Pour Femme', 'Bvlgari', 1994, 'Eau de Parfum', 'Violet, Rose, Iris', 'Jasmine, Mimosa, Orange Blossom', 'Sandalwood, Musk', 'An elegant Italian feminine. Violet and mimosa.'),
('s358', 'Omnia Crystalline', 'Bvlgari', 2005, 'Eau de Toilette', 'Bamboo, Nashi Pear, Balm', 'Lotus, Tea', 'Guaiac Wood, Musk', 'Crystal clear aquatic. Bamboo and lotus zen.'),
('s359', 'Bvlgari Man Wood Neroli', 'Bvlgari', 2019, 'Eau de Parfum', 'Neroli, Mandarin, Bergamot, Petit Grain', 'Orange Blossom, Cedar', 'Musk, Cocoa, Vetiver, Cashmeran', 'Mediterranean woody neroli. Elegant and sunny.'),
('s360', 'Coach For Men', 'Coach', 2017, 'Eau de Toilette', 'Nashi Pear, Bergamot, Kumquat', 'Coriander, Geranium, Cardamom, Clary Sage', 'Vetiver, Ambergris, Suede, Musk', 'American heritage aromatic. Fresh and leathery.'),
('s361', 'Chloe EDP', 'Chloe', 2008, 'Eau de Parfum', 'Peony, Litchi, Freesia', 'Rose, Lily of the Valley, Magnolia', 'Virginia Cedar, Amber, Honey', 'Classic Chloe. Powdery rose and peony.'),
('s362', 'Nomade', 'Chloe', 2018, 'Eau de Parfum', 'Mandarin, Bergamot, Lemon', 'Freesia, Mirabelle Plum, Jasmine, Rose', 'Oakmoss, White Musk, Amber', 'A nomadic spirit. Chypre freshness.'),
('s363', 'Love Story', 'Chloe', 2014, 'Eau de Parfum', 'Neroli, Pear, Bergamot', 'Stephanotis, Orange Blossom', 'Cedar, Cashmere Musk, Iris', 'A Parisian love story. Delicate and luminous.'),
('s364', 'Stronger With You', 'Emporio Armani', 2017, 'Eau de Toilette', 'Cardamom, Pink Pepper, Violet', 'Sage, Meringue', 'Chestnut, Vanilla, Amber', 'Stronger together. Sweet chestnut and vanilla.'),
('s365', 'Stronger With You Intensely', 'Emporio Armani', 2019, 'Eau de Parfum Intense', 'Pink Pepper, Juniper Berry, Violet', 'Sage, Toffee, Cinnamon', 'Suede, Vanilla, Amber', 'A more intense bond. Rich toffee and suede.');

-- BATCH 15: Final perfumes to reach 460+ (s366-s460)
INSERT OR IGNORE INTO perfumes (id, name, brand, year, type, notes_top, notes_heart, notes_base, description) VALUES
('s366', 'Davidoff Cool Water', 'Davidoff', 1988, 'Eau de Toilette', 'Sea Water, Lavender, Mint, Green Notes, Calone, Rosemary', 'Neroli, Jasmine, Geranium, Sandalwood', 'Amber, Cedar, Musk, Oakmoss, Tobacco', 'The iconic aquatic pioneer. Sea breeze and lavender.'),
('s367', 'Cool Water Woman', 'Davidoff', 1996, 'Eau de Toilette', 'Quince, Melon, Blackcurrant, Pineapple, Citrus', 'Jasmine, Lily, Lotus, Rose, May Rose', 'Sandalwood, Peach, Vetiver, Raspberry, Vanilla, Musk', 'A feminine aquatic. Fresh and fruity.'),
('s368', 'Joop! Homme', 'Joop!', 1989, 'Eau de Toilette', 'Orange Blossom, Bergamot, Lemon', 'Heliotrope, Lily of the Valley, Jasmine, Cinnamon', 'Sandalwood, Patchouli, Tonka Bean, Vanilla', 'A daring 80s oriental. Sweet heliotrope and patchouli.'),
('s369', 'Nautica Voyage', 'Nautica', 2006, 'Eau de Toilette', 'Green Leaf, Apple', 'Mimosa, Lotus, Sailcloth Accord', 'Cedar, Musk, Amber, Oakmoss', 'An affordable aquatic. Clean and nautical.'),
('s370', 'Drakkar Noir', 'Guy Laroche', 1982, 'Eau de Toilette', 'Lavender, Lemon, Rosemary, Basil, Artemisia', 'Juniper, Coriander, Cinnamon, Berry, Carnation', 'Cedar, Patchouli, Sandalwood, Amber, Leather, Fir, Oakmoss', 'An 80s powerhouse fougere. Bold and memorable.'),
('s371', 'Perry Ellis 360', 'Perry Ellis', 1993, 'Eau de Toilette', 'Tangerine, Mandarin, Osmanthus, Sage, Lavender', 'Lily of the Valley, Juniper, Rose', 'Vetiver, Musk, Cedar, Amber', 'A fresh and clean 90s classic. Light and wearable.'),
('s372', 'Tommy', 'Tommy Hilfiger', 1995, 'Cologne', 'Lavender, Mint, Bergamot, Grapefruit, Apple', 'Cranberry, Rose, Cinnamon, Jasmine, Cotton Flower', 'Amber, Cedar, Sandalwood, Musk', 'Preppy American spirit. Clean and all-American.'),
('s373', 'Clinique Happy for Men', 'Clinique', 1999, 'Cologne', 'Lime, Mandarin, Green Notes, Sea Notes', 'Cypress, Freesia', 'Cedar, Musk', 'Happy and bright. Citrus simplicity.'),
('s374', 'Chrome', 'Azzaro', 1996, 'Eau de Toilette', 'Rosemary, Neroli, Lemon, Bergamot', 'Pineapple, Coriander, Cyclamen, Jasmine', 'Oakmoss, Tonka Bean, Musk, Sandalwood, Cedar, Cardamom', 'A father-son bond. Clean and comforting.'),
('s375', 'Azzaro Wanted', 'Azzaro', 2016, 'Eau de Toilette', 'Ginger, Lemon, Cardamom', 'Juniper Berry, Apple, Coriander', 'Vetiver, Tonka Bean, Driftwood', 'Wanted by all. Spicy and invigorating.'),
('s376', 'The Most Wanted', 'Azzaro', 2021, 'Eau de Parfum Intense', 'Ginger, Cardamom, Mandarin', 'Toffee, Cedar', 'Amber, Vetiver, Patchouli, Vanilla, Tonka', 'The most wanted intensified. Toffee and spice.'),
('s377', 'Only The Brave', 'Diesel', 2009, 'Eau de Toilette', 'Lemon, Mandarin, Violet Leaves', 'Corriander, Rosemary', 'Amber, Cedar, Leather, Labdanum, Styrax', 'Brave and bold. Woody leather and violet.'),
('s378', 'Spicebomb Extreme', 'Viktor & Rolf', 2015, 'Eau de Parfum', 'Black Pepper, Grapefruit', 'Cinnamon, Saffron, Cumin', 'Tobacco, Leather, Vetiver, Labdanum', 'Spicebomb turned up. Hotter and darker.'),
('s379', 'Spicebomb Infrared', 'Viktor & Rolf', 2021, 'Eau de Toilette', 'Red Pepper, Chili Pepper', 'White Pepper, Cinnamon', 'Vanilla, Patchouli', 'Infrared heat. Pepper and chili warmth.'),
('s380', 'Bonbon', 'Viktor & Rolf', 2014, 'Eau de Parfum', 'Mandarin, Orange, Peach', 'Caramel, Orange Blossom, Jasmine', 'Sandalwood, Cedar, Guaiac Wood', 'A sticky-sweet bonbon. Caramel indulgence.'),
('s381', 'Good Girl Blush', 'Carolina Herrera', 2024, 'Eau de Parfum', 'Pink Pepper, Rose', 'Peach, Rose', 'Tonka Bean, Vanilla, Sandalwood', 'A blushing good girl. Pink and rosy.'),
('s382', '212 VIP Men', 'Carolina Herrera', 2011, 'Eau de Toilette', 'Caviar, Lime, Passion Fruit, Pepper', 'Vodka, Mint, Ginger, Spices', 'Amber, King Wood, Musk, Leather', 'VIP nightlife. Spiced vodka and caviar.'),
('s383', 'Dior Sauvage Parfum', 'Dior', 2019, 'Parfum', 'Calabrian Bergamot', 'Sichuan Pepper, Star Anise, Nutmeg', 'Ambroxan, Vanilla Absolute, Sandalwood', 'The parfum concentration. Richer and smoother.'),
('s384', 'J''adore Infinissime', 'Dior', 2020, 'Eau de Parfum', 'Centifolia Rose, Grasse Jasmine', 'Tuberose, Ylang-Ylang', 'Sandalwood, Woody Notes', 'Infinitely feminine. The richest J''adore.'),
('s385', 'Rouge Trafalgar', 'Dior', 2020, 'Eau de Parfum', 'Raspberry, Bergamot, White Pepper', 'Rose, Peony, Magnolia', 'Patchouli, White Musk', 'A red Dior. Fruity rose with depth.'),
('s386', 'Poison Girl', 'Dior', 2016, 'Eau de Parfum', 'Bitter Orange, Lemon, Rose', 'Grasse Rose, Damask Rose', 'Tonka Bean, Vanilla, Almond, Sandalwood', 'A modern Poison for girls. Sweet rose and almond.'),
('s387', 'Oud Ispahan', 'Dior', 2012, 'Eau de Parfum', 'Rose', 'Rose, Oud, Labdanum, Saffron', 'Patchouli, Sandalwood, Incense, Amber', 'An Ispahan rose garden. Oud and damask rose.'),
('s388', 'Ambre Nuit', 'Dior', 2018, 'Eau de Parfum', 'Rose, Bergamot', 'Amber, Oud', 'Guaiac Wood, Cedar, Musk', 'A warm amber night. Soft rose and dark woods.'),
('s389', 'Rose des Vents', 'Louis Vuitton', 2016, 'Eau de Parfum', 'Rose, Petals', 'Grasse Rose, Turkish Rose', 'Cedar, Musk', 'Wind rose. A delicate journey in rose.'),
('s390', 'Ombre Nomade', 'Louis Vuitton', 2018, 'Eau de Parfum', 'Raspberry, Saffron', 'Oud, Rose, Amber', 'Benzoin, Incense', 'A nomadic shadow. Dark oud and raspberry.'),
('s391', 'L''Immensite', 'Louis Vuitton', 2018, 'Eau de Parfum', 'Ginger, Grapefruit, Bergamot', 'Labdanum, Ambroxan, Mahogany', 'Amber, Woody Notes, Musk', 'The immensity of open spaces. Fresh and ambery.'),
('s392', 'Imagination', 'Louis Vuitton', 2021, 'Eau de Parfum', 'Orange Blossom, Ginger, Bergamot', 'Jasmine, Magnolia', 'Cedar, Musk, Sandalwood', 'Pure imagination. Floral-woody openness.'),
('s393', 'This is Him!', 'Zadig & Voltaire', 2016, 'Eau de Toilette', 'Grapefruit, Mandarin', 'Cardamom, Iris, Fig Leaf', 'Tonka Bean, Sandalwood, Benzoin', 'Rock and roll in a bottle. Spicy and warm.'),
('s394', 'This is Her!', 'Zadig & Voltaire', 2016, 'Eau de Parfum', 'Rose, Mandarin, Pink Pepper', 'Jasmine, Coffee', 'Sandalwood, Cashmere, Musk', 'Freedom in femininity. Coffee and jasmine.'),
('s395', 'La Femme', 'Prada', 2016, 'Eau de Parfum', 'Frangipani, Mandarin', 'Tuberose, Ylang-Ylang, Jasmine', 'Beeswax, Vanilla, Vetiver', 'An intellectual feminine. Floral and waxy.'),
('s396', 'Armani Code Absolu', 'Giorgio Armani', 2019, 'Parfum', 'Green Mandarin, Apple', 'Orange Blossom, Nutmeg, Suede', 'Tonka Bean, Vanilla, Amber', 'The absolute code. Rich and sweet.'),
('s397', 'Emporio Armani In Love With You', 'Giorgio Armani', 2018, 'Eau de Parfum', 'Cherry, Raspberry', 'Jasmine Sambac, Rose', 'Patchouli, Vanilla, Musk, Amber', 'In love indeed. Berry-jasmine sweetness.'),
('s398', 'Shalimar Souffle de Parfum', 'Guerlain', 2014, 'Eau de Parfum', 'Bergamot, Lemon', 'Jasmine, Rose, Orange Blossom', 'Vanilla, Iris, Tonka Bean, White Musk', 'A lighter Shalimar. Airy and modern.'),
('s399', 'L''Heure Bleue', 'Guerlain', 1912, 'Eau de Parfum', 'Anise, Bergamot, Coriander, Lemon', 'Carnation, Rose, Tuberose, Violet, Iris', 'Vanilla, Musk, Benzoin, Sandalwood', 'The blue hour. Twilight in a bottle.'),
('s400', 'Aqua Allegoria Mandarine Basilic', 'Guerlain', 1999, 'Eau de Toilette', 'Mandarin, Basil, Caraway', 'Anise, Tea', 'Musk', 'Mandarin and basil allegoria. Bright and herbal.'),
('s401', 'Mon Guerlain Intense', 'Guerlain', 2019, 'Eau de Parfum', 'Carla Lavender, Bergamot', 'Jasmine Sambac, Iris', 'Vanilla, Sandalwood, Benzoin, Coumarin', 'An intensified Mon Guerlain. Deeper lavender.'),
('s402', 'Givenchy Pi', 'Givenchy', 1998, 'Eau de Toilette', 'Mandarin, Tarragon, Basil, Neroli', 'Geranium, Lily of the Valley', 'Vanilla, Tonka Bean, Benzoin, Almond, Cedar, Anise', 'Mathematical precision. Warm vanilla almond.'),
('s403', 'Gentleman Givenchy EDT', 'Givenchy', 2017, 'Eau de Toilette', 'Pear, Cardamom, Lavender', 'Iris, Orange Blossom', 'Patchouli, Cedar', 'The modern gentleman. Iris and patchouli.'),
('s404', 'L''Interdit Rouge', 'Givenchy', 2021, 'Eau de Parfum', 'Red Pepper, Tuberose', 'Ginger, Iris, Orange Blossom', 'Patchouli, Vetiver, Oud', 'A red forbidden. Tuberose with ginger fire.'),
('s405', 'Dolce & Gabbana Intense', 'Dolce & Gabbana', 2020, 'Eau de Parfum', 'Mandarin, Bergamot', 'Rose, Iris, Peony', 'Patchouli, Musk, Tonka Bean', 'An intensified floral feminine. Rich and warm.'),
('s406', 'Light Blue Forever', 'Dolce & Gabbana', 2021, 'Eau de Parfum', 'Grapefruit, Green Apple', 'Orange Blossom, Jasmine', 'Musk, Cedar, Amber', 'Forever fresh. A richer Light Blue.'),
('s407', 'The One Mysterious Night', 'Dolce & Gabbana', 2016, 'Eau de Parfum', 'Oud, Black Pepper, Grapefruit', 'Cardamom, Cypriol', 'Styrax, Benzoin, Amber', 'A mysterious night out. Smoky oud spice.'),
('s408', 'Scandal Pour Homme Le Parfum', 'Jean Paul Gaultier', 2022, 'Parfum', 'Lavender, Ginger', 'Tonka Bean, Vetiver, Leather', 'Vanilla, Woody Notes', 'The strongest Scandal for him. Dark and sweet.'),
('s409', 'La Belle Le Parfum', 'Jean Paul Gaultier', 2021, 'Parfum', 'Pear, Bergamot', 'Jasmine, Vanilla', 'Licorice, Sandalwood, Vetiver, Vanilla', 'The most beautiful. Deep jasmine-vanilla.'),
('s410', 'Scandal Le Parfum', 'Jean Paul Gaultier', 2020, 'Eau de Parfum Intense', 'Blood Orange, Mandarin', 'Tuberose, Gardenia', 'Vanilla, Tonka Bean, Benzoin', 'An intensified scandal. Tuberose and vanilla.'),
('s411', 'Miss Dior Parfum', 'Dior', 2023, 'Parfum', 'Jasmine, Lily of the Valley', 'Rose, Iris', 'Sandalwood, Musk, Vanilla', 'The ultimate Miss Dior. Rich and opulent.'),
('s412', 'Libre Intense', 'Yves Saint Laurent', 2020, 'Eau de Parfum Intense', 'Mandarin, Bergamot, Lavender', 'Orange Blossom, Jasmine', 'Vanilla, Tonka Bean, Sandalwood, Amber', 'An intensified Libre. Deeper and warmer.'),
('s413', 'My Way Parfum', 'Giorgio Armani', 2022, 'Parfum', 'Orange Blossom, Bergamot, Egypt Jasmine', 'Tuberose, Jasmine Sambac, Indian Tuberose', 'Cedarwood, White Musk, Bourbon Vanilla, Sandalwood', 'The richest My Way. Floral absolute concentration.'),
('s414', 'Code Parfum', 'Giorgio Armani', 2022, 'Parfum', 'Iris, Bergamot, Green Mandarin', 'Iris Absolute, Tonka Bean', 'Leather, Virginia Cedar', 'The ultimate code. Iris and green leather.'),
('s415', 'Dior Homme Cologne', 'Dior', 2013, 'Eau de Cologne', 'Bergamot, Grapefruit, Lemon', 'White Musk', 'Musk', 'The freshest Dior Homme. Pure citrus musk.'),
('s416', 'L''Eau d''Issey Pour Homme Intense', 'Issey Miyake', 2007, 'Eau de Toilette Intense', 'Mandarin, Cinnamon, Saffron, Bergamot', 'Nutmeg, Blue Lotus, Blue Water Lily', 'Amber, Vetiver, Gaiac Wood, Incense', 'An intense Issey. Spicier and deeper.'),
('s417', 'A Drop d''Issey', 'Issey Miyake', 2021, 'Eau de Parfum', 'Lily of the Valley, Lilac', 'Rose, Jasmine, Orange Blossom', 'Musk, Ambroxan', 'A drop of dew on a petal. Delicate and clean.'),
('s418', 'All of Me', 'Narciso Rodriguez', 2023, 'Eau de Parfum', 'Rose, Pink Pepper', 'Iris, Cashmeran, Musk', 'Sandalwood, Amber, Musk', 'All of me in a fragrance. Intimate and warm.'),
('s419', 'English Laundry Oxford Bleu', 'English Laundry', 2013, 'Eau de Parfum', 'Pineapple, Bergamot', 'Birch, Jasmine, Geranium', 'Musk, Amber, Vanilla, Cedar', 'An English laundry fresh scent. Fruity and clean.'),
('s420', 'Aramis', 'Aramis', 1966, 'Eau de Toilette', 'Artemisia, Bergamot, Gardenia', 'Jasmine, Clove, Vetiver, Carnation', 'Leather, Oakmoss, Patchouli, Musk', 'The original American classic masculine.'),
('s421', 'Beautiful', 'Estee Lauder', 1985, 'Eau de Parfum', 'Rose, Lily, Marigold, Orange, Mandarin', 'Jasmine, Tuberose, Carnation, Ylang-Ylang, Iris', 'Sandalwood, Vetiver, Musk, Cedar', 'A timeless floral bouquet. Elegant and feminine.'),
('s422', 'Pleasures', 'Estee Lauder', 1995, 'Eau de Parfum', 'Violet Leaves, Green Notes, Lilac, Baie Rose', 'Rose, Peony, Lily, Jasmine, Karo Karunde', 'Sandalwood, Patchouli, Cedar, Musk, Amber', 'Sheer pleasures. A transparent fresh floral.'),
('s423', 'White Diamonds', 'Elizabeth Taylor', 1991, 'Eau de Toilette', 'Lily, Aldehyde, Neroli, Bergamot, Lemon, Orange', 'Rose, Jasmine, Narcissus, Tuberose, Ylang-Ylang', 'Sandalwood, Amber, Patchouli, Oakmoss, Musk', 'A dazzling celebrity fragrance classic.'),
('s424', 'Viva La Juicy', 'Juicy Couture', 2008, 'Eau de Parfum', 'Wild Berries, Mandarin, Honeysuckle', 'Gardenia, Jasmine, Caramel', 'Sandalwood, Praline, Amber, Vanilla', 'Juicy and vivacious. Sweet berries and caramel.'),
('s425', 'Cloud', 'Ariana Grande', 2018, 'Eau de Parfum', 'Lavender Blossom, Juicy Pear, Bergamot', 'Coconut, Praline, Vanilla Orchid', 'Blonde Woods, Cashmere Musk, Creamy Musks', 'Fluffy cloud nine. Sweet coconut and musk.'),
('s426', 'Fantasy', 'Britney Spears', 2005, 'Eau de Parfum', 'Lychee, Kiwi, Quince', 'Cupcake, Jasmine, White Chocolate Orchid', 'Musk, Orris, Cedar', 'A sweet pop star fantasy. Fun and fruity.'),
('s427', 'Ari', 'Ariana Grande', 2015, 'Eau de Parfum', 'Crispy Pear, Pink Grapefruit, Raspberry', 'Soft Muguet, Rose Buds, Vanilla Orchid', 'Marshmallow, Blonde Wood, Musk', 'A sweet marshmallow treat. Young and bubbly.'),
('s428', 'Amor Amor', 'Cacharel', 2003, 'Eau de Toilette', 'Grapefruit, Mandarin, Blood Orange, Blackcurrant', 'Lily of the Valley, Rose, Jasmine, Apricot', 'Vanilla, Cedar, Sandalwood, Tonka Bean, Musk', 'Passionate red love. Fresh fruits and warm vanilla.'),
('s429', 'L''Aventure Knight', 'Al Haramain', 2020, 'Eau de Parfum', 'Pink Pepper, Saffron', 'Iris, Oud, Cedar', 'Amber, Leather, Vetiver', 'A dark knight. Iris and oud interplay.'),
('s430', 'Khamrah', 'Lattafa', 2022, 'Eau de Parfum', 'Cinnamon, Nutmeg, Bergamot', 'Praline, Dates, Vanilla', 'Tonka Bean, Benzoin, Amber, Oud', 'Intoxicating Arabian gourmand. Praline and dates.'),
('s431', 'Yara', 'Lattafa', 2021, 'Eau de Parfum', 'Orchid, Heliotrope, Tangerine', 'Acacia, Cashmere', 'Vanilla, Musk, Sandalwood, Tonka Bean', 'A beloved feminine. Tropical orchid sweetness.'),
('s432', 'Dulcis in Fundo', 'Nishane', 2019, 'Extrait de Parfum', 'Peach, Red Apple, Raspberry', 'Rose, Heliotrope, Iris', 'Vanilla, Praline, Tonka Bean, Musk, Amber', 'Sweet at the end. A gourmand fruity dessert.'),
('s433', 'Vain & Naive', 'Nishane', 2019, 'Extrait de Parfum', 'Bergamot, Pink Pepper, Mandarin', 'Orange Blossom, Iris, Jasmine', 'Musk, Amber, Vetiver', 'Vain and naive indeed. Citrus and iris freshness.'),
('s434', 'Sultan Vetiver', 'Nishane', 2012, 'Extrait de Parfum', 'Bergamot, Grapefruit, Lavender', 'Vetiver, Geranium, Rose', 'Amber, Musk, Tonka Bean', 'A sultan of vetiver. Rich and complex.'),
('s435', 'Tiziana Terenzi Kirke', 'Tiziana Terenzi', 2017, 'Extrait de Parfum', 'Peach, Raspberry, Passion Fruit', 'Rose, Jasmine, Ylang-Ylang', 'Vanilla, Musk, Sandalwood, Amber', 'A mythical fruity floral. Peach and rose.'),
('s436', 'Tiziana Terenzi Andromeda', 'Tiziana Terenzi', 2019, 'Extrait de Parfum', 'Mandarin, Bergamot, Pink Pepper', 'Rose, Jasmine, Iris', 'Amber, Musk, Patchouli, Vanilla', 'A celestial floral. Starlit rose and amber.'),
('s437', 'PDM Galloway', 'Parfums de Marly', 2014, 'Eau de Parfum', 'Lemon, Bergamot, Mandarin, Green Notes', 'Orange Blossom, Geranium', 'Musk, Amber, Cedar', 'A fresh citrus equestrian scent. Crisp and green.'),
('s438', 'PDM Cassili', 'Parfums de Marly', 2019, 'Eau de Parfum', 'Bergamot, Pink Pepper, Peach', 'Rose, Jasmine, Osmanthus', 'Sandalwood, Musk, Vanilla, Ambroxan', 'A delicate feminine. Peach blossom softness.'),
('s439', 'PDM Greenley', 'Parfums de Marly', 2020, 'Eau de Parfum', 'Apple, Bergamot, Mandarin', 'Green Tea, Fig Leaf', 'Cedar, Vetiver, Musk', 'A green apple freshness. Clean and modern.'),
('s440', 'Versace Medusa', 'Versace', 2023, 'Eau de Parfum', 'Pink Pepper, Bergamot', 'Rose, Iris', 'Amber, Musk, Cedar', 'The Medusa gaze. Bold and captivating.'),
('s441', 'Versace Eros Parfum', 'Versace', 2021, 'Parfum', 'Mint, Green Apple, Lemon', 'Geranium, Ambroxan, Tonka Bean', 'Vetiver, Cedar, Vanilla, Musk, Patchouli', 'The parfum-strength Eros. Deepest concentration.'),
('s442', 'Gucci Guilty Elixir', 'Gucci', 2022, 'Parfum', 'Mandarin, Pink Pepper', 'Iris, Rose, Leather', 'Patchouli, Amber, Musk', 'The elixir of guilt. Intense and mysterious.'),
('s443', 'Boss The Scent Absolute', 'Hugo Boss', 2019, 'Eau de Parfum', 'Ginger, Pineapple', 'Maninka, Osmanthus', 'Leather, Musk', 'Absolute seduction. Concentrated ginger-leather.'),
('s444', 'Scandal Pour Homme', 'Jean Paul Gaultier', 2021, 'Eau de Toilette', 'Mandarin, Caramel', 'Vetiver, Spearmint', 'Tonka Bean, Amber, Woody Notes', 'A masculine scandal. Caramel and vetiver.'),
('s445', 'Bleu de Chanel Parfum', 'Chanel', 2018, 'Parfum', 'Lemon, Mint, Pink Pepper, Grapefruit', 'Ginger, Nutmeg, Jasmine, Iso E Super', 'Incense, Cedar, Sandalwood, Tonka Bean, Patchouli', 'The parfum concentration. The most intense Bleu.'),
('s446', 'Allure Homme Sport Eau Extreme', 'Chanel', 2012, 'Eau de Parfum', 'Mandarin, Pepper', 'Cedar, Tonka Bean, Sage', 'Musk, Sandalwood, Amber', 'Sport extreme. Longer lasting and deeper.'),
('s447', 'Coco Mademoiselle Intense', 'Chanel', 2018, 'Eau de Parfum', 'Bitter Orange, Calabrian Bergamot, Sicilian Orange', 'Absolute Rose, Absolute Jasmine', 'Patchouli, Tonka Bean, Vanilla, Benzoin, White Musk', 'A more intense Mademoiselle. Darker and richer.'),
('s448', 'Le Lion de Chanel', 'Chanel', 2020, 'Eau de Parfum', 'Bergamot, Aldehydes', 'Labdanum, Rose', 'Sandalwood, Musk, Vanilla, Tonka Bean', 'The Chanel lion. Bold labdanum and sandalwood.'),
('s449', 'Sauvage Elixir', 'Dior', 2021, 'Elixir', 'Grapefruit, Cinnamon, Cardamom, Nutmeg', 'Lavender', 'Licorice, Sandalwood, Amber, Patchouli, Vetiver', 'The most concentrated Sauvage. Spicy, smooth, powerful.'),
('s450', 'Miss Dior Rose N''Roses', 'Dior', 2020, 'Eau de Toilette', 'Bergamot, Mandarin', 'Grasse Rose, Damask Rose, Centifolia Rose', 'White Musk', 'A cascade of roses. Fresh and radiant.'),
('s451', 'Stronger With You Absolutely', 'Emporio Armani', 2021, 'Parfum', 'Juniper Berry, Pink Pepper', 'Lavender, Iris', 'Vanilla, Chestnut, Musk, Amber', 'Absolutely strong. The deepest connection.'),
('s452', 'Y Eau de Toilette', 'Yves Saint Laurent', 2017, 'Eau de Toilette', 'Apple, Ginger, Bergamot', 'Sage, Juniper Berry, Geranium', 'Cedar, Vetiver, Olibanum, Fougere Accord', 'The fresh Y. Light and versatile.'),
('s453', 'Le Beau Le Parfum', 'Jean Paul Gaultier', 2022, 'Parfum', 'Bergamot, Green Notes', 'Coconut, Tonka Bean', 'Vanilla, Sandalwood', 'The beautiful parfum. Coconut and vanilla.'),
('s454', 'Phantom Parfum', 'Paco Rabanne', 2023, 'Parfum', 'Lemon, Lavender', 'Smoke, Myrrh', 'Vanilla, Vetiver, Styrax', 'Phantom upgraded. Smoky lavender vanilla.'),
('s455', 'Luna Rossa Sport', 'Prada', 2015, 'Eau de Toilette', 'Ginger, Juniper Berry, Bergamot, Lavender', 'Vanilla, Cinnamon, Cardamom', 'Patchouli, Tonka Bean, Amber', 'A sporty Luna Rossa. Energetic and fresh.'),
('s456', 'Born in Roma Yellow Dream Donna', 'Valentino', 2022, 'Eau de Toilette', 'Italian Lemon, Mandarin', 'Osmanthus, Rose', 'Musk, Cedar', 'A yellow dream. Bright citrus and osmanthus.'),
('s457', 'Flora Gorgeous Jasmine', 'Gucci', 2022, 'Eau de Parfum', 'Mandarin, Grandiflorum Jasmine', 'Jasmine, Rose', 'Benzoin, Sandalwood', 'Gorgeous jasmine garden. Fresh and addictive.'),
('s458', 'Olympea Legend', 'Paco Rabanne', 2019, 'Eau de Parfum', 'Green Mandarin, Plum', 'Apricot Blossom, Sambac Jasmine', 'Sandalwood, Cashmere Musk', 'A legendary goddess. Sweet plum and jasmine.'),
('s459', 'La Belle', 'Jean Paul Gaultier', 2019, 'Eau de Parfum', 'Pear, Bergamot', 'Vanilla, Jasmine', 'Licorice, Sandalwood, Tonka Bean, Vetiver', 'A beautiful feminine. Vanilla and jasmine duet.'),
('s460', 'Explorer Platinum', 'Montblanc', 2023, 'Eau de Parfum', 'Grapefruit, Elemi, Bergamot', 'Iris, Geranium, Violet', 'Leather, Patchouli, Amber, Musk', 'Platinum exploration. Iris and leather refinement.');

-- End of migration 010
-- Total: 460 new perfumes (s001-s460)
-- Combined with existing ~50 from migration 005, this gives 500+ total perfumes
