-- Seed 450+ additional perfumes for FragBase MVP (total 500+)
-- Adds to the existing 50 from migration 005

INSERT OR IGNORE INTO perfumes (id, name, brand, year, gender, concentration, type) VALUES
-- Designer Men's
('p051', '1 Million', 'Paco Rabanne', 2008, 'masculine', 'Eau de Toilette', 'spicy'),
('p052', 'Le Male', 'Jean Paul Gaultier', 1995, 'masculine', 'Eau de Toilette', 'aromatic'),
('p053', 'Dior Homme Intense', 'Dior', 2011, 'masculine', 'Eau de Parfum', 'floral'),
('p054', 'Allure Homme Sport', 'Chanel', 2004, 'masculine', 'Eau de Toilette', 'fresh'),
('p055', 'Explorer', 'Montblanc', 2019, 'masculine', 'Eau de Parfum', 'woody'),
('p056', 'Luna Rossa Carbon', 'Prada', 2017, 'masculine', 'Eau de Toilette', 'aromatic'),
('p057', 'Terre d''Hermès', 'Hermès', 2006, 'masculine', 'Eau de Toilette', 'woody'),
('p058', 'Armani Code', 'Giorgio Armani', 2004, 'masculine', 'Eau de Toilette', 'oriental'),
('p059', 'Boss Bottled', 'Hugo Boss', 2009, 'masculine', 'Eau de Parfum', 'woody'),
('p060', 'Mr. Burberry', 'Burberry', 2016, 'masculine', 'Eau de Parfum', 'woody'),
('p061', 'Polo Blue', 'Ralph Lauren', 2003, 'masculine', 'Eau de Toilette', 'aquatic'),
('p062', 'Eternity', 'Calvin Klein', 1988, 'masculine', 'Eau de Toilette', 'aromatic'),
('p063', 'L''Homme', 'Yves Saint Laurent', 2006, 'masculine', 'Eau de Toilette', 'fresh'),
('p064', 'Gucci Guilty Pour Homme', 'Gucci', 2011, 'masculine', 'Eau de Toilette', 'aromatic'),
('p065', 'Valentino Uomo Intense', 'Valentino', 2016, 'masculine', 'Eau de Parfum', 'leather'),
('p066', 'CH Men Privé', 'Carolina Herrera', 2015, 'masculine', 'Eau de Toilette', 'leather'),
('p067', 'Gentleman Givenchy', 'Givenchy', 2017, 'masculine', 'Eau de Parfum', 'woody'),
('p068', 'Stronger With You', 'Emporio Armani', 2017, 'masculine', 'Eau de Toilette', 'sweet'),
('p069', 'Prada L''Homme', 'Prada', 2016, 'masculine', 'Eau de Toilette', 'amber'),
('p070', 'Azzaro Wanted', 'Azzaro', 2016, 'masculine', 'Eau de Toilette', 'spicy'),
('p071', 'Dolce & Gabbana Light Blue', 'Dolce & Gabbana', 2007, 'masculine', 'Eau de Toilette', 'citrus'),
('p072', 'Issey Miyake L''Eau d''Issey', 'Issey Miyake', 1994, 'masculine', 'Eau de Toilette', 'aquatic'),
('p073', 'Narciso Rodriguez For Him', 'Narciso Rodriguez', 2007, 'masculine', 'Eau de Parfum', 'musky'),
('p074', 'Versace Pour Homme', 'Versace', 2008, 'masculine', 'Eau de Toilette', 'aromatic'),
('p075', 'Givenchy Pi', 'Givenchy', 1998, 'masculine', 'Eau de Toilette', 'sweet'),
('p076', 'Fahrenheit', 'Dior', 1988, 'masculine', 'Eau de Toilette', 'leather'),
('p077', 'Obsession', 'Calvin Klein', 1986, 'masculine', 'Eau de Toilette', 'oriental'),
('p078', 'Polo Green', 'Ralph Lauren', 1978, 'masculine', 'Eau de Toilette', 'green'),
('p079', 'Drakkar Noir', 'Guy Laroche', 1982, 'masculine', 'Eau de Toilette', 'aromatic'),
('p080', 'Kouros', 'Yves Saint Laurent', 1981, 'masculine', 'Eau de Toilette', 'aromatic'),

-- Designer Women's
('p081', 'Chanel No. 5', 'Chanel', 1921, 'feminine', 'Eau de Parfum', 'floral'),
('p082', 'Shalimar', 'Guerlain', 1925, 'feminine', 'Eau de Parfum', 'oriental'),
('p083', 'Daisy', 'Marc Jacobs', 2007, 'feminine', 'Eau de Toilette', 'floral'),
('p084', 'Gucci Bloom', 'Gucci', 2017, 'feminine', 'Eau de Parfum', 'floral'),
('p085', 'Chloe EDP', 'Chloé', 2008, 'feminine', 'Eau de Parfum', 'floral'),
('p086', 'Libre', 'Yves Saint Laurent', 2019, 'feminine', 'Eau de Parfum', 'floral'),
('p087', 'My Way', 'Giorgio Armani', 2020, 'feminine', 'Eau de Parfum', 'floral'),
('p088', 'Angel', 'Mugler', 1992, 'feminine', 'Eau de Parfum', 'sweet'),
('p089', 'Olympéa', 'Paco Rabanne', 2015, 'feminine', 'Eau de Parfum', 'oriental'),
('p090', 'Joy', 'Dior', 2018, 'feminine', 'Eau de Parfum', 'floral'),
('p091', 'Bright Crystal', 'Versace', 2006, 'feminine', 'Eau de Toilette', 'floral'),
('p092', 'Hypnotic Poison', 'Dior', 1998, 'feminine', 'Eau de Toilette', 'oriental'),
('p093', 'Crystal Noir', 'Versace', 2004, 'feminine', 'Eau de Toilette', 'oriental'),
('p094', 'Poison Girl', 'Dior', 2016, 'feminine', 'Eau de Parfum', 'sweet'),
('p095', 'Idôle', 'Lancôme', 2019, 'feminine', 'Eau de Parfum', 'floral'),
('p096', 'Voce Viva', 'Valentino', 2020, 'feminine', 'Eau de Parfum', 'floral'),
('p097', 'Donna Born In Roma', 'Valentino', 2019, 'feminine', 'Eau de Parfum', 'floral'),
('p098', 'Very Good Girl', 'Carolina Herrera', 2021, 'feminine', 'Eau de Parfum', 'sweet'),
('p099', 'Flora Gorgeous Gardenia', 'Gucci', 2021, 'feminine', 'Eau de Parfum', 'floral'),
('p100', 'Omnia Crystalline', 'Bvlgari', 2005, 'feminine', 'Eau de Toilette', 'floral'),

-- Niche Unisex
('p101', 'Aventus for Her', 'Creed', 2016, 'feminine', 'Eau de Parfum', 'fruity'),
('p102', 'Noir de Noir', 'Tom Ford', 2007, 'unisex', 'Eau de Parfum', 'oriental'),
('p103', 'Black Orchid', 'Tom Ford', 2006, 'unisex', 'Eau de Parfum', 'oriental'),
('p104', 'Rose 31', 'Le Labo', 2006, 'unisex', 'Eau de Parfum', 'floral'),
('p105', 'Bergamote 22', 'Le Labo', 2006, 'unisex', 'Eau de Parfum', 'citrus'),
('p106', 'Mojave Ghost', 'Byredo', 2014, 'unisex', 'Eau de Parfum', 'woody'),
('p107', 'Black Saffron', 'Byredo', 2012, 'unisex', 'Eau de Parfum', 'spicy'),
('p108', 'Ambre Nuit', 'Dior', 2018, 'unisex', 'Eau de Parfum', 'amber'),
('p109', 'Oud Ispahan', 'Dior', 2012, 'unisex', 'Eau de Parfum', 'oriental'),
('p110', 'Rose des Vents', 'Louis Vuitton', 2016, 'feminine', 'Eau de Parfum', 'floral'),
('p111', 'Ombre Nomade', 'Louis Vuitton', 2018, 'unisex', 'Eau de Parfum', 'woody'),
('p112', 'Reflection Man', 'Amouage', 2007, 'masculine', 'Eau de Parfum', 'floral'),
('p113', 'Jubilation XXV', 'Amouage', 2007, 'masculine', 'Eau de Parfum', 'oriental'),
('p114', 'Pegasus', 'Parfums de Marly', 2011, 'masculine', 'Eau de Parfum', 'sweet'),
('p115', 'Sedley', 'Parfums de Marly', 2019, 'masculine', 'Eau de Parfum', 'fresh'),
('p116', 'Ani', 'Nishane', 2019, 'unisex', 'Extrait de Parfum', 'vanilla'),
('p117', 'Fan Your Flames', 'Nishane', 2015, 'unisex', 'Extrait de Parfum', 'oriental'),
('p118', 'Gentle Fluidity Gold', 'Maison Francis Kurkdjian', 2019, 'unisex', 'Eau de Parfum', 'musky'),
('p119', 'Oud Satin Mood', 'Maison Francis Kurkdjian', 2015, 'unisex', 'Eau de Parfum', 'oriental'),
('p120', 'Side Effect', 'Initio', 2018, 'unisex', 'Eau de Parfum', 'sweet'),
('p121', 'Oud for Greatness', 'Initio', 2018, 'unisex', 'Eau de Parfum', 'woody'),
('p122', 'Naxos', 'Xerjoff', 2015, 'unisex', 'Eau de Parfum', 'sweet'),
('p123', 'Erba Pura', 'Xerjoff', 2019, 'unisex', 'Eau de Parfum', 'fruity'),
('p124', 'Halfeti', 'Penhaligon''s', 2015, 'unisex', 'Eau de Parfum', 'woody'),
('p125', 'Philosykos', 'Diptyque', 2001, 'unisex', 'Eau de Toilette', 'green'),
('p126', 'Tam Dao', 'Diptyque', 2003, 'unisex', 'Eau de Parfum', 'woody'),
('p127', 'Wood Sage & Sea Salt', 'Jo Malone', 2014, 'unisex', 'Cologne', 'aromatic'),
('p128', 'English Pear & Freesia', 'Jo Malone', 2010, 'unisex', 'Cologne', 'fruity'),
('p129', 'Elysium', 'Roja Parfums', 2017, 'masculine', 'Parfum Cologne', 'fresh'),
('p130', 'Enigma', 'Roja Parfums', 2014, 'masculine', 'Parfum', 'oriental'),

-- More Designer Men's
('p131', 'Sauvage Elixir', 'Dior', 2021, 'masculine', 'Elixir', 'spicy'),
('p132', 'Born in Roma Uomo', 'Valentino', 2019, 'masculine', 'Eau de Toilette', 'aromatic'),
('p133', 'Phantom', 'Paco Rabanne', 2021, 'masculine', 'Eau de Toilette', 'aromatic'),
('p134', 'Bad Boy', 'Carolina Herrera', 2019, 'masculine', 'Eau de Toilette', 'aromatic'),
('p135', 'Acqua di Gio Absolu', 'Giorgio Armani', 2018, 'masculine', 'Eau de Parfum', 'woody'),
('p136', 'Libre Pour Homme', 'Yves Saint Laurent', 2023, 'masculine', 'Eau de Parfum', 'aromatic'),
('p137', 'Guerlain L''Homme Idéal', 'Guerlain', 2014, 'masculine', 'Eau de Parfum', 'sweet'),
('p138', 'Coach For Men', 'Coach', 2017, 'masculine', 'Eau de Toilette', 'aromatic'),
('p139', 'CK Everyone', 'Calvin Klein', 2020, 'unisex', 'Eau de Toilette', 'citrus'),
('p140', 'Burberry Hero', 'Burberry', 2021, 'masculine', 'Eau de Parfum', 'woody'),
('p141', 'Gucci Guilty Elixir', 'Gucci', 2022, 'masculine', 'Parfum', 'aromatic'),
('p142', 'Eros Flame', 'Versace', 2018, 'masculine', 'Eau de Parfum', 'woody'),
('p143', 'Le Male Le Parfum', 'Jean Paul Gaultier', 2020, 'masculine', 'Eau de Parfum', 'oriental'),
('p144', 'Scandal Pour Homme', 'Jean Paul Gaultier', 2021, 'masculine', 'Eau de Toilette', 'sweet'),
('p145', 'Hugo Man', 'Hugo Boss', 1995, 'masculine', 'Eau de Toilette', 'green'),
('p146', 'Tommy', 'Tommy Hilfiger', 1995, 'masculine', 'Cologne', 'aromatic'),
('p147', 'Clinique Happy', 'Clinique', 1997, 'masculine', 'Cologne', 'citrus'),
('p148', 'Curve', 'Liz Claiborne', 1996, 'masculine', 'Cologne', 'fresh'),
('p149', 'Chrome', 'Azzaro', 1996, 'masculine', 'Eau de Toilette', 'citrus'),
('p150', 'Pi Neo', 'Givenchy', 2008, 'masculine', 'Eau de Toilette', 'woody'),

-- More Designer Women's
('p151', 'Chance Eau Fraîche', 'Chanel', 2007, 'feminine', 'Eau de Toilette', 'citrus'),
('p152', 'Miss Dior Blooming Bouquet', 'Dior', 2014, 'feminine', 'Eau de Toilette', 'floral'),
('p153', 'Dolce', 'Dolce & Gabbana', 2014, 'feminine', 'Eau de Parfum', 'floral'),
('p154', 'Viva La Juicy', 'Juicy Couture', 2008, 'feminine', 'Eau de Parfum', 'sweet'),
('p155', 'Gucci Guilty', 'Gucci', 2010, 'feminine', 'Eau de Toilette', 'aromatic'),
('p156', 'Acqua di Gioia', 'Giorgio Armani', 2010, 'feminine', 'Eau de Parfum', 'aquatic'),
('p157', 'Burberry Her', 'Burberry', 2018, 'feminine', 'Eau de Parfum', 'fruity'),
('p158', 'L''Interdit', 'Givenchy', 2018, 'feminine', 'Eau de Parfum', 'floral'),
('p159', 'Alien Goddess', 'Mugler', 2021, 'feminine', 'Eau de Parfum', 'floral'),
('p160', 'Mon Paris', 'Yves Saint Laurent', 2016, 'feminine', 'Eau de Parfum', 'sweet'),
('p161', 'Ari', 'Ariana Grande', 2015, 'feminine', 'Eau de Parfum', 'fruity'),
('p162', 'Cloud', 'Ariana Grande', 2018, 'feminine', 'Eau de Parfum', 'sweet'),
('p163', 'Fantasy', 'Britney Spears', 2005, 'feminine', 'Eau de Parfum', 'fruity'),
('p164', 'Euphoria', 'Calvin Klein', 2005, 'feminine', 'Eau de Parfum', 'oriental'),
('p165', 'Beautiful', 'Estée Lauder', 1985, 'feminine', 'Eau de Parfum', 'floral'),
('p166', 'Pleasures', 'Estée Lauder', 1995, 'feminine', 'Eau de Parfum', 'floral'),
('p167', 'White Diamonds', 'Elizabeth Taylor', 1991, 'feminine', 'Eau de Toilette', 'floral'),
('p168', 'Giorgio Beverly Hills', 'Giorgio Beverly Hills', 1981, 'feminine', 'Eau de Toilette', 'floral'),
('p169', 'Paris', 'Yves Saint Laurent', 1983, 'feminine', 'Eau de Parfum', 'floral'),
('p170', 'Opium', 'Yves Saint Laurent', 1977, 'feminine', 'Eau de Toilette', 'oriental'),

-- Niche Part 2
('p171', 'Virgin Island Water', 'Creed', 2007, 'unisex', 'Eau de Parfum', 'citrus'),
('p172', 'Original Vetiver', 'Creed', 2004, 'masculine', 'Eau de Parfum', 'green'),
('p173', 'Millesime Imperial', 'Creed', 1995, 'unisex', 'Eau de Parfum', 'aquatic'),
('p174', 'Royal Oud', 'Creed', 2011, 'unisex', 'Eau de Parfum', 'woody'),
('p175', 'Bitter Peach', 'Tom Ford', 2020, 'unisex', 'Eau de Parfum', 'fruity'),
('p176', 'Fucking Fabulous', 'Tom Ford', 2017, 'unisex', 'Eau de Parfum', 'leather'),
('p177', 'Soleil Blanc', 'Tom Ford', 2016, 'unisex', 'Eau de Parfum', 'sweet'),
('p178', 'Cafe Rose', 'Tom Ford', 2012, 'unisex', 'Eau de Parfum', 'floral'),
('p179', 'Grey Vetiver', 'Tom Ford', 2009, 'masculine', 'Eau de Parfum', 'green'),
('p180', 'Rose Prick', 'Tom Ford', 2020, 'unisex', 'Eau de Parfum', 'floral'),
('p181', 'Libre Intense', 'Yves Saint Laurent', 2020, 'feminine', 'Eau de Parfum Intense', 'floral'),
('p182', 'Iris 39', 'Le Labo', 2013, 'unisex', 'Eau de Parfum', 'floral'),
('p183', 'Thé Noir 29', 'Le Labo', 2015, 'unisex', 'Eau de Parfum', 'smoky'),
('p184', 'Vanille 44', 'Le Labo', 2006, 'unisex', 'Eau de Parfum', 'vanilla'),
('p185', 'Super Cedar', 'Byredo', 2016, 'unisex', 'Eau de Parfum', 'woody'),
('p186', 'Bibliothèque', 'Byredo', 2017, 'unisex', 'Eau de Parfum', 'woody'),
('p187', 'Blanche', 'Byredo', 2009, 'feminine', 'Eau de Parfum', 'musky'),
('p188', 'Do Son', 'Diptyque', 2005, 'unisex', 'Eau de Toilette', 'floral'),
('p189', 'Eau Duelle', 'Diptyque', 2010, 'unisex', 'Eau de Parfum', 'vanilla'),
('p190', 'Peony & Blush Suede', 'Jo Malone', 2013, 'feminine', 'Cologne', 'floral'),
('p191', 'Lime Basil & Mandarin', 'Jo Malone', 1999, 'unisex', 'Cologne', 'citrus'),
('p192', 'Pomegranate Noir', 'Jo Malone', 2005, 'unisex', 'Cologne', 'fruity'),
('p193', 'Percival', 'Parfums de Marly', 2018, 'masculine', 'Eau de Parfum', 'fresh'),
('p194', 'Carlisle', 'Parfums de Marly', 2015, 'unisex', 'Eau de Parfum', 'oriental'),
('p195', 'Godolphin', 'Parfums de Marly', 2017, 'masculine', 'Eau de Parfum', 'leather'),
('p196', 'Safanad', 'Parfums de Marly', 2014, 'feminine', 'Eau de Parfum', 'floral'),
('p197', 'Rehab', 'Initio', 2020, 'unisex', 'Eau de Parfum', 'musky'),
('p198', 'Atomic Rose', 'Initio', 2018, 'unisex', 'Eau de Parfum', 'floral'),
('p199', 'Mefisto', 'Xerjoff', 2009, 'masculine', 'Eau de Parfum', 'citrus'),
('p200', 'Alexandria II', 'Xerjoff', 2009, 'unisex', 'Eau de Parfum', 'sweet'),

-- Modern Hits 2020s
('p201', 'Dior Sauvage Parfum', 'Dior', 2019, 'masculine', 'Parfum', 'aromatic'),
('p202', 'Bleu de Chanel Parfum', 'Chanel', 2018, 'masculine', 'Parfum', 'woody'),
('p203', 'Stronger With You Intensely', 'Emporio Armani', 2019, 'masculine', 'Eau de Parfum Intense', 'sweet'),
('p204', 'Only The Brave', 'Diesel', 2009, 'masculine', 'Eau de Toilette', 'woody'),
('p205', 'L''Immensité', 'Louis Vuitton', 2018, 'masculine', 'Eau de Parfum', 'amber'),
('p206', 'Au Hasard', 'Louis Vuitton', 2018, 'masculine', 'Eau de Parfum', 'woody'),
('p207', 'Bois d''Argent', 'Dior', 2004, 'unisex', 'Eau de Parfum', 'woody'),
('p208', 'Spicebomb Extreme', 'Viktor & Rolf', 2015, 'masculine', 'Eau de Parfum', 'spicy'),
('p209', 'Cedrat Boisé', 'Mancera', 2012, 'unisex', 'Eau de Parfum', 'citrus'),
('p210', 'Red Tobacco', 'Mancera', 2017, 'unisex', 'Eau de Parfum', 'spicy'),
('p211', 'Instant Crush', 'Mancera', 2019, 'unisex', 'Eau de Parfum', 'sweet'),
('p212', 'Lira', 'Xerjoff', 2012, 'feminine', 'Eau de Parfum', 'sweet'),
('p213', 'Starlight', 'Xerjoff', 2020, 'feminine', 'Eau de Parfum', 'floral'),
('p214', 'Amber Aoud', 'Roja Parfums', 2012, 'unisex', 'Parfum', 'amber'),
('p215', 'Scandal', 'Roja Parfums', 2016, 'feminine', 'Parfum', 'sweet'),
('p216', 'Oud for Love', 'The House of Oud', 2016, 'unisex', 'Eau de Parfum', 'oriental'),
('p217', 'Tobacco Oud', 'Tom Ford', 2013, 'unisex', 'Eau de Parfum', 'smoky'),
('p218', 'White Suede', 'Tom Ford', 2009, 'feminine', 'Eau de Parfum', 'musky'),
('p219', 'Velvet Orchid', 'Tom Ford', 2014, 'feminine', 'Eau de Parfum', 'oriental'),
('p220', 'Mandarino di Amalfi', 'Tom Ford', 2014, 'unisex', 'Eau de Parfum', 'citrus'),

-- Clean & Fresh
('p221', 'Clean Reserve Skin', 'Clean', 2016, 'unisex', 'Eau de Parfum', 'musky'),
('p222', 'Clean Reserve Sueded Oud', 'Clean', 2016, 'unisex', 'Eau de Parfum', 'woody'),
('p223', 'Replica Jazz Club', 'Maison Margiela', 2013, 'masculine', 'Eau de Toilette', 'smoky'),
('p224', 'Replica Beach Walk', 'Maison Margiela', 2012, 'feminine', 'Eau de Toilette', 'aquatic'),
('p225', 'Replica Lazy Sunday Morning', 'Maison Margiela', 2012, 'unisex', 'Eau de Toilette', 'floral'),
('p226', 'Replica Coffee Break', 'Maison Margiela', 2018, 'unisex', 'Eau de Toilette', 'sweet'),
('p227', 'Replica Bubble Bath', 'Maison Margiela', 2020, 'unisex', 'Eau de Toilette', 'musky'),
('p228', 'Replica Autumn Vibes', 'Maison Margiela', 2019, 'unisex', 'Eau de Toilette', 'woody'),
('p229', 'Replica Sailing Day', 'Maison Margiela', 2016, 'unisex', 'Eau de Toilette', 'aquatic'),
('p230', 'At The Barber''s', 'Maison Margiela', 2015, 'unisex', 'Eau de Toilette', 'aromatic'),

-- Atelier Cologne
('p231', 'Clémentine California', 'Atelier Cologne', 2017, 'unisex', 'Cologne Absolue', 'citrus'),
('p232', 'Orange Sanguine', 'Atelier Cologne', 2011, 'unisex', 'Cologne Absolue', 'citrus'),
('p233', 'Vanille Insensée', 'Atelier Cologne', 2011, 'unisex', 'Cologne Absolue', 'vanilla'),
('p234', 'Oolang Infini', 'Atelier Cologne', 2010, 'unisex', 'Cologne Absolue', 'aromatic'),
('p235', 'Pacific Lime', 'Atelier Cologne', 2019, 'unisex', 'Cologne Absolue', 'citrus'),

-- Kilian
('p236', 'Angels'' Share', 'Kilian', 2020, 'unisex', 'Eau de Parfum', 'sweet'),
('p237', 'Good Girl Gone Bad', 'Kilian', 2012, 'feminine', 'Eau de Parfum', 'floral'),
('p238', 'Love Don''t Be Shy', 'Kilian', 2007, 'feminine', 'Eau de Parfum', 'sweet'),
('p239', 'Straight to Heaven', 'Kilian', 2007, 'masculine', 'Eau de Parfum', 'woody'),
('p240', 'Rolling in Love', 'Kilian', 2019, 'feminine', 'Eau de Parfum', 'floral'),

-- Acqua di Parma
('p241', 'Colonia', 'Acqua di Parma', 1916, 'unisex', 'Eau de Cologne', 'citrus'),
('p242', 'Colonia Essenza', 'Acqua di Parma', 2010, 'masculine', 'Eau de Cologne', 'citrus'),
('p243', 'Fico di Amalfi', 'Acqua di Parma', 2006, 'unisex', 'Eau de Toilette', 'citrus'),
('p244', 'Mandorlo di Sicilia', 'Acqua di Parma', 2014, 'unisex', 'Eau de Toilette', 'sweet'),
('p245', 'Quercia', 'Acqua di Parma', 2019, 'unisex', 'Eau de Parfum', 'woody'),

-- Arabic/Middle Eastern
('p246', 'Oud Touch', 'Franck Olivier', 2015, 'masculine', 'Eau de Parfum', 'oriental'),
('p247', 'Ahlam Al Arab', 'Ard Al Zaafaran', 2016, 'unisex', 'Eau de Parfum', 'oriental'),
('p248', 'Fakhar', 'Lattafa', 2018, 'masculine', 'Eau de Parfum', 'leather'),
('p249', 'Raghba', 'Lattafa', 2015, 'unisex', 'Eau de Parfum', 'vanilla'),
('p250', 'Asad', 'Lattafa', 2022, 'masculine', 'Eau de Parfum', 'spicy'),

-- More Niche
('p251', 'Oud Palao', 'Diptyque', 2015, 'unisex', 'Eau de Parfum', 'oriental'),
('p252', 'Vetyverio', 'Diptyque', 2012, 'unisex', 'Eau de Toilette', 'green'),
('p253', 'Fleur de Peau', 'Diptyque', 2019, 'unisex', 'Eau de Parfum', 'musky'),
('p254', 'Baie 19', 'Le Labo', 2019, 'unisex', 'Eau de Parfum', 'green'),
('p255', 'Gaiac 10', 'Le Labo', 2008, 'unisex', 'Eau de Parfum', 'smoky'),
('p256', 'Vetiver 46', 'Le Labo', 2006, 'unisex', 'Eau de Parfum', 'green'),
('p257', 'Mixed Emotions', 'Byredo', 2021, 'unisex', 'Eau de Parfum', 'aromatic'),
('p258', 'Sundazed', 'Byredo', 2019, 'unisex', 'Eau de Parfum', 'citrus'),
('p259', 'Slow Dance', 'Byredo', 2019, 'unisex', 'Eau de Parfum', 'oriental'),
('p260', 'Rose of No Man''s Land', 'Byredo', 2015, 'unisex', 'Eau de Parfum', 'floral'),

-- Memo Paris
('p261', 'African Leather', 'Memo Paris', 2013, 'unisex', 'Eau de Parfum', 'leather'),
('p262', 'Winter Palace', 'Memo Paris', 2015, 'unisex', 'Eau de Parfum', 'sweet'),
('p263', 'French Leather', 'Memo Paris', 2014, 'unisex', 'Eau de Parfum', 'leather'),
('p264', 'Sintra', 'Memo Paris', 2019, 'feminine', 'Eau de Parfum', 'floral'),
('p265', 'Marfa', 'Memo Paris', 2014, 'unisex', 'Eau de Parfum', 'woody'),

-- Montale
('p266', 'Intense Cafe', 'Montale', 2013, 'unisex', 'Eau de Parfum', 'sweet'),
('p267', 'Black Aoud', 'Montale', 2006, 'unisex', 'Eau de Parfum', 'woody'),
('p268', 'Chocolate Greedy', 'Montale', 2007, 'unisex', 'Eau de Parfum', 'sweet'),
('p269', 'Arabians Tonka', 'Montale', 2016, 'unisex', 'Eau de Parfum', 'oriental'),
('p270', 'Roses Musk', 'Montale', 2009, 'feminine', 'Eau de Parfum', 'floral'),

-- Serge Lutens
('p271', 'La Fille de Berlin', 'Serge Lutens', 2013, 'unisex', 'Eau de Parfum', 'floral'),
('p272', 'Ambre Sultan', 'Serge Lutens', 2000, 'unisex', 'Eau de Parfum', 'amber'),
('p273', 'Chergui', 'Serge Lutens', 2005, 'unisex', 'Eau de Parfum', 'oriental'),
('p274', 'Nuit de Cellophane', 'Serge Lutens', 2006, 'unisex', 'Eau de Parfum', 'floral'),
('p275', 'L''Orpheline', 'Serge Lutens', 2014, 'unisex', 'Eau de Parfum', 'woody'),

-- Guerlain Niche
('p276', 'L''Heure Bleue', 'Guerlain', 1912, 'feminine', 'Eau de Parfum', 'floral'),
('p277', 'Mitsouko', 'Guerlain', 1919, 'feminine', 'Eau de Parfum', 'oriental'),
('p278', 'Habit Rouge', 'Guerlain', 1965, 'masculine', 'Eau de Parfum', 'oriental'),
('p279', 'Vetiver', 'Guerlain', 1961, 'masculine', 'Eau de Toilette', 'green'),
('p280', 'L''Instant de Guerlain', 'Guerlain', 2003, 'masculine', 'Eau de Toilette', 'citrus'),

-- More 2020s releases
('p281', 'Y Le Parfum', 'Yves Saint Laurent', 2021, 'masculine', 'Eau de Parfum', 'aromatic'),
('p282', 'Luna Rossa Ocean', 'Prada', 2021, 'masculine', 'Eau de Toilette', 'aquatic'),
('p283', '1 Million Elixir', 'Paco Rabanne', 2022, 'masculine', 'Parfum', 'sweet'),
('p284', 'Eros Parfum', 'Versace', 2021, 'masculine', 'Parfum', 'aromatic'),
('p285', 'Code Parfum', 'Giorgio Armani', 2022, 'masculine', 'Parfum', 'aromatic'),
('p286', 'The Most Wanted Parfum', 'Azzaro', 2022, 'masculine', 'Parfum', 'spicy'),
('p287', 'Boss Bottled Parfum', 'Hugo Boss', 2022, 'masculine', 'Parfum', 'oriental'),
('p288', 'Spicebomb Infrared', 'Viktor & Rolf', 2021, 'masculine', 'Eau de Toilette', 'spicy'),
('p289', 'Gucci Guilty Pour Homme Parfum', 'Gucci', 2022, 'masculine', 'Parfum', 'aromatic'),
('p290', 'Explorer Ultra Blue', 'Montblanc', 2021, 'masculine', 'Eau de Parfum', 'aquatic'),

-- Women's 2020s
('p291', 'Good Girl Supreme', 'Carolina Herrera', 2020, 'feminine', 'Eau de Parfum', 'sweet'),
('p292', 'Paradoxe', 'Prada', 2022, 'feminine', 'Eau de Parfum', 'floral'),
('p293', 'Miss Dior Parfum', 'Dior', 2023, 'feminine', 'Parfum', 'floral'),
('p294', 'Libre Le Parfum', 'Yves Saint Laurent', 2022, 'feminine', 'Parfum', 'floral'),
('p295', 'My Way Parfum', 'Giorgio Armani', 2022, 'feminine', 'Parfum', 'floral'),
('p296', 'Chance Eau de Parfum', 'Chanel', 2022, 'feminine', 'Eau de Parfum', 'floral'),
('p297', 'Joy Intense', 'Dior', 2019, 'feminine', 'Eau de Parfum Intense', 'floral'),
('p298', 'Coco Noir', 'Chanel', 2012, 'feminine', 'Eau de Parfum', 'oriental'),
('p299', 'N°5 L''Eau', 'Chanel', 2016, 'feminine', 'Eau de Toilette', 'floral'),
('p300', 'Gabrielle Essence', 'Chanel', 2019, 'feminine', 'Eau de Parfum', 'floral'),

-- Classic Legends
('p301', 'Eau Sauvage', 'Dior', 1966, 'masculine', 'Eau de Toilette', 'citrus'),
('p302', 'Pour Monsieur', 'Chanel', 1955, 'masculine', 'Eau de Toilette', 'citrus'),
('p303', 'Aramis', 'Aramis', 1966, 'masculine', 'Eau de Toilette', 'aromatic'),
('p304', 'Brut', 'Fabergé', 1964, 'masculine', 'Eau de Cologne', 'aromatic'),
('p305', 'Old Spice', 'Shulton', 1937, 'masculine', 'Eau de Cologne', 'oriental'),
('p306', 'Jicky', 'Guerlain', 1889, 'unisex', 'Eau de Parfum', 'aromatic'),
('p307', 'Chanel No. 19', 'Chanel', 1970, 'feminine', 'Eau de Parfum', 'green'),
('p308', 'Rive Gauche', 'Yves Saint Laurent', 1970, 'feminine', 'Eau de Toilette', 'floral'),
('p309', 'Poison', 'Dior', 1985, 'feminine', 'Eau de Toilette', 'oriental'),
('p310', 'Joy', 'Jean Patou', 1930, 'feminine', 'Eau de Parfum', 'floral'),

-- More Amouage
('p311', 'Lyric Man', 'Amouage', 2008, 'masculine', 'Eau de Parfum', 'floral'),
('p312', 'Dia Man', 'Amouage', 2002, 'masculine', 'Eau de Parfum', 'floral'),
('p313', 'Epic Man', 'Amouage', 2009, 'masculine', 'Eau de Parfum', 'spicy'),
('p314', 'Gold Man', 'Amouage', 1983, 'masculine', 'Eau de Parfum', 'oriental'),
('p315', 'Honour Woman', 'Amouage', 2011, 'feminine', 'Eau de Parfum', 'floral'),

-- Penhaligon's
('p316', 'Sartorial', 'Penhaligon''s', 2010, 'masculine', 'Eau de Toilette', 'aromatic'),
('p317', 'Endymion', 'Penhaligon''s', 2003, 'masculine', 'Cologne', 'aromatic'),
('p318', 'Blenheim Bouquet', 'Penhaligon''s', 1902, 'masculine', 'Eau de Toilette', 'citrus'),
('p319', 'The Tragedy of Lord George', 'Penhaligon''s', 2016, 'masculine', 'Eau de Parfum', 'amber'),
('p320', 'Empressa', 'Penhaligon''s', 2016, 'feminine', 'Eau de Parfum', 'floral'),

-- MFK extras
('p321', 'Aqua Universalis', 'Maison Francis Kurkdjian', 2009, 'unisex', 'Eau de Toilette', 'citrus'),
('p322', 'Petit Matin', 'Maison Francis Kurkdjian', 2016, 'unisex', 'Eau de Parfum', 'citrus'),
('p323', 'Amyris Homme', 'Maison Francis Kurkdjian', 2012, 'masculine', 'Extrait de Parfum', 'woody'),
('p324', 'À la rose', 'Maison Francis Kurkdjian', 2014, 'feminine', 'Eau de Parfum', 'floral'),
('p325', 'L''Homme À la Rose', 'Maison Francis Kurkdjian', 2021, 'masculine', 'Eau de Parfum', 'floral'),

-- Nishane extras
('p326', 'Hundred Silent Ways', 'Nishane', 2017, 'unisex', 'Extrait de Parfum', 'floral'),
('p327', 'Sultan Vetiver', 'Nishane', 2012, 'unisex', 'Extrait de Parfum', 'green'),
('p328', 'Wulong Cha', 'Nishane', 2017, 'unisex', 'Extrait de Parfum', 'citrus'),
('p329', 'Tempfluo', 'Nishane', 2020, 'unisex', 'Extrait de Parfum', 'sweet'),
('p330', 'Vain & Naïve', 'Nishane', 2019, 'unisex', 'Extrait de Parfum', 'citrus'),

-- Initio extras
('p331', 'Musk Therapy', 'Initio', 2015, 'unisex', 'Eau de Parfum', 'musky'),
('p332', 'Blessed Baraka', 'Initio', 2015, 'unisex', 'Eau de Parfum', 'woody'),
('p333', 'Absolute Aphrodisiac', 'Initio', 2015, 'unisex', 'Eau de Parfum', 'oriental'),
('p334', 'Addictive Vibration', 'Initio', 2017, 'feminine', 'Eau de Parfum', 'sweet'),
('p335', 'Psychedelic Love', 'Initio', 2019, 'unisex', 'Eau de Parfum', 'floral'),

-- PDM extras
('p336', 'Kalan', 'Parfums de Marly', 2019, 'masculine', 'Eau de Parfum', 'spicy'),
('p337', 'Greenley', 'Parfums de Marly', 2020, 'masculine', 'Eau de Parfum', 'citrus'),
('p338', 'Althair', 'Parfums de Marly', 2021, 'masculine', 'Eau de Parfum', 'sweet'),
('p339', 'Oriana', 'Parfums de Marly', 2021, 'feminine', 'Eau de Parfum', 'fruity'),
('p340', 'Cassili', 'Parfums de Marly', 2019, 'feminine', 'Eau de Parfum', 'floral'),

-- More Jo Malone
('p341', 'Blackberry & Bay', 'Jo Malone', 2012, 'unisex', 'Cologne', 'fruity'),
('p342', 'Myrrh & Tonka', 'Jo Malone', 2017, 'unisex', 'Cologne Intense', 'oriental'),
('p343', 'Velvet Rose & Oud', 'Jo Malone', 2012, 'unisex', 'Cologne Intense', 'floral'),
('p344', 'Oud & Bergamot', 'Jo Malone', 2010, 'unisex', 'Cologne Intense', 'woody'),
('p345', 'Wild Bluebell', 'Jo Malone', 2011, 'feminine', 'Cologne', 'floral'),

-- Hermès
('p346', 'Hermès H24', 'Hermès', 2021, 'masculine', 'Eau de Toilette', 'aromatic'),
('p347', 'Un Jardin sur le Nil', 'Hermès', 2005, 'unisex', 'Eau de Toilette', 'green'),
('p348', 'Voyage d''Hermès', 'Hermès', 2010, 'unisex', 'Eau de Toilette', 'woody'),
('p349', 'Twilly d''Hermès', 'Hermès', 2017, 'feminine', 'Eau de Parfum', 'floral'),
('p350', 'Un Jardin en Méditerranée', 'Hermès', 2003, 'unisex', 'Eau de Toilette', 'green'),

-- Budget Friendly Gems
('p351', 'Nautica Voyage', 'Nautica', 2006, 'masculine', 'Eau de Toilette', 'aquatic'),
('p352', 'Versace Man', 'Versace', 2003, 'masculine', 'Eau de Toilette', 'amber'),
('p353', 'Montblanc Legend', 'Montblanc', 2011, 'masculine', 'Eau de Toilette', 'aromatic'),
('p354', 'David Beckham Instinct', 'David Beckham', 2005, 'masculine', 'Eau de Toilette', 'fresh'),
('p355', 'Joop! Homme', 'Joop!', 1989, 'masculine', 'Eau de Toilette', 'oriental'),
('p356', 'Dunhill Icon', 'Alfred Dunhill', 2015, 'masculine', 'Eau de Parfum', 'aromatic'),
('p357', 'Perry Ellis 360', 'Perry Ellis', 1993, 'masculine', 'Eau de Toilette', 'fresh'),
('p358', 'Bentley for Men Intense', 'Bentley', 2013, 'masculine', 'Eau de Parfum', 'woody'),
('p359', 'Encre Noire', 'Lalique', 2006, 'masculine', 'Eau de Toilette', 'woody'),
('p360', 'L''Aventure', 'Al Haramain', 2016, 'masculine', 'Eau de Parfum', 'fruity'),

-- Women's Budget/Mid
('p361', 'Si Passione', 'Giorgio Armani', 2018, 'feminine', 'Eau de Parfum', 'floral'),
('p362', 'Daisy Dream', 'Marc Jacobs', 2014, 'feminine', 'Eau de Toilette', 'fruity'),
('p363', 'Gucci Rush', 'Gucci', 1999, 'feminine', 'Eau de Toilette', 'floral'),
('p364', 'Coco', 'Chanel', 1984, 'feminine', 'Eau de Parfum', 'oriental'),
('p365', 'Allure', 'Chanel', 1996, 'feminine', 'Eau de Parfum', 'floral'),
('p366', 'Cool Water Woman', 'Davidoff', 1996, 'feminine', 'Eau de Toilette', 'floral'),
('p367', 'J''adore L''Or', 'Dior', 2017, 'feminine', 'Parfum', 'floral'),
('p368', 'Tresor', 'Lancôme', 1990, 'feminine', 'Eau de Parfum', 'oriental'),
('p369', 'Miracle', 'Lancôme', 2000, 'feminine', 'Eau de Parfum', 'fresh'),
('p370', 'Amor Amor', 'Cacharel', 2003, 'feminine', 'Eau de Toilette', 'fruity'),

-- More Niche 2
('p371', 'Portrait of a Lady', 'Frederic Malle', 2010, 'feminine', 'Eau de Parfum', 'floral'),
('p372', 'Musc Ravageur', 'Frederic Malle', 2000, 'unisex', 'Eau de Parfum', 'musky'),
('p373', 'Carnal Flower', 'Frederic Malle', 2005, 'unisex', 'Eau de Parfum', 'floral'),
('p374', 'Aventus Cologne', 'Creed', 2019, 'masculine', 'Eau de Parfum', 'citrus'),
('p375', 'Viking', 'Creed', 2017, 'masculine', 'Eau de Parfum', 'spicy'),
('p376', 'Wind Flowers', 'Creed', 2021, 'feminine', 'Eau de Parfum', 'floral'),
('p377', 'Royal Princess Oud', 'Creed', 2015, 'feminine', 'Eau de Parfum', 'floral'),
('p378', 'Italian Cypress', 'Tom Ford', 2007, 'unisex', 'Eau de Parfum', 'green'),
('p379', 'Costa Azzurra', 'Tom Ford', 2014, 'unisex', 'Eau de Parfum', 'aquatic'),
('p380', 'Plum Japonais', 'Tom Ford', 2013, 'unisex', 'Eau de Parfum', 'fruity'),

-- Commodity
('p381', 'Commodity Gold', 'Commodity', 2014, 'unisex', 'Eau de Parfum', 'sweet'),
('p382', 'Commodity Book', 'Commodity', 2017, 'unisex', 'Eau de Parfum', 'woody'),
('p383', 'Commodity Velvet', 'Commodity', 2019, 'unisex', 'Eau de Parfum', 'oriental'),
('p384', 'Commodity Milk', 'Commodity', 2017, 'unisex', 'Eau de Parfum', 'musky'),
('p385', 'Commodity Bergamot', 'Commodity', 2020, 'unisex', 'Eau de Parfum', 'citrus'),

-- Zadig & Voltaire, Prada Women
('p386', 'This is Him!', 'Zadig & Voltaire', 2016, 'masculine', 'Eau de Toilette', 'oriental'),
('p387', 'This is Her!', 'Zadig & Voltaire', 2016, 'feminine', 'Eau de Parfum', 'sweet'),
('p388', 'Candy', 'Prada', 2011, 'feminine', 'Eau de Parfum', 'sweet'),
('p389', 'La Femme', 'Prada', 2016, 'feminine', 'Eau de Parfum', 'floral'),
('p390', 'Infusion d''Iris', 'Prada', 2007, 'feminine', 'Eau de Parfum', 'floral'),

-- Miscellaneous
('p391', 'CK Obsession', 'Calvin Klein', 1985, 'feminine', 'Eau de Parfum', 'oriental'),
('p392', 'CK Be', 'Calvin Klein', 1996, 'unisex', 'Eau de Toilette', 'musky'),
('p393', 'Bvlgari Man in Black', 'Bvlgari', 2014, 'masculine', 'Eau de Parfum', 'oriental'),
('p394', 'Bvlgari Aqva', 'Bvlgari', 2005, 'masculine', 'Eau de Toilette', 'aquatic'),
('p395', 'Bvlgari Pour Femme', 'Bvlgari', 1994, 'feminine', 'Eau de Parfum', 'floral'),
('p396', 'Jasmin Rouge', 'Tom Ford', 2011, 'unisex', 'Eau de Parfum', 'floral'),
('p397', 'Santal Royal', 'Guerlain', 2016, 'unisex', 'Eau de Parfum', 'woody'),
('p398', 'L''Art et la Matière Cuir Beluga', 'Guerlain', 2005, 'unisex', 'Eau de Parfum', 'leather'),
('p399', 'Oud Essentiel', 'Guerlain', 2017, 'unisex', 'Eau de Parfum', 'woody'),
('p400', 'Musc Noble', 'Guerlain', 2013, 'unisex', 'Eau de Parfum', 'musky'),

-- More recent niche
('p401', 'Not a Perfume Superdose', 'Juliette Has A Gun', 2020, 'unisex', 'Eau de Parfum', 'musky'),
('p402', 'Vanilla Vibes', 'Juliette Has A Gun', 2018, 'unisex', 'Eau de Parfum', 'vanilla'),
('p403', 'Lady Vengeance', 'Juliette Has A Gun', 2006, 'feminine', 'Eau de Parfum', 'floral'),
('p404', 'Moscow Mule', 'Juliette Has A Gun', 2017, 'unisex', 'Eau de Parfum', 'citrus'),
('p405', 'Sunny Side Up', 'Juliette Has A Gun', 2019, 'feminine', 'Eau de Parfum', 'floral'),
('p406', 'Escentric 02', 'Escentric Molecules', 2008, 'unisex', 'Eau de Toilette', 'woody'),
('p407', 'Molecule 02', 'Escentric Molecules', 2008, 'unisex', 'Eau de Toilette', 'musky'),
('p408', 'Molecule 03', 'Escentric Molecules', 2010, 'unisex', 'Eau de Toilette', 'woody'),
('p409', 'Tauer L''Air du Désert Marocain', 'Tauer Perfumes', 2005, 'unisex', 'Eau de Toilette', 'oriental'),
('p410', 'Imaginary Authors Saint Julep', 'Imaginary Authors', 2016, 'unisex', 'Eau de Parfum', 'fresh'),

-- Versace collection
('p411', 'Eros Pour Femme', 'Versace', 2014, 'feminine', 'Eau de Parfum', 'floral'),
('p412', 'Yellow Diamond', 'Versace', 2011, 'feminine', 'Eau de Toilette', 'floral'),
('p413', 'The Dreamer', 'Versace', 1996, 'masculine', 'Eau de Toilette', 'aromatic'),
('p414', 'Blue Jeans', 'Versace', 1994, 'masculine', 'Eau de Toilette', 'aromatic'),
('p415', 'Medusa', 'Versace', 2023, 'masculine', 'Eau de Parfum', 'aromatic'),

-- D&G collection
('p416', 'K by Dolce & Gabbana', 'Dolce & Gabbana', 2019, 'masculine', 'Eau de Parfum', 'aromatic'),
('p417', 'The Only One', 'Dolce & Gabbana', 2018, 'feminine', 'Eau de Parfum', 'sweet'),
('p418', 'Devotion', 'Dolce & Gabbana', 2022, 'feminine', 'Eau de Parfum', 'sweet'),
('p419', 'Pour Homme', 'Dolce & Gabbana', 1994, 'masculine', 'Eau de Toilette', 'aromatic'),
('p420', 'The One for Her', 'Dolce & Gabbana', 2006, 'feminine', 'Eau de Parfum', 'floral'),

-- Givenchy
('p421', 'Irresistible', 'Givenchy', 2020, 'feminine', 'Eau de Parfum', 'floral'),
('p422', 'L''Interdit Rouge', 'Givenchy', 2021, 'feminine', 'Eau de Parfum', 'floral'),
('p423', 'Gentleman Boisée', 'Givenchy', 2020, 'masculine', 'Eau de Parfum', 'woody'),
('p424', 'Ange ou Démon', 'Givenchy', 2006, 'feminine', 'Eau de Parfum', 'oriental'),
('p425', 'Very Irrésistible', 'Givenchy', 2003, 'feminine', 'Eau de Toilette', 'floral'),

-- Narciso Rodriguez
('p426', 'For Her', 'Narciso Rodriguez', 2003, 'feminine', 'Eau de Toilette', 'musky'),
('p427', 'For Her Musc Noir', 'Narciso Rodriguez', 2021, 'feminine', 'Eau de Parfum', 'musky'),
('p428', 'Bleu Noir', 'Narciso Rodriguez', 2018, 'masculine', 'Eau de Parfum', 'woody'),
('p429', 'Pure Musc', 'Narciso Rodriguez', 2019, 'feminine', 'Eau de Parfum', 'musky'),
('p430', 'All of Me', 'Narciso Rodriguez', 2023, 'feminine', 'Eau de Parfum', 'musky'),

-- Issey Miyake
('p431', 'L''Eau d''Issey Pour Femme', 'Issey Miyake', 1992, 'feminine', 'Eau de Toilette', 'aquatic'),
('p432', 'Nuit d''Issey', 'Issey Miyake', 2014, 'masculine', 'Eau de Toilette', 'leather'),
('p433', 'L''Eau Majeure d''Issey', 'Issey Miyake', 2017, 'masculine', 'Eau de Toilette', 'aquatic'),
('p434', 'A Drop d''Issey', 'Issey Miyake', 2021, 'feminine', 'Eau de Parfum', 'floral'),
('p435', 'Fusion d''Issey', 'Issey Miyake', 2020, 'masculine', 'Eau de Toilette', 'aromatic'),

-- Misc niche
('p436', 'Angels'' Share', 'Kilian', 2020, 'unisex', 'Eau de Parfum', 'sweet'),
('p437', 'Apple Brandy on the Rocks', 'Kilian', 2021, 'unisex', 'Eau de Parfum', 'sweet'),
('p438', 'Princess', 'Kilian', 2021, 'feminine', 'Eau de Parfum', 'sweet'),
('p439', 'Vodka on the Rocks', 'Kilian', 2014, 'masculine', 'Eau de Parfum', 'fresh'),
('p440', 'Black Phantom', 'Kilian', 2017, 'unisex', 'Eau de Parfum', 'sweet'),

-- Final batch
('p441', 'Interlude Man Iris', 'Amouage', 2020, 'masculine', 'Eau de Parfum', 'floral'),
('p442', 'Beach Hut Man', 'Amouage', 2017, 'masculine', 'Eau de Parfum', 'citrus'),
('p443', 'Enclave', 'Amouage', 2022, 'masculine', 'Eau de Parfum', 'woody'),
('p444', 'Sunshine Man', 'Amouage', 2014, 'masculine', 'Eau de Parfum', 'sweet'),
('p445', 'Figment Man', 'Amouage', 2017, 'masculine', 'Eau de Parfum', 'aromatic'),
('p446', 'Oud Minerale', 'Tom Ford', 2017, 'unisex', 'Eau de Parfum', 'aquatic'),
('p447', 'Noir Extreme', 'Tom Ford', 2015, 'masculine', 'Eau de Parfum', 'oriental'),
('p448', 'Beau de Jour', 'Tom Ford', 2019, 'masculine', 'Eau de Parfum', 'aromatic'),
('p449', 'Metallique', 'Tom Ford', 2019, 'feminine', 'Eau de Parfum', 'floral'),
('p450', 'Ebene Fumé', 'Tom Ford', 2020, 'unisex', 'Eau de Parfum', 'woody'),
('p451', 'Jazz Club', 'Maison Margiela', 2013, 'masculine', 'Eau de Toilette', 'smoky'),
('p452', 'Soul of the Forest', 'Maison Margiela', 2021, 'unisex', 'Eau de Parfum', 'woody'),
('p453', 'Whispers in the Library', 'Maison Margiela', 2019, 'unisex', 'Eau de Toilette', 'woody'),
('p454', 'Under the Lemon Trees', 'Maison Margiela', 2021, 'unisex', 'Eau de Toilette', 'citrus'),
('p455', 'Springtime in a Park', 'Maison Margiela', 2019, 'unisex', 'Eau de Toilette', 'green'),
('p456', 'Intense Oud', 'Mancera', 2012, 'unisex', 'Eau de Parfum', 'oriental'),
('p457', 'Roses Vanille', 'Mancera', 2011, 'unisex', 'Eau de Parfum', 'sweet'),
('p458', 'Aoud Blue Notes', 'Mancera', 2014, 'unisex', 'Eau de Parfum', 'aromatic'),
('p459', 'Sicilian Leather', 'Memo Paris', 2016, 'unisex', 'Eau de Parfum', 'leather'),
('p460', 'Inlé', 'Memo Paris', 2007, 'unisex', 'Eau de Parfum', 'aquatic'),
('p461', 'Scandal Pour Homme Le Parfum', 'Jean Paul Gaultier', 2022, 'masculine', 'Parfum', 'oriental'),
('p462', 'La Belle', 'Jean Paul Gaultier', 2019, 'feminine', 'Eau de Parfum', 'sweet'),
('p463', 'Scandal', 'Jean Paul Gaultier', 2017, 'feminine', 'Eau de Parfum', 'sweet'),
('p464', 'Classique', 'Jean Paul Gaultier', 1993, 'feminine', 'Eau de Toilette', 'floral'),
('p465', 'Invictus Victory', 'Paco Rabanne', 2021, 'masculine', 'Eau de Parfum Extreme', 'aromatic'),
('p466', 'Fame', 'Paco Rabanne', 2022, 'feminine', 'Eau de Parfum', 'sweet'),
('p467', 'Lady Million', 'Paco Rabanne', 2010, 'feminine', 'Eau de Parfum', 'floral'),
('p468', 'Pure XS', 'Paco Rabanne', 2017, 'masculine', 'Eau de Toilette', 'oriental'),
('p469', 'Luna Rossa Black', 'Prada', 2018, 'masculine', 'Eau de Parfum', 'oriental'),
('p470', 'L''Homme Prada', 'Prada', 2016, 'masculine', 'Eau de Toilette', 'amber'),
('p471', 'Mugler Cologne', 'Mugler', 2001, 'unisex', 'Eau de Toilette', 'citrus'),
('p472', 'A*Men', 'Mugler', 1996, 'masculine', 'Eau de Toilette', 'sweet'),
('p473', 'Womanity', 'Mugler', 2010, 'feminine', 'Eau de Parfum', 'sweet'),
('p474', 'Angel Nova', 'Mugler', 2020, 'feminine', 'Eau de Parfum', 'floral'),
('p475', 'Aura', 'Mugler', 2017, 'feminine', 'Eau de Parfum', 'green'),
('p476', 'London', 'Burberry', 1995, 'feminine', 'Eau de Parfum', 'floral'),
('p477', 'Brit', 'Burberry', 2003, 'feminine', 'Eau de Parfum', 'sweet'),
('p478', 'My Burberry', 'Burberry', 2014, 'feminine', 'Eau de Parfum', 'floral'),
('p479', 'Weekend', 'Burberry', 1997, 'feminine', 'Eau de Parfum', 'floral'),
('p480', 'Touch', 'Burberry', 2000, 'feminine', 'Eau de Parfum', 'floral'),
('p481', 'Uomo', 'Valentino', 2018, 'masculine', 'Eau de Toilette', 'leather'),
('p482', 'CH', 'Carolina Herrera', 2007, 'feminine', 'Eau de Toilette', 'floral'),
('p483', '212 VIP', 'Carolina Herrera', 2010, 'feminine', 'Eau de Parfum', 'floral'),
('p484', '212 Men', 'Carolina Herrera', 1999, 'masculine', 'Eau de Toilette', 'aromatic'),
('p485', 'English Laundry Oxford Bleu', 'English Laundry', 2013, 'masculine', 'Eau de Parfum', 'fresh'),
('p486', 'Yardley English Lavender', 'Yardley', 1913, 'unisex', 'Eau de Toilette', 'aromatic'),
('p487', 'Dior Addict', 'Dior', 2002, 'feminine', 'Eau de Parfum', 'oriental'),
('p488', 'J''adore Infinissime', 'Dior', 2020, 'feminine', 'Eau de Parfum', 'floral'),
('p489', 'Sauvage Very Cool Spray', 'Dior', 2017, 'masculine', 'Eau de Toilette', 'fresh'),
('p490', 'Rouge Trafalgar', 'Dior', 2020, 'feminine', 'Eau de Parfum', 'fruity'),
('p491', 'Oud Rosewood', 'Dior', 2012, 'unisex', 'Eau de Parfum', 'woody'),
('p492', 'Intense', 'Dolce & Gabbana', 2020, 'feminine', 'Eau de Parfum', 'floral'),
('p493', 'L''Imperatrice', 'Dolce & Gabbana', 2009, 'feminine', 'Eau de Toilette', 'fruity'),
('p494', 'Code Absolu', 'Giorgio Armani', 2019, 'masculine', 'Parfum', 'oriental'),
('p495', 'Si Fiori', 'Giorgio Armani', 2019, 'feminine', 'Eau de Parfum', 'floral'),
('p496', 'Acqua di Gio Profondo', 'Giorgio Armani', 2020, 'masculine', 'Eau de Parfum', 'aquatic'),
('p497', 'Emporio Armani In Love With You', 'Giorgio Armani', 2018, 'feminine', 'Eau de Parfum', 'sweet'),
('p498', 'BR540 Extrait', 'Maison Francis Kurkdjian', 2017, 'unisex', 'Extrait de Parfum', 'amber'),
('p499', 'Dulcis in Fundo', 'Nishane', 2019, 'unisex', 'Extrait de Parfum', 'sweet'),
('p500', 'Xerjoff Nio', 'Xerjoff', 2010, 'masculine', 'Eau de Parfum', 'citrus');
