-- Migration 019: Scent Compass - adds positioning scores for 2D fragrance map
-- fresh_warm_score: 0 = fresh, 1 = warm/spicy
-- light_heavy_score: 0 = light, 1 = heavy/intense

ALTER TABLE perfumes ADD COLUMN fresh_warm_score REAL;
ALTER TABLE perfumes ADD COLUMN light_heavy_score REAL;

-- Seed compass scores for the original 50 perfumes (p001-p050)
-- Men's Classics
UPDATE perfumes SET fresh_warm_score = 0.35, light_heavy_score = 0.50 WHERE id = 'p001'; -- Sauvage (moderately fresh, medium weight)
UPDATE perfumes SET fresh_warm_score = 0.30, light_heavy_score = 0.45 WHERE id = 'p002'; -- Bleu de Chanel (fresh-leaning, medium)
UPDATE perfumes SET fresh_warm_score = 0.25, light_heavy_score = 0.55 WHERE id = 'p003'; -- Aventus (fresh fruity, slightly heavy)
UPDATE perfumes SET fresh_warm_score = 0.10, light_heavy_score = 0.15 WHERE id = 'p004'; -- Acqua di Gio (very fresh, very light)
UPDATE perfumes SET fresh_warm_score = 0.70, light_heavy_score = 0.55 WHERE id = 'p005'; -- La Nuit de L'Homme (warm spicy, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.40, light_heavy_score = 0.50 WHERE id = 'p006'; -- Eros (balanced, medium)
UPDATE perfumes SET fresh_warm_score = 0.65, light_heavy_score = 0.55 WHERE id = 'p007'; -- The One (warm, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.20, light_heavy_score = 0.35 WHERE id = 'p008'; -- Invictus (fresh, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.30, light_heavy_score = 0.45 WHERE id = 'p009'; -- Dylan Blue (fresh, medium)
UPDATE perfumes SET fresh_warm_score = 0.35, light_heavy_score = 0.45 WHERE id = 'p010'; -- Y EDP (slightly fresh, medium)

-- Men's Niche
UPDATE perfumes SET fresh_warm_score = 0.75, light_heavy_score = 0.80 WHERE id = 'p011'; -- Baccarat Rouge 540 (warm amber, heavy)
UPDATE perfumes SET fresh_warm_score = 0.60, light_heavy_score = 0.70 WHERE id = 'p012'; -- Oud Wood (warm woody, heavy)
UPDATE perfumes SET fresh_warm_score = 0.85, light_heavy_score = 0.90 WHERE id = 'p013'; -- Tobacco Vanille (very warm, very heavy)
UPDATE perfumes SET fresh_warm_score = 0.65, light_heavy_score = 0.65 WHERE id = 'p014'; -- Layton (warm spicy, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.20, light_heavy_score = 0.60 WHERE id = 'p015'; -- Hacivat (fresh fruity, medium-heavy projection)
UPDATE perfumes SET fresh_warm_score = 0.15, light_heavy_score = 0.40 WHERE id = 'p016'; -- Green Irish Tweed (very fresh green, medium)
UPDATE perfumes SET fresh_warm_score = 0.10, light_heavy_score = 0.30 WHERE id = 'p017'; -- Silver Mountain Water (very fresh, light)
UPDATE perfumes SET fresh_warm_score = 0.80, light_heavy_score = 0.90 WHERE id = 'p018'; -- Interlude Man (very warm smoky, very heavy)
UPDATE perfumes SET fresh_warm_score = 0.80, light_heavy_score = 0.75 WHERE id = 'p019'; -- Grand Soir (warm amber, heavy)
UPDATE perfumes SET fresh_warm_score = 0.75, light_heavy_score = 0.70 WHERE id = 'p020'; -- Herod (warm spicy, heavy)

-- Women's Classics
UPDATE perfumes SET fresh_warm_score = 0.40, light_heavy_score = 0.40 WHERE id = 'p021'; -- J'adore (balanced floral, medium)
UPDATE perfumes SET fresh_warm_score = 0.30, light_heavy_score = 0.45 WHERE id = 'p022'; -- Coco Mademoiselle (fresh floral, medium)
UPDATE perfumes SET fresh_warm_score = 0.60, light_heavy_score = 0.55 WHERE id = 'p023'; -- La Vie Est Belle (sweet warm, medium)
UPDATE perfumes SET fresh_warm_score = 0.70, light_heavy_score = 0.65 WHERE id = 'p024'; -- Black Opium (warm sweet, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.65, light_heavy_score = 0.60 WHERE id = 'p025'; -- Good Girl (warm sweet, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.35, light_heavy_score = 0.40 WHERE id = 'p026'; -- Si (slightly fresh, medium)
UPDATE perfumes SET fresh_warm_score = 0.20, light_heavy_score = 0.25 WHERE id = 'p027'; -- Chance Eau Tendre (fresh, light)
UPDATE perfumes SET fresh_warm_score = 0.55, light_heavy_score = 0.55 WHERE id = 'p028'; -- Flowerbomb (warm floral, medium)
UPDATE perfumes SET fresh_warm_score = 0.30, light_heavy_score = 0.35 WHERE id = 'p029'; -- Miss Dior (fresh floral, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.05, light_heavy_score = 0.10 WHERE id = 'p030'; -- Light Blue (very fresh citrus, very light)

-- Women's Niche
UPDATE perfumes SET fresh_warm_score = 0.45, light_heavy_score = 0.50 WHERE id = 'p031'; -- Delina (balanced floral, medium)
UPDATE perfumes SET fresh_warm_score = 0.65, light_heavy_score = 0.65 WHERE id = 'p032'; -- Lost Cherry (warm fruity, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.40, light_heavy_score = 0.15 WHERE id = 'p033'; -- Not a Perfume (balanced, very light skin scent)
UPDATE perfumes SET fresh_warm_score = 0.55, light_heavy_score = 0.75 WHERE id = 'p034'; -- Alien (warm woody, heavy)
UPDATE perfumes SET fresh_warm_score = 0.50, light_heavy_score = 0.50 WHERE id = 'p035'; -- Mon Guerlain (balanced, medium)

-- Unisex Favorites
UPDATE perfumes SET fresh_warm_score = 0.55, light_heavy_score = 0.60 WHERE id = 'p036'; -- Santal 33 (warm woody, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.35, light_heavy_score = 0.30 WHERE id = 'p037'; -- Another 13 (balanced musky, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.30, light_heavy_score = 0.20 WHERE id = 'p038'; -- Molecule 01 (neutral, light)
UPDATE perfumes SET fresh_warm_score = 0.40, light_heavy_score = 0.45 WHERE id = 'p039'; -- Bal d'Afrique (balanced, medium)
UPDATE perfumes SET fresh_warm_score = 0.35, light_heavy_score = 0.40 WHERE id = 'p040'; -- Gypsy Water (slightly fresh, medium)

-- Fresh & Summer
UPDATE perfumes SET fresh_warm_score = 0.15, light_heavy_score = 0.35 WHERE id = 'p041'; -- Acqua di Gio Profumo (fresh, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.05, light_heavy_score = 0.20 WHERE id = 'p042'; -- Cool Water (very fresh, light)
UPDATE perfumes SET fresh_warm_score = 0.05, light_heavy_score = 0.10 WHERE id = 'p043'; -- CK One (very fresh citrus, very light)
UPDATE perfumes SET fresh_warm_score = 0.10, light_heavy_score = 0.25 WHERE id = 'p044'; -- Neroli Portofino (fresh citrus, light)
UPDATE perfumes SET fresh_warm_score = 0.10, light_heavy_score = 0.30 WHERE id = 'p045'; -- Aventus Cologne (fresh citrus, light-medium)

-- Oriental & Evening
UPDATE perfumes SET fresh_warm_score = 0.80, light_heavy_score = 0.70 WHERE id = 'p046'; -- Spicebomb (very warm spicy, heavy)
UPDATE perfumes SET fresh_warm_score = 0.75, light_heavy_score = 0.65 WHERE id = 'p047'; -- Wanted by Night (warm spicy, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.70, light_heavy_score = 0.60 WHERE id = 'p048'; -- Ultra Male (warm sweet, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.85, light_heavy_score = 0.85 WHERE id = 'p049'; -- Tuscan Leather (very warm, very heavy)
UPDATE perfumes SET fresh_warm_score = 0.90, light_heavy_score = 0.80 WHERE id = 'p050'; -- By the Fireplace (very warm smoky, heavy)

-- Seed compass scores for selected perfumes from the 500-seed batch
-- Chanel & Dior (s001-s020)
UPDATE perfumes SET fresh_warm_score = 0.55, light_heavy_score = 0.65 WHERE id = 's001'; -- No. 5 (warm aldehydic, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.40, light_heavy_score = 0.45 WHERE id = 's002'; -- Chance (balanced, medium)
UPDATE perfumes SET fresh_warm_score = 0.15, light_heavy_score = 0.30 WHERE id = 's003'; -- Allure Homme Sport (fresh, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.65, light_heavy_score = 0.65 WHERE id = 's004'; -- Coco Noir (warm oriental, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.30, light_heavy_score = 0.35 WHERE id = 's005'; -- Gabrielle (fresh floral, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.20, light_heavy_score = 0.30 WHERE id = 's006'; -- Platinum Egoiste (fresh herbal, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.15, light_heavy_score = 0.20 WHERE id = 's007'; -- Chance Eau Fraiche (very fresh, light)
UPDATE perfumes SET fresh_warm_score = 0.60, light_heavy_score = 0.55 WHERE id = 's008'; -- Allure Sensuelle (warm, medium)
UPDATE perfumes SET fresh_warm_score = 0.20, light_heavy_score = 0.45 WHERE id = 's009'; -- No. 19 (fresh green, medium)
UPDATE perfumes SET fresh_warm_score = 0.15, light_heavy_score = 0.30 WHERE id = 's010'; -- Pour Monsieur (fresh citrus, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.45, light_heavy_score = 0.60 WHERE id = 's011'; -- Sauvage EDP (balanced, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.70, light_heavy_score = 0.70 WHERE id = 's012'; -- Fahrenheit (warm, heavy)
UPDATE perfumes SET fresh_warm_score = 0.10, light_heavy_score = 0.25 WHERE id = 's013'; -- Eau Sauvage (very fresh, light)
UPDATE perfumes SET fresh_warm_score = 0.80, light_heavy_score = 0.85 WHERE id = 's014'; -- Poison (very warm, very heavy)
UPDATE perfumes SET fresh_warm_score = 0.70, light_heavy_score = 0.60 WHERE id = 's015'; -- Hypnotic Poison (warm vanilla, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.30, light_heavy_score = 0.30 WHERE id = 's016'; -- Joy (fresh floral, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.45, light_heavy_score = 0.50 WHERE id = 's017'; -- Dior Homme (balanced iris, medium)
UPDATE perfumes SET fresh_warm_score = 0.50, light_heavy_score = 0.60 WHERE id = 's018'; -- Dior Homme Intense (balanced, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.20, light_heavy_score = 0.15 WHERE id = 's019'; -- Miss Dior Blooming Bouquet (fresh, very light)
UPDATE perfumes SET fresh_warm_score = 0.65, light_heavy_score = 0.60 WHERE id = 's020'; -- Dior Addict (warm, medium-heavy)

-- Tom Ford (s021-s040)
UPDATE perfumes SET fresh_warm_score = 0.75, light_heavy_score = 0.85 WHERE id = 's021'; -- Black Orchid (warm dark, very heavy)
UPDATE perfumes SET fresh_warm_score = 0.60, light_heavy_score = 0.70 WHERE id = 's022'; -- Fucking Fabulous (warm leather, heavy)
UPDATE perfumes SET fresh_warm_score = 0.70, light_heavy_score = 0.70 WHERE id = 's023'; -- Bitter Peach (warm gourmand, heavy)
UPDATE perfumes SET fresh_warm_score = 0.55, light_heavy_score = 0.65 WHERE id = 's024'; -- Rose Prick (warm spicy rose, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.65, light_heavy_score = 0.75 WHERE id = 's025'; -- Ombre Leather (warm leather, heavy)
UPDATE perfumes SET fresh_warm_score = 0.45, light_heavy_score = 0.50 WHERE id = 's026'; -- Soleil Blanc (balanced, medium)
UPDATE perfumes SET fresh_warm_score = 0.65, light_heavy_score = 0.70 WHERE id = 's027'; -- Cafe Rose (warm coffee rose, heavy)
UPDATE perfumes SET fresh_warm_score = 0.15, light_heavy_score = 0.40 WHERE id = 's028'; -- Grey Vetiver (fresh vetiver, medium)
UPDATE perfumes SET fresh_warm_score = 0.90, light_heavy_score = 0.90 WHERE id = 's029'; -- Tobacco Oud (very warm, very heavy)
UPDATE perfumes SET fresh_warm_score = 0.15, light_heavy_score = 0.35 WHERE id = 's030'; -- Costa Azzurra (fresh coastal, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.75, light_heavy_score = 0.80 WHERE id = 's031'; -- Noir de Noir (warm, very heavy)
UPDATE perfumes SET fresh_warm_score = 0.40, light_heavy_score = 0.55 WHERE id = 's032'; -- White Patchouli (balanced, medium)
UPDATE perfumes SET fresh_warm_score = 0.05, light_heavy_score = 0.15 WHERE id = 's033'; -- Mandarino di Amalfi (very fresh citrus, light)
UPDATE perfumes SET fresh_warm_score = 0.75, light_heavy_score = 0.70 WHERE id = 's034'; -- Noir Extreme (warm spicy, heavy)
UPDATE perfumes SET fresh_warm_score = 0.15, light_heavy_score = 0.35 WHERE id = 's035'; -- Beau de Jour (fresh fougere, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.60, light_heavy_score = 0.60 WHERE id = 's036'; -- Velvet Orchid (warm, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.60, light_heavy_score = 0.65 WHERE id = 's037'; -- Jasmin Rouge (warm spicy jasmine, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.45, light_heavy_score = 0.50 WHERE id = 's038'; -- Metallique (balanced, medium)
UPDATE perfumes SET fresh_warm_score = 0.75, light_heavy_score = 0.80 WHERE id = 's039'; -- Ebene Fume (warm smoky, heavy)
UPDATE perfumes SET fresh_warm_score = 0.40, light_heavy_score = 0.35 WHERE id = 's040'; -- White Suede (balanced, light-medium)

-- Creed (s041-s050)
UPDATE perfumes SET fresh_warm_score = 0.30, light_heavy_score = 0.50 WHERE id = 's041'; -- Viking (fresh spicy, medium)
UPDATE perfumes SET fresh_warm_score = 0.50, light_heavy_score = 0.60 WHERE id = 's042'; -- Royal Oud (balanced, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.10, light_heavy_score = 0.25 WHERE id = 's043'; -- Millesime Imperial (fresh aquatic, light)
UPDATE perfumes SET fresh_warm_score = 0.60, light_heavy_score = 0.55 WHERE id = 's044'; -- Original Santal (warm, medium)
UPDATE perfumes SET fresh_warm_score = 0.10, light_heavy_score = 0.20 WHERE id = 's045'; -- Himalaya (fresh, light)
UPDATE perfumes SET fresh_warm_score = 0.25, light_heavy_score = 0.30 WHERE id = 's046'; -- Wind Flowers (fresh floral, light)
UPDATE perfumes SET fresh_warm_score = 0.05, light_heavy_score = 0.15 WHERE id = 's047'; -- Virgin Island Water (very fresh tropical, light)
UPDATE perfumes SET fresh_warm_score = 0.10, light_heavy_score = 0.20 WHERE id = 's048'; -- Royal Water (fresh aquatic, light)
UPDATE perfumes SET fresh_warm_score = 0.15, light_heavy_score = 0.35 WHERE id = 's049'; -- Original Vetiver (fresh green, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.50, light_heavy_score = 0.50 WHERE id = 's050'; -- Royal Princess Oud (balanced, medium)

-- Selected from other batches for variety
UPDATE perfumes SET fresh_warm_score = 0.15, light_heavy_score = 0.30 WHERE id = 's051'; -- Versace Pour Homme (fresh, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.15, light_heavy_score = 0.20 WHERE id = 's052'; -- Bright Crystal (fresh, light)
UPDATE perfumes SET fresh_warm_score = 0.60, light_heavy_score = 0.55 WHERE id = 's053'; -- Crystal Noir (warm, medium)
UPDATE perfumes SET fresh_warm_score = 0.35, light_heavy_score = 0.45 WHERE id = 's054'; -- Eros Pour Femme (balanced, medium)
UPDATE perfumes SET fresh_warm_score = 0.10, light_heavy_score = 0.15 WHERE id = 's055'; -- Yellow Diamond (fresh, light)
UPDATE perfumes SET fresh_warm_score = 0.50, light_heavy_score = 0.55 WHERE id = 's056'; -- Eros Flame (balanced, medium)
UPDATE perfumes SET fresh_warm_score = 0.70, light_heavy_score = 0.65 WHERE id = 's064'; -- 1 Million (warm spicy, medium-heavy)
UPDATE perfumes SET fresh_warm_score = 0.60, light_heavy_score = 0.50 WHERE id = 's071'; -- Le Male (warm, medium)
UPDATE perfumes SET fresh_warm_score = 0.50, light_heavy_score = 0.45 WHERE id = 's077'; -- Libre (balanced, medium)
UPDATE perfumes SET fresh_warm_score = 0.80, light_heavy_score = 0.80 WHERE id = 's079'; -- Opium (very warm, heavy)
UPDATE perfumes SET fresh_warm_score = 0.75, light_heavy_score = 0.85 WHERE id = 's084'; -- Shalimar (warm, very heavy)
UPDATE perfumes SET fresh_warm_score = 0.50, light_heavy_score = 0.50 WHERE id = 's085'; -- Mon Guerlain (balanced, medium)
UPDATE perfumes SET fresh_warm_score = 0.35, light_heavy_score = 0.55 WHERE id = 's091'; -- L'Interdit (balanced, medium)
UPDATE perfumes SET fresh_warm_score = 0.30, light_heavy_score = 0.40 WHERE id = 's096'; -- Armani Code (balanced, medium)
UPDATE perfumes SET fresh_warm_score = 0.15, light_heavy_score = 0.30 WHERE id = 's098'; -- Acqua di Gio Profondo (fresh, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.25, light_heavy_score = 0.45 WHERE id = 's101'; -- Terre d'Hermes (fresh earthy, medium)
UPDATE perfumes SET fresh_warm_score = 0.10, light_heavy_score = 0.20 WHERE id = 's102'; -- Un Jardin sur le Nil (very fresh, light)
UPDATE perfumes SET fresh_warm_score = 0.25, light_heavy_score = 0.35 WHERE id = 's107'; -- Luna Rossa Carbon (fresh, light-medium)
UPDATE perfumes SET fresh_warm_score = 0.65, light_heavy_score = 0.70 WHERE id = 's111'; -- Candy (warm sweet, heavy)
UPDATE perfumes SET fresh_warm_score = 0.30, light_heavy_score = 0.40 WHERE id = 's114'; -- Burberry Her (balanced, medium)
UPDATE perfumes SET fresh_warm_score = 0.55, light_heavy_score = 0.60 WHERE id = 's126'; -- Boss Bottled (warm, medium)
